import jsPDF from 'jspdf';

export interface OpcoesExportPdf {
  titulo: string;
  subtitulo?: string;
  autor: string;
  data: string;
  idioma: 'pt' | 'en';
  tema: 'light' | 'dark' | 'sepia';
  incluirCabecalho: boolean;
  incluirRodape: boolean;
  incluirIndice: boolean;
  incluirNumerosVersiculos: boolean;
  fonte: 'serif' | 'sans';
  margem: number;
}

export interface ConteudoExport {
  tipo: 'versiculo' | 'comentario' | 'estudo' | 'nota' | 'capitulo';
  titulo?: string;
  conteudo: string;
  referencia?: string;
  autor?: string;
  metadata?: Record<string, unknown>;
}

interface TemaCores {
  fundo: [number, number, number];
  texto: [number, number, number];
  textoSecundario: [number, number, number];
  primario: [number, number, number];
  primarioEscuro: [number, number, number];
  dourado: [number, number, number];
  borda: [number, number, number];
  fundoCartao: [number, number, number];
  fundoRodape: [number, number, number];
}

const TEMAS: Record<'light' | 'dark' | 'sepia', TemaCores> = {
  light: {
    fundo: [250, 250, 250],
    texto: [30, 30, 30],
    textoSecundario: [120, 120, 120],
    primario: [87, 56, 29],
    primarioEscuro: [60, 38, 18],
    dourado: [180, 140, 50],
    borda: [220, 215, 205],
    fundoCartao: [245, 240, 232],
    fundoRodape: [248, 248, 248],
  },
  dark: {
    fundo: [18, 18, 18],
    texto: [230, 230, 230],
    textoSecundario: [140, 140, 140],
    primario: [212, 168, 67],
    primarioEscuro: [180, 140, 50],
    dourado: [212, 168, 67],
    borda: [50, 50, 50],
    fundoCartao: [30, 30, 30],
    fundoRodape: [25, 25, 25],
  },
  sepia: {
    fundo: [245, 238, 224],
    texto: [74, 55, 40],
    textoSecundario: [122, 110, 98],
    primario: [120, 80, 40],
    primarioEscuro: [90, 60, 30],
    dourado: [180, 140, 60],
    borda: [210, 200, 180],
    fundoCartao: [238, 230, 214],
    fundoRodape: [240, 234, 220],
  },
};

const TEXTO_IDIOMA: Record<string, { paginaDe: string; estudoBiblico: string; indice: string; geradoPor: string; dataGeracao: string; autor: string; sumario: string }> = {
  pt: {
    paginaDe: 'Página',
    estudoBiblico: 'Estudo Bíblico Acadêmico',
    indice: 'Sumário',
    geradoPor: 'Gerado por Sola Scriptura',
    dataGeracao: 'Data de geração',
    autor: 'Autor',
    sumario: 'Sumário',
  },
  en: {
    paginaDe: 'Page',
    estudoBiblico: 'Academic Bible Study',
    indice: 'Table of Contents',
    geradoPor: 'Generated by Sola Scriptura',
    dataGeracao: 'Generation date',
    autor: 'Author',
    sumario: 'Table of Contents',
  },
};

export function criarOpcoesPadrao(titulo: string, overrides?: Partial<OpcoesExportPdf>): OpcoesExportPdf {
  return {
    titulo,
    autor: 'Sola Scriptura',
    data: new Date().toLocaleDateString('pt-BR'),
    idioma: 'pt',
    tema: 'light',
    incluirCabecalho: true,
    incluirRodape: true,
    incluirIndice: false,
    incluirNumerosVersiculos: true,
    fonte: 'serif',
    margem: 20,
    ...overrides,
  };
}

function obterFonte(tipo: 'serif' | 'sans', estilo: 'normal' | 'bold' | 'italic' | 'bolditalic'): string {
  if (tipo === 'serif') {
    switch (estilo) {
      case 'bold': return 'times-bold';
      case 'italic': return 'times-italic';
      case 'bolditalic': return 'times-bolditalic';
      default: return 'times';
    }
  }
  switch (estilo) {
    case 'bold': return 'helvetica-bold';
    case 'italic': return 'helvetica-oblique';
    case 'bolditalic': return 'helvetica-boldoblique';
    default: return 'helvetica';
  }
}

function desenharCabecalho(doc: jsPDF, opcoes: OpcoesExportPdf, cores: TemaCores, tituloPagina: string) {
  const pw = doc.internal.pageSize.getWidth();
  doc.setFillColor(...cores.primarioEscuro);
  doc.rect(0, 0, pw, 14, 'F');

  doc.setDrawColor(...cores.dourado);
  doc.setLineWidth(0.3);
  doc.line(opcoes.margem, 14, pw - opcoes.margem, 14);

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text('Sola Scriptura', opcoes.margem, 9);

  doc.setTextColor(200, 200, 200);
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  const maxTitleW = pw - 2 * opcoes.margem - 40;
  const truncated = tituloPagina.length > 80 ? tituloPagina.substring(0, 77) + '...' : tituloPagina;
  doc.text(truncated, pw - opcoes.margem, 9, { align: 'right' });
}

function desenharRodape(doc: jsPDF, opcoes: OpcoesExportPdf, cores: TemaCores, numPagina: number, totalPaginas: number) {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const txt = TEXTO_IDIOMA[opcoes.idioma];

  doc.setFillColor(...cores.fundoRodape);
  doc.rect(0, ph - 18, pw, 18, 'F');

  doc.setDrawColor(...cores.dourado);
  doc.setLineWidth(0.3);
  doc.line(opcoes.margem, ph - 18, pw - opcoes.margem, ph - 18);

  doc.setTextColor(...cores.textoSecundario);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text(`Sola Scriptura  |  ${opcoes.titulo}`, opcoes.margem, ph - 11);

  doc.setTextColor(...cores.textoSecundario);
  doc.text(`${txt.paginaDe} ${numPagina} / ${totalPaginas}`, pw - opcoes.margem, ph - 11, { align: 'right' });

  doc.setFontSize(6);
  doc.setTextColor(...cores.textoSecundario.slice(0, 3).map(v => Math.min(255, v + 30)) as [number, number, number]);
  doc.text(txt.geradoPor + ' — sola-scriptura-two.vercel.app', pw / 2, ph - 7, { align: 'center' });
}

function desenharCapa(doc: jsPDF, opcoes: OpcoesExportPdf, cores: TemaCores) {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();

  doc.setFillColor(...cores.primarioEscuro);
  doc.rect(0, 0, pw, ph, 'F');

  const goldX = opcoes.margem;
  doc.setDrawColor(...cores.dourado);
  doc.setLineWidth(0.5);
  doc.rect(goldX + 10, 30, pw - 2 * goldX - 20, ph - 60, 'S');

  doc.setLineWidth(0.3);
  doc.rect(goldX + 14, 34, pw - 2 * goldX - 28, ph - 68, 'S');

  doc.setTextColor(...cores.dourado);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.text('Sola Scriptura', pw / 2, ph / 2 - 60, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(200, 180, 140);
  doc.text(TEXTO_IDIOMA[opcoes.idioma].estudoBiblico, pw / 2, ph / 2 - 45, { align: 'center' });

  doc.setDrawColor(...cores.dourado);
  doc.setLineWidth(0.5);
  doc.line(pw / 2 - 40, ph / 2 - 35, pw / 2 + 40, ph / 2 - 35);

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  const tituloLinhas = doc.splitTextToSize(opcoes.titulo, pw - 2 * opcoes.margem - 40);
  doc.text(tituloLinhas, pw / 2, ph / 2 - 10, { align: 'center' });

  if (opcoes.subtitulo) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(13);
    doc.setTextColor(180, 160, 120);
    const subLinhas = doc.splitTextToSize(opcoes.subtitulo, pw - 2 * opcoes.margem - 40);
    doc.text(subLinhas, pw / 2, ph / 2 + 10 + tituloLinhas.length * 8, { align: 'center' });
  }

  const metaY = ph / 2 + 60;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(180, 160, 120);

  const labels = [
    `${TEXTO_IDIOMA[opcoes.idioma].autor}: ${opcoes.autor}`,
    `${TEXTO_IDIOMA[opcoes.idioma].dataGeracao}: ${opcoes.data}`,
  ];
  labels.forEach((label, i) => {
    doc.text(label, pw / 2, metaY + i * 7, { align: 'center' });
  });

  doc.setFontSize(7);
  doc.setTextColor(120, 100, 70);
  doc.text('sola-scriptura-two.vercel.app', pw / 2, ph - 30, { align: 'center' });
}

function desenharIndice(doc: jsPDF, opcoes: OpcoesExportPdf, cores: TemaCores, conteudo: ConteudoExport[]) {
  const pw = doc.internal.pageSize.getWidth();
  const txt = TEXTO_IDIOMA[opcoes.idioma];
  let y = opcoes.margem + 5;

  doc.setFillColor(...cores.fundo);
  doc.rect(0, 0, pw, doc.internal.pageSize.getHeight(), 'F');

  doc.setTextColor(...cores.primario);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(txt.sumario, opcoes.margem, y);
  y += 4;

  doc.setDrawColor(...cores.dourado);
  doc.setLineWidth(0.5);
  doc.line(opcoes.margem, y, pw - opcoes.margem, y);
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  conteudo.forEach((item, i) => {
    if (y > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      y = opcoes.margem + 10;
    }

    const num = String(i + 1).padStart(2, '0');
    const titulo = item.titulo || item.referencia || `${txt.estudoBiblico} ${i + 1}`;

    doc.setTextColor(...cores.primario);
    doc.setFont('helvetica', 'bold');
    doc.text(num, opcoes.margem, y);

    doc.setTextColor(...cores.texto);
    doc.setFont('helvetica', 'normal');
    doc.text(titulo.substring(0, 65), opcoes.margem + 12, y);

    y += 7;
  });
}

function desenharSecao(
  doc: jsPDF,
  opcoes: OpcoesExportPdf,
  cores: TemaCores,
  item: ConteudoExport,
  numSecao: number
) {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const cw = pw - 2 * opcoes.margem;
  let y = opcoes.margem + (opcoes.incluirCabecalho ? 22 : 5);

  if (item.referencia) {
    doc.setTextColor(...cores.primario);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text(item.referencia.toUpperCase(), opcoes.margem, y);
    y += 6;
  }

  if (item.titulo) {
    doc.setTextColor(...cores.primario);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    const tLines = doc.splitTextToSize(item.titulo, cw);
    doc.text(tLines, opcoes.margem, y);
    y += tLines.length * 7 + 3;
  }

  if (item.autor) {
    doc.setTextColor(...cores.textoSecundario);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.text(item.autor, opcoes.margem, y);
    y += 6;
  }

  doc.setDrawColor(...cores.borda);
  doc.setLineWidth(0.3);
  doc.line(opcoes.margem, y, pw - opcoes.margem, y);
  y += 6;

  const bodyFont = obterFonte(opcoes.fonte, 'normal');
  const italicFont = obterFonte(opcoes.fonte, 'italic');

  const linhas = doc.splitTextToSize(item.conteudo, cw);
  doc.setFont(bodyFont);

  for (const linha of linhas) {
    if (y > ph - 25) {
      doc.addPage();
      y = opcoes.margem + (opcoes.incluirCabecalho ? 22 : 10);
      if (opcoes.incluirCabecalho) {
        desenharCabecalho(doc, opcoes, cores, item.titulo || opcoes.titulo);
      }
      doc.setFont(bodyFont);
    }

    const isItalic = linha.startsWith('_') && linha.endsWith('_');
    const isBold = linha.startsWith('**') && linha.endsWith('**');

    if (isItalic) {
      doc.setFont(italicFont);
      doc.setTextColor(...cores.texto);
      doc.text(linha.replace(/^_+|_+$/g, ''), opcoes.margem, y);
      doc.setFont(bodyFont);
    } else if (isBold) {
      doc.setFont(obterFonte(opcoes.fonte, 'bold'));
      doc.setTextColor(...cores.texto);
      doc.text(linha.replace(/^\*+|\*+$/g, ''), opcoes.margem, y);
      doc.setFont(bodyFont);
    } else {
      doc.setTextColor(...cores.texto);
      doc.text(linha, opcoes.margem, y);
    }

    y += 5;
  }
}

function desenharVersiculos(
  doc: jsPDF,
  opcoes: OpcoesExportPdf,
  cores: TemaCores,
  versiculos: { numero: number; texto: string; traducao?: string }[],
  referenciaBase: string
) {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const cw = pw - 2 * opcoes.margem;
  let y = opcoes.margem + (opcoes.incluirCabecalho ? 22 : 5);

  doc.setTextColor(...cores.primario);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(referenciaBase, opcoes.margem, y);
  y += 5;

  doc.setDrawColor(...cores.dourado);
  doc.setLineWidth(0.5);
  doc.line(opcoes.margem, y, opcoes.margem + 40, y);
  y += 8;

  for (const v of versiculos) {
    if (y > ph - 25) {
      doc.addPage();
      y = opcoes.margem + (opcoes.incluirCabecalho ? 22 : 10);
      if (opcoes.incluirCabecalho) {
        desenharCabecalho(doc, opcoes, cores, referenciaBase);
      }
    }

    if (opcoes.incluirNumerosVersiculos) {
      doc.setFillColor(...cores.fundoCartao);
      doc.roundedRect(opcoes.margem, y - 4, 8, 8, 1, 1, 'F');
      doc.setTextColor(...cores.primario);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text(String(v.numero), opcoes.margem + 4, y + 0.5, { align: 'center' });
    }

    const textX = opcoes.incluirNumerosVersiculos ? opcoes.margem + 12 : opcoes.margem;
    const maxW = cw - (textX - opcoes.margem);

    if (v.traducao && versiculos.length > 1) {
      doc.setFillColor(...cores.fundoCartao);
      doc.roundedRect(textX, y - 3.5, 12, 5, 1, 1, 'F');
      doc.setTextColor(...cores.textoSecundario);
      doc.setFontSize(6);
      doc.setFont('helvetica', 'bold');
      doc.text(v.traducao.toUpperCase(), textX + 6, y, { align: 'center' });
    }

    const bodyFont = obterFonte(opcoes.fonte, 'normal');
    doc.setFont(bodyFont);
    doc.setFontSize(10);
    doc.setTextColor(...cores.texto);

    const textoLinhas = doc.splitTextToSize(v.texto, maxW);
    doc.text(textoLinhas, textX, y);

    y += textoLinhas.length * 4.5 + 4;

    doc.setDrawColor(...cores.borda);
    doc.setLineWidth(0.15);
    doc.line(textX, y - 1.5, pw - opcoes.margem, y - 1.5);
    y += 2;
  }
}

export async function exportarPdf(conteudo: ConteudoExport[], opcoes?: Partial<OpcoesExportPdf>): Promise<void> {
  const opts = criarOpcoesPadrao(conteudo[0]?.titulo || 'Sola Scriptura', opcoes);
  const cores = TEMAS[opts.tema];

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw = doc.internal.pageSize.getWidth();

  desenharCapa(doc, opts, cores);
  doc.addPage();

  if (opts.incluirIndice) {
    desenharIndice(doc, opts, cores, conteudo);
    doc.addPage();
  }

  for (let i = 0; i < conteudo.length; i++) {
    if (i > 0) doc.addPage();

    if (opts.incluirCabecalho) {
      desenharCabecalho(doc, opts, cores, conteudo[i].titulo || opts.titulo);
    }

    desenharSecao(doc, opts, cores, conteudo[i], i);
  }

  const totalPages = doc.getNumberOfPages();
  for (let p = 2; p <= totalPages; p++) {
    doc.setPage(p);
    desenharRodape(doc, opts, cores, p, totalPages);
  }

  const nomeArquivo = opts.titulo
    .toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9 ]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .substring(0, 50);

  doc.save(`${nomeArquivo || 'sola-scriptura'}.pdf`);
}

export async function exportarCapitulo(
  livroNome: string,
  capitulo: number,
  versiculos: { numero: number; texto: string; traducao?: string }[],
  opcoes?: Partial<OpcoesExportPdf>
): Promise<void> {
  const titulo = `${livroNome} ${capitulo}`;
  const opts = criarOpcoesPadrao(titulo, opcoes);
  const cores = TEMAS[opts.tema];

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  desenharCapa(doc, opts, cores);
  doc.addPage();

  if (opts.incluirCabecalho) {
    desenharCabecalho(doc, opts, cores, titulo);
  }

  desenharVersiculos(doc, opts, cores, versiculos, titulo);

  const totalPages = doc.getNumberOfPages();
  for (let p = 2; p <= totalPages; p++) {
    doc.setPage(p);
    desenharRodape(doc, opts, cores, p, totalPages);
  }

  const nome = livroNome.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, '_');
  doc.save(`${nome}_${capitulo}.pdf`);
}

export async function exportarEstudo(
  estudo: { titulo: string; conteudo: string; autor?: string; referencia?: string },
  opcoes?: Partial<OpcoesExportPdf>
): Promise<void> {
  const opts = criarOpcoesPadrao(estudo.titulo, opcoes);
  const cores = TEMAS[opts.tema];

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  desenharCapa(doc, opts, cores);
  doc.addPage();

  if (opts.incluirCabecalho) {
    desenharCabecalho(doc, opts, cores, estudo.titulo);
  }

  desenharSecao(doc, opts, cores, {
    tipo: 'estudo',
    titulo: estudo.titulo,
    conteudo: estudo.conteudo,
    referencia: estudo.referencia,
    autor: estudo.autor,
  }, 0);

  const totalPages = doc.getNumberOfPages();
  for (let p = 2; p <= totalPages; p++) {
    doc.setPage(p);
    desenharRodape(doc, opts, cores, p, totalPages);
  }

  doc.save(`${estudo.titulo.substring(0, 50).normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, '_')}.pdf`);
}

export async function exportarVersiculos(
  versiculos: { numero: number; texto: string; traducao?: string; referencia?: string }[],
  referenciaBase: string,
  opcoes?: Partial<OpcoesExportPdf>
): Promise<void> {
  const opts = criarOpcoesPadrao(referenciaBase, opcoes);
  const cores = TEMAS[opts.tema];

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  desenharCapa(doc, opts, cores);
  doc.addPage();

  if (opts.incluirCabecalho) {
    desenharCabecalho(doc, opts, cores, referenciaBase);
  }

  desenharVersiculos(doc, opts, cores, versiculos, referenciaBase);

  const totalPages = doc.getNumberOfPages();
  for (let p = 2; p <= totalPages; p++) {
    doc.setPage(p);
    desenharRodape(doc, opts, cores, p, totalPages);
  }

  doc.save(`${referenciaBase.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, '_')}.pdf`);
}

export async function exportarComentarios(
  referencia: string,
  comentarios: { autor: string; texto: string }[],
  opcoes?: Partial<OpcoesExportPdf>
): Promise<void> {
  const conteudoComentarios = comentarios.map(c => ({
    tipo: 'comentario' as const,
    titulo: c.autor,
    conteudo: c.texto,
    referencia,
    autor: c.autor,
  }));

  const opts = criarOpcoesPadrao(`Comentários — ${referencia}`, opcoes);
  const cores = TEMAS[opts.tema];

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  desenharCapa(doc, opts, cores);
  doc.addPage();

  if (opts.incluirCabecalho) {
    desenharCabecalho(doc, opts, cores, `Comentários — ${referencia}`);
  }

  for (let i = 0; i < conteudoComentarios.length; i++) {
    if (i > 0) doc.addPage();
    desenharSecao(doc, opts, cores, conteudoComentarios[i], i);
  }

  const totalPages = doc.getNumberOfPages();
  for (let p = 2; p <= totalPages; p++) {
    doc.setPage(p);
    desenharRodape(doc, opts, cores, p, totalPages);
  }

  doc.save(`comentarios_${referencia.replace(/\s+/g, '_')}.pdf`);
}

export async function exportarNota(
  nota: { titulo: string; conteudo: string; data?: string; tags?: string[] },
  opcoes?: Partial<OpcoesExportPdf>
): Promise<void> {
  const opts = criarOpcoesPadrao(nota.titulo, opcoes);
  const cores = TEMAS[opts.tema];

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  desenharCapa(doc, opts, cores);
  doc.addPage();

  if (opts.incluirCabecalho) {
    desenharCabecalho(doc, opts, cores, nota.titulo);
  }

  let metaExtra = '';
  if (nota.data) metaExtra += `\nData: ${nota.data}`;
  if (nota.tags?.length) metaExtra += `\nTags: ${nota.tags.join(', ')}`;

  desenharSecao(doc, opts, cores, {
    tipo: 'nota',
    titulo: nota.titulo,
    conteudo: nota.conteudo,
    autor: opts.autor + metaExtra,
  }, 0);

  const totalPages = doc.getNumberOfPages();
  for (let p = 2; p <= totalPages; p++) {
    doc.setPage(p);
    desenharRodape(doc, opts, cores, p, totalPages);
  }

  doc.save(`nota_${nota.titulo.substring(0, 40).normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, '_')}.pdf`);
}

export function downloadAsFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

interface VerseCompat { numero: number; texto: string }
interface TranslationDataCompat { traducao: string; versiculos: VerseCompat[] }

export async function exportChapterPdf(
  livroNome: string,
  capitulo: number,
  data: TranslationDataCompat[]
): Promise<void> {
  const allVersiculos: { numero: number; texto: string; traducao?: string }[] = [];
  const maxVerses = Math.max(...data.map(d => d.versiculos.length));

  for (let i = 0; i < maxVerses; i++) {
    for (const t of data) {
      const v = t.versiculos[i];
      if (v) {
        allVersiculos.push({ numero: v.numero, texto: v.texto, traducao: data.length > 1 ? t.traducao : undefined });
      }
    }
  }

  const traducoes = data.map(d => d.traducao.toUpperCase()).join(' / ');
  await exportarCapitulo(livroNome, capitulo, allVersiculos, {
    titulo: `${livroNome} ${capitulo}`,
    subtitulo: traducoes,
  });
}
