import { downloadAsFile } from './exportPdf';
import { livroPorAbreviacao } from '@/data/biblia';
import type { MarcaBiblia } from './estudos';

export interface OpcoesExport {
  formato: 'pdf' | 'epub' | 'html' | 'markdown' | 'txt';
  incluirVersiculos: boolean;
  incluirComentarios: boolean;
  incluirNotas: boolean;
  incluirReferencias: boolean;
  incluirMetadados: boolean;
  idioma: 'pt' | 'en';
}

export interface EstudoCompleto {
  id: string;
  titulo: string;
  descricao?: string;
  autor: string;
  dataCriacao: string;
  dataAtualizacao?: string;
  referencia?: string;
  versiculos: MarcaBiblia[];
  notas: NotaEstudo[];
  comentarios: ComentarioEstudo[];
  tags: string[];
}

export interface NotaEstudo {
  id: string;
  titulo: string;
  conteudo: string;
  data: string;
  tags: string[];
}

export interface ComentarioEstudo {
  autor: string;
  texto: string;
  fonte?: string;
}

const TEXTO: Record<string, {
  estudoBiblico: string;
  versiculos: string;
  anotacoes: string;
  comentarios: string;
  referencias: string;
  metadados: string;
  autor: string;
  dataCriacao: string;
  geradoPor: string;
  nadaEncontrado: string;
  capitulo: string;
}> = {
  pt: {
    estudoBiblico: 'Estudo Bíblico',
    versiculos: 'Versículos',
    anotacoes: 'Anotações',
    comentarios: 'Comentários',
    referencias: 'Referências',
    metadados: 'Metadados',
    autor: 'Autor',
    dataCriacao: 'Data de criação',
    geradoPor: 'Gerado por Sola Scriptura',
    nadaEncontrado: 'Nenhum conteúdo encontrado',
    capitulo: 'Capítulo',
  },
  en: {
    estudoBiblico: 'Bible Study',
    versiculos: 'Verses',
    anotacoes: 'Notes',
    comentarios: 'Commentaries',
    referencias: 'References',
    metadados: 'Metadata',
    autor: 'Author',
    dataCriacao: 'Creation date',
    geradoPor: 'Generated by Sola Scriptura',
    nadaEncontrado: 'No content found',
    capitulo: 'Chapter',
  },
};

function opcoesPadrao(overrides?: Partial<OpcoesExport>): OpcoesExport {
  return {
    formato: 'pdf',
    incluirVersiculos: true,
    incluirComentarios: true,
    incluirNotas: true,
    incluirReferencias: true,
    incluirMetadados: false,
    idioma: 'pt',
    ...overrides,
  };
}

function nomeLivro(abrev: string): string {
  const livro = livroPorAbreviacao.get(abrev.toLowerCase());
  return livro?.nome || abrev;
}

function formatarRef(m: MarcaBiblia): string {
  return `${nomeLivro(m.livro)} ${m.capitulo}:${m.versiculo}`;
}

export function exportarParaMarkdown(estudo: EstudoCompleto, opcoes?: Partial<OpcoesExport>): string {
  const opts = opcoesPadrao(opcoes);
  const t = TEXTO[opts.idioma];
  const linhas: string[] = [];

  linhas.push(`# ${estudo.titulo}`);
  linhas.push('');

  if (estudo.descricao) {
    linhas.push(`> ${estudo.descricao}`);
    linhas.push('');
  }

  if (opts.incluirMetadados) {
    linhas.push('---');
    linhas.push(`**${t.autor}:** ${estudo.autor}`);
    linhas.push(`**${t.dataCriacao}:** ${estudo.dataCriacao}`);
    if (estudo.tags.length) linhas.push(`**Tags:** ${estudo.tags.join(', ')}`);
    linhas.push('---');
    linhas.push('');
  }

  if (opts.incluirVersiculos && estudo.versiculos.length > 0) {
    linhas.push(`## ${t.versiculos}`);
    linhas.push('');

    const agrupados = new Map<string, MarcaBiblia[]>();
    for (const v of estudo.versiculos) {
      const ref = formatarRef(v);
      if (!agrupados.has(ref)) agrupados.set(ref, []);
      agrupados.get(ref)!.push(v);
    }

    for (const [ref, versiculos] of agrupados) {
      linhas.push(`### ${ref}`);
      linhas.push('');
      for (const v of versiculos) {
        linhas.push(`> **${v.traducao.toUpperCase()}** — "${v.texto}"`);
        linhas.push('');
        if (v.favorito) linhas.push('⭐ **Favorito**');
        if (v.anotacao?.texto) {
          linhas.push(`**Minha anotação:** ${v.anotacao.texto}`);
          linhas.push('');
        }
      }
    }
  }

  if (opts.incluirNotas && estudo.notas.length > 0) {
    linhas.push(`## ${t.anotacoes}`);
    linhas.push('');
    for (const nota of estudo.notas) {
      linhas.push(`### ${nota.titulo}`);
      linhas.push('');
      linhas.push(nota.conteudo);
      linhas.push('');
      if (nota.tags.length) linhas.push(`*Tags: ${nota.tags.join(', ')}*`);
      linhas.push('');
    }
  }

  if (opts.incluirComentarios && estudo.comentarios.length > 0) {
    linhas.push(`## ${t.comentarios}`);
    linhas.push('');
    for (const c of estudo.comentarios) {
      linhas.push(`> **${c.autor}${c.fonte ? ` (${c.fonte})` : ''}:** ${c.texto}`);
      linhas.push('');
    }
  }

  linhas.push('---');
  linhas.push(`*${t.geradoPor}*`);

  return linhas.join('\n');
}

export function exportarParaHTML(estudo: EstudoCompleto, opcoes?: Partial<OpcoesExport>): string {
  const opts = opcoesPadrao(opcoes);
  const t = TEXTO[opts.idioma];

  let html = `<!DOCTYPE html>
<html lang="${opts.idioma}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${estudo.titulo} — Sola Scriptura</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: Georgia, 'Times New Roman', serif;
      color: #1a1612;
      background: #faf8f5;
      line-height: 1.8;
      max-width: 800px;
      margin: 0 auto;
      padding: 2rem 1.5rem;
    }
    header { text-align: center; margin-bottom: 3rem; padding-bottom: 2rem; border-bottom: 2px solid #d4a843; }
    h1 { font-size: 2rem; color: #3a2618; margin-bottom: 0.5rem; }
    h2 { font-size: 1.4rem; color: #7a5030; margin: 2rem 0 1rem; border-left: 3px solid #d4a843; padding-left: 0.75rem; }
    h3 { font-size: 1.1rem; color: #3a2618; margin: 1.5rem 0 0.5rem; }
    blockquote { background: #f5f0e8; border-left: 3px solid #b48c32; padding: 1rem 1.25rem; margin: 1rem 0; border-radius: 0 8px 8px 0; font-style: italic; }
    blockquote strong { font-style: normal; color: #7a5030; }
    .meta { font-size: 0.9rem; color: #7a6e62; }
    .badge { display: inline-block; background: #f5f0e8; color: #7a5030; font-size: 0.7rem; font-weight: 700; padding: 2px 8px; border-radius: 4px; text-transform: uppercase; letter-spacing: 0.05em; }
    .favorito { color: #d4a843; }
    .nota { background: #fff; border: 1px solid #e0d8cc; border-radius: 8px; padding: 1rem; margin: 0.75rem 0; }
    footer { text-align: center; margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid #e0d8cc; color: #7a6e62; font-size: 0.85rem; }
    @media print {
      body { padding: 0; max-width: none; }
      header, footer { break-inside: avoid; }
    }
  </style>
</head>
<body>
  <header>
    <h1>${estudo.titulo}</h1>
    ${estudo.descricao ? `<p class="meta">${estudo.descricao}</p>` : ''}
    ${opts.incluirMetadados ? `
    <div class="meta" style="margin-top:1rem">
      <span>${t.autor}: ${estudo.autor}</span> · <span>${t.dataCriacao}: ${estudo.dataCriacao}</span>
      ${estudo.tags.length ? `<br><span>Tags: ${estudo.tags.join(', ')}</span>` : ''}
    </div>` : ''}
  </header>
  <main>`;

  if (opts.incluirVersiculos && estudo.versiculos.length > 0) {
    html += `\n    <h2>${t.versiculos}</h2>`;
    const agrupados = new Map<string, MarcaBiblia[]>();
    for (const v of estudo.versiculos) {
      const ref = formatarRef(v);
      if (!agrupados.has(ref)) agrupados.set(ref, []);
      agrupados.get(ref)!.push(v);
    }
    for (const [ref, versiculos] of agrupados) {
      html += `\n    <h3>${ref}</h3>`;
      for (const v of versiculos) {
        html += `\n    <blockquote><strong><span class="badge">${v.traducao.toUpperCase()}</span></strong> &ldquo;${v.texto}&rdquo;</blockquote>`;
        if (v.anotacao?.texto) {
          html += `\n    <div class="nota"><strong>Anotação:</strong> ${v.anotacao.texto}</div>`;
        }
      }
    }
  }

  if (opts.incluirNotas && estudo.notas.length > 0) {
    html += `\n    <h2>${t.anotacoes}</h2>`;
    for (const nota of estudo.notas) {
      html += `\n    <h3>${nota.titulo}</h3>`;
      html += `\n    <div class="nota">${nota.conteudo.replace(/\n/g, '<br>')}</div>`;
      if (nota.tags.length) {
        html += `\n    <p class="meta"><em>Tags: ${nota.tags.join(', ')}</em></p>`;
      }
    }
  }

  if (opts.incluirComentarios && estudo.comentarios.length > 0) {
    html += `\n    <h2>${t.comentarios}</h2>`;
    for (const c of estudo.comentarios) {
      html += `\n    <blockquote><strong>${c.autor}${c.fonte ? ` (${c.fonte})` : ''}:</strong> ${c.texto}</blockquote>`;
    }
  }

  html += `
  </main>
  <footer>
    <p>${t.geradoPor}</p>
  </footer>
</body>
</html>`;

  return html;
}

export function exportarParaTXT(estudo: EstudoCompleto, opcoes?: Partial<OpcoesExport>): string {
  const opts = opcoesPadrao(opcoes);
  const t = TEXTO[opts.idioma];
  const linhas: string[] = [];

  linhas.push('='.repeat(60));
  linhas.push(estudo.titulo.toUpperCase());
  linhas.push('='.repeat(60));
  linhas.push('');

  if (opts.incluirMetadados) {
    linhas.push(`${t.autor}: ${estudo.autor}`);
    linhas.push(`${t.dataCriacao}: ${estudo.dataCriacao}`);
    if (estudo.tags.length) linhas.push(`Tags: ${estudo.tags.join(', ')}`);
    linhas.push('');
    linhas.push('-'.repeat(40));
  }

  if (opts.incluirVersiculos && estudo.versiculos.length > 0) {
    linhas.push('');
    linhas.push(`  ${t.versiculos.toUpperCase()}`);
    linhas.push('');

    for (const v of estudo.versiculos) {
      linhas.push(`[${formatarRef(v)}] (${v.traducao.toUpperCase()})`);
      linhas.push(`"${v.texto}"`);
      if (v.anotacao?.texto) {
        linhas.push(`  >> ${v.anotacao.texto}`);
      }
      linhas.push('');
    }
  }

  if (opts.incluirNotas && estudo.notas.length > 0) {
    linhas.push(`  ${t.anotacoes.toUpperCase()}`);
    linhas.push('');
    for (const nota of estudo.notas) {
      linhas.push(`--- ${nota.titulo} ---`);
      linhas.push(nota.conteudo);
      linhas.push('');
    }
  }

  if (opts.incluirComentarios && estudo.comentarios.length > 0) {
    linhas.push(`  ${t.comentarios.toUpperCase()}`);
    linhas.push('');
    for (const c of estudo.comentarios) {
      linhas.push(`[${c.autor}]: ${c.texto}`);
      linhas.push('');
    }
  }

  linhas.push('-'.repeat(40));
  linhas.push(t.geradoPor);

  return linhas.join('\n');
}

export async function exportarParaEPUB(
  estudo: EstudoCompleto,
  opcoes?: Partial<OpcoesExport>
): Promise<void> {
  const { gerarEpub } = await import('./exportEpub');

  const capitulos: { titulo: string; conteudo: string }[] = [];
  const opts = opcoesPadrao(opcoes);

  if (opts.incluirVersiculos && estudo.versiculos.length > 0) {
    const agrupados = new Map<string, MarcaBiblia[]>();
    for (const v of estudo.versiculos) {
      const ref = formatarRef(v);
      if (!agrupados.has(ref)) agrupados.set(ref, []);
      agrupados.get(ref)!.push(v);
    }

    for (const [ref, versiculos] of agrupados) {
      let conteudo = `<h2>${ref}</h2>\n`;
      for (const v of versiculos) {
        conteudo += `<p class="verse"><sup class="verse-num">${v.versiculo}</sup> <em>(${v.traducao.toUpperCase()})</em> "${v.texto}"</p>\n`;
        if (v.anotacao?.texto) {
          conteudo += `<div class="note"><strong>Anotação:</strong> ${v.anotacao.texto}</div>\n`;
        }
      }
      capitulos.push({ titulo: ref, conteudo });
    }
  }

  if (opts.incluirNotas && estudo.notas.length > 0) {
    for (const nota of estudo.notas) {
      capitulos.push({
        titulo: nota.titulo,
        conteudo: `<div>${nota.conteudo.replace(/\n/g, '</p><p>')}</div>`,
      });
    }
  }

  if (opts.incluirComentarios && estudo.comentarios.length > 0) {
    let conteudo = '';
    for (const c of estudo.comentarios) {
      conteudo += `<blockquote><strong>${c.autor}${c.fonte ? ` (${c.fonte})` : ''}:</strong> ${c.texto}</blockquote>\n`;
    }
    capitulos.push({ titulo: 'Comentários', conteudo });
  }

  if (capitulos.length === 0) {
    capitulos.push({ titulo: estudo.titulo, conteudo: `<p>${estudo.descricao || 'Estudo vazio.'}</p>` });
  }

  const blob = await gerarEpub({
    titulo: estudo.titulo,
    autor: estudo.autor,
    descricao: estudo.descricao || '',
    capitulos,
    idioma: opts.idioma === 'pt' ? 'pt-BR' : 'en',
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${estudo.titulo.substring(0, 50).normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, '_')}.epub`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function exportarEstudoCompleto(
  estudo: EstudoCompleto,
  opcoes?: Partial<OpcoesExport>
): Promise<void> {
  const opts = opcoesPadrao(opcoes);

  switch (opts.formato) {
    case 'markdown': {
      const md = exportarParaMarkdown(estudo, opcoes);
      downloadAsFile(md, `${estudo.titulo.substring(0, 50)}.md`, 'text/markdown;charset=utf-8');
      break;
    }
    case 'html': {
      const html = exportarParaHTML(estudo, opcoes);
      downloadAsFile(html, `${estudo.titulo.substring(0, 50)}.html`, 'text/html;charset=utf-8');
      break;
    }
    case 'txt': {
      const txt = exportarParaTXT(estudo, opcoes);
      downloadAsFile(txt, `${estudo.titulo.substring(0, 50)}.txt`, 'text/plain;charset=utf-8');
      break;
    }
    case 'epub': {
      await exportarParaEPUB(estudo, opcoes);
      break;
    }
    case 'pdf': {
      const { exportarEstudo } = await import('./exportPdf');
      const conteudoPdf = [];

      if (opts.incluirVersiculos && estudo.versiculos.length > 0) {
        for (const v of estudo.versiculos) {
          conteudoPdf.push({
            tipo: 'versiculo' as const,
            titulo: formatarRef(v),
            conteudo: `"${v.texto}"`,
            referencia: formatarRef(v),
          });
        }
      }

      if (opts.incluirNotas && estudo.notas.length > 0) {
        for (const nota of estudo.notas) {
          conteudoPdf.push({
            tipo: 'nota' as const,
            titulo: nota.titulo,
            conteudo: nota.conteudo,
          });
        }
      }

      if (opts.incluirComentarios && estudo.comentarios.length > 0) {
        for (const c of estudo.comentarios) {
          conteudoPdf.push({
            tipo: 'comentario' as const,
            titulo: c.autor,
            conteudo: c.texto,
            autor: c.autor,
          });
        }
      }

      if (conteudoPdf.length === 0) {
        conteudoPdf.push({
          tipo: 'estudo' as const,
          titulo: estudo.titulo,
          conteudo: estudo.descricao || 'Estudo vazio',
        });
      }

      await exportarEstudo({
        titulo: estudo.titulo,
        conteudo: conteudoPdf.map(c => c.conteudo).join('\n\n'),
        autor: estudo.autor,
        referencia: estudo.referencia,
      }, { idioma: opts.idioma });
      break;
    }
  }
}

export function exportToJson(marcas: MarcaBiblia[]) {
  const data = marcas.map(m => ({
    referencia: formatarRef(m),
    traducao: m.traducao,
    texto: m.texto,
    favorito: m.favorito,
    anotacao: m.anotacao?.texto || null,
    data: new Date(m.dataCriacao).toISOString(),
  }));
  downloadAsFile(JSON.stringify(data, null, 2), 'meus-estudos.json', 'application/json');
}

export function exportToTxt(marcas: MarcaBiblia[]) {
  const lines = marcas.map(m => {
    const ref = formatarRef(m);
    let out = `${ref} (${m.traducao})\n${m.texto}`;
    if (m.anotacao?.texto) {
      out += `\n\nAnotação:\n${m.anotacao.texto}`;
    }
    return out;
  });
  const content = lines.join('\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n');
  downloadAsFile(content, 'meus-estudos.txt', 'text/plain;charset=utf-8');
}

export function exportToCsv(marcas: MarcaBiblia[]) {
  const header = 'Livro,Capítulo,Versículo,Tradução,Texto,Favorito,Anotação,Data';
  const rows = marcas.map(m => {
    const livro = nomeLivro(m.livro);
    const texto = `"${m.texto.replace(/"/g, '""')}"`;
    const anotacao = m.anotacao?.texto ? `"${m.anotacao.texto.replace(/"/g, '""')}"` : '';
    return `${livro},${m.capitulo},${m.versiculo},${m.traducao},${texto},${m.favorito},${anotacao},${new Date(m.dataCriacao).toISOString()}`;
  });
  const bom = '\uFEFF';
  downloadAsFile(bom + [header, ...rows].join('\n'), 'meus-estudos.csv', 'text/csv;charset=utf-8');
}

export function gerarLinkCompartilhamento(estudoId: string): string {
  if (typeof window !== 'undefined') {
    return `${window.location.origin}/compartilhar/estudo/${estudoId}`;
  }
  return `https://sola-scriptura-two.vercel.app/compartilhar/estudo/${estudoId}`;
}
