import fs from 'fs';
const path = 'C:\\Sola Scriptura BR\\src\\data\\comentarios.ts';
let content = fs.readFileSync(path, 'utf8');
let count = 0;

// Common English phrases that appear in Matthew Henry comments
const phraseReplacements = [
  // Common patterns
  ["Here is, I.", "Aqui está: I."],
  ["Here is, 1.", "Aqui está: 1."],
  ["Here we have,", "Aqui temos:"],
  ["Here we have,\\\\nI.", "Aqui temos: I."],
  ["Here, I.", "Aqui, I."],
  ["Here, 1.", "Aqui, 1."],
  ["Observe, I.", "Observe: I."],
  ["Observe, 1.", "Observe: 1."],
  ["Observe here,", "Observe aqui:"],
  ["We have here,", "Temos aqui:"],
  ["We are here told,", "Somos aqui informados:"],
  ["We may suppose", "Podemos supor"],
  ["We read before", "Lemos antes"],
  
  // Common theological terms
  ["the Lord Jesus Christ", "o Senhor Jesus Cristo"],
  ["Jesus Christ", "Jesus Cristo"],
  ["the Holy Ghost", "o Espírito Santo"],
  ["the Holy Spirit", "o Espírito Santo"],
  ["the kingdom of God", "o reino de Deus"],
  ["the kingdom of heaven", "o reino dos céus"],
  ["the church", "a igreja"],
  ["the gospel", "o evangelho"],
  ["the apostle", "o apóstolo"],
  ["the psalmist", "o salmista"],
  ["the prophet", "o profeta"],
  ["the Lord", "o Senhor"],
  ["God", "Deus"],
  
  // Common structural phrases
  ["In these verses", "Nestes versículos"],
  ["In this passage", "Nesta passagem"],
  ["In this psalm", "Neste salmo"],
  ["In this chapter", "Neste capítulo"],
  ["In this epistle", "Nesta epístola"],
  ["In this paragraph", "Neste parágrafo"],
  
  // Common Matthew Henry phrases
  ["Observe, 1.", "Observe: 1."],
  ["Observe, I.", "Observe: I."],
  ["Note,", "Nota:"],
  ["Note.", "Nota."],
  ["We must here", "Devemos aqui"],
  ["We are here", "Estamos aqui"],
  ["Here we are", "Aqui estamos"],
  ["Here he is", "Aqui ele está"],
  ["Here it is", "Aqui está"],
  ["Here they are", "Aqui estão"],
  ["Here we see", "Aqui vemos"],
  ["Here we find", "Aqui encontramos"],
  ["Here we have", "Aqui temos"],
  ["Here is", "Aqui está"],
  ["Here was", "Aqui havia"],
  ["Here are", "Aqui estão"],
  ["Here we may", "Aqui podemos"],
  ["Here we must", "Aqui devemos"],
  ["Here the apostle", "Aqui o apóstolo"],
  ["Here the psalmist", "Aqui o salmista"],
  ["Here the prophet", "Aqui o profeta"],
  ["Here David", "Aqui Davi"],
  ["Here Job", "Aqui Jó"],
  ["Here Solomon", "Aqui Salomão"],
  ["Here Moses", "Aqui Moisés"],
  ["Here Joshua", "Aqui Josué"],
  ["Here Samuel", "Aqui Samuel"],
  ["Here Elijah", "Aqui Elias"],
  ["Here Elisha", "Aqui Eliseu"],
  ["Here Isaiah", "Aqui Isaías"],
  ["Here Jeremiah", "Aqui Jeremias"],
  ["Here Ezekiel", "Aqui Ezequiel"],
  ["Here Daniel", "Aqui Daniel"],
  ["Here Peter", "Aqui Pedro"],
  ["Here Paul", "Aqui Paulo"],
  ["Here John", "Aqui João"],
  ["Here James", "Aqui Tiago"],
  ["Here Jude", "Aqui Judas"],
  
  // Common verbs and phrases
  ["he says", "ele diz"],
  ["he tells", "ele diz"],
  ["he shows", "ele mostra"],
  ["he teaches", "ele ensina"],
  ["he explains", "ele explica"],
  ["he declares", "ele declara"],
  ["he reveals", "ele revela"],
  ["he describes", "ele descreve"],
  ["he mentions", "ele menciona"],
  ["he observes", "ele observa"],
  ["he notes", "ele observa"],
  ["he remarks", "ele observa"],
  ["he points out", "ele aponta"],
  ["he makes", "ele faz"],
  ["he gives", "ele dá"],
  ["he brings", "ele traz"],
  ["he leads", "ele leva"],
  ["he guides", "ele guia"],
  ["he directs", "ele dirige"],
  ["he instructs", "ele instrui"],
  ["he warns", "ele avisa"],
  ["he exhorts", "ele exorta"],
  ["he encourages", "ele encoraja"],
  ["he comforts", "ele consola"],
  ["he rebukes", "ele repreende"],
  ["he corrects", "ele corrige"],
  ["he punishes", "ele pune"],
  ["he rewards", "ele recompensa"],
  ["he blesses", "ele abençoa"],
  ["he curses", "ele amaldiçoa"],
  ["he destroys", "ele destrói"],
  ["he saves", "ele salva"],
  ["he delivers", "ele livra"],
  ["he heals", "ele cura"],
  ["he protects", "ele protege"],
  ["he provides", "ele provê"],
  ["he supplies", "ele supre"],
  ["he supports", "ele sustenta"],
  ["he sustains", "ele sustenta"],
  ["he maintains", "ele mantém"],
  ["he preserves", "ele preserva"],
  ["he keeps", "ele guarda"],
  ["he watches", "ele vigia"],
  ["he waits", "ele espera"],
  ["he comes", "ele vem"],
  ["he goes", "ele vai"],
  ["he returns", "ele retorna"],
  ["he speaks", "ele fala"],
  ["he hears", "ele ouve"],
  ["he sees", "ele vê"],
  ["he knows", "ele sabe"],
  ["he understands", "ele entende"],
  ["he remembers", "ele lembra"],
  ["he forgets", "ele esquece"],
  ["he loves", "ele ama"],
  ["he hates", "ele odeia"],
  ["he fears", "ele teme"],
  ["he trusts", "ele confia"],
  ["he hopes", "ele espera"],
  ["he believes", "ele crê"],
  ["he doubts", "ele duvida"],
  ["he wonders", "ele admira"],
  ["he rejoices", "ele se alegra"],
  ["he mourns", "ele chora"],
  ["he weeps", "ele chora"],
  ["he laughs", "ele ri"],
  ["he is glad", "ele está feliz"],
  ["he is sorry", "ele está arrependido"],
  ["he is angry", "ele está irado"],
  ["he is patient", "ele é paciente"],
  ["he is merciful", "ele é misericordioso"],
  ["he is just", "ele é justo"],
  ["he is holy", "ele é santo"],
  ["he is good", "ele é bom"],
  ["he is great", "ele é grande"],
  ["he is powerful", "ele é poderoso"],
  ["he is wise", "ele é sábio"],
  ["he is faithful", "ele é fiel"],
  ["he is true", "ele é verdadeiro"],
  ["he is eternal", "ele é eterno"],
  ["he is unchanging", "ele é imutável"],
  
  // Common sentence structures
  ["It is said", "É dito"],
  ["It is written", "Está escrito"],
  ["It is reported", "É relatado"],
  ["It is mentioned", "É mencionado"],
  ["It is observed", "É observado"],
  ["It is noted", "É notado"],
  ["It is remarked", "É observado"],
  ["It is to be observed", "Deve-se observar"],
  ["It is to be noted", "Deve-se notar"],
  ["It is to be remembered", "Deve-se lembrar"],
  ["It is to be considered", "Deve-se considerar"],
  ["It is to be observed that", "Deve-se observar que"],
  ["It is to be noted that", "Deve-se notar que"],
  ["It is to be remembered that", "Deve-se lembrar que"],
  ["It is to be considered that", "Deve-se considerar que"],
  
  // Common theological concepts
  ["the grace of God", "a graça de Deus"],
  ["the love of God", "o amor de Deus"],
  ["the mercy of God", "a misericórdia de Deus"],
  ["the justice of God", "a justiça de Deus"],
  ["the wisdom of God", "a sabedoria de Deus"],
  ["the power of God", "o poder de Deus"],
  ["the will of God", "a vontade de Deus"],
  ["the word of God", "a palavra de Deus"],
  ["the house of God", "a casa de Deus"],
  ["the people of God", "o povo de Deus"],
  ["the children of God", "os filhos de Deus"],
  ["the saints of God", "os santos de Deus"],
  ["the servants of God", "os servos de Deus"],
  ["the ministers of God", "os ministros de Deus"],
  ["the prophets of God", "os profetas de Deus"],
  ["the apostles of God", "os apóstolos de Deus"],
  
  // Common biblical references
  ["Psa.", "Sl."],
  ["Pro.", "Pv."],
  ["Ecc.", "Ec."],
  ["Isa.", "Is."],
  ["Jer.", "Jr."],
  ["Eze.", "Ez."],
  ["Dan.", "Dn."],
  ["Hos.", "Os."],
  ["Amo.", "Am."],
  ["Mic.", "Mq."],
  ["Zac.", "Zc."],
  ["Mat.", "Mt."],
  ["Mar.", "Mc."],
  ["Luk.", "Lc."],
  ["Joh.", "Jo."],
  ["Act.", "At."],
  ["Rom.", "Rm."],
  ["Co1.", "1 Co."],
  ["Co2.", "2 Co."],
  ["Gal.", "Gl."],
  ["Eph.", "Ef."],
  ["Phi.", "Fl."],
  ["Col.", "Cl."],
  ["Th1.", "1 Ts."],
  ["Th2.", "2 Ts."],
  ["Ti1.", "1 Tm."],
  ["Ti2.", "2 Tm."],
  ["Heb.", "Hb."],
  ["Jam.", "Tg."],
  ["Pe1.", "1 Pe."],
  ["Pe2.", "2 Pe."],
  ["Jo1.", "1 Jo."],
  ["Jo2.", "2 Jo."],
  ["Jo3.", "3 Jo."],
  ["Jde.", "Jd."],
  ["Rev.", "Ap."],
];

// Apply phrase replacements
for (const [eng, pt] of phraseReplacements) {
  const regex = new RegExp(eng.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
  const newContent = content.replace(regex, pt);
  if (newContent !== content) {
    count++;
    content = newContent;
  }
}

fs.writeFileSync(path, content, 'utf8');
console.log(`Applied ${count} phrase replacements`);
