FROM node:20-alpine AS builder

WORKDIR /app

COPY backend/package*.json ./
RUN npm ci --only=production
RUN cp -R node_modules /prod_modules
RUN npm ci

COPY backend/tsconfig*.json ./
COPY backend/src ./src
COPY backend/nest-cli.json ./

RUN npm run build

FROM node:20-alpine AS production

WORKDIR /app

COPY --from=builder /prod_modules ./node_modules
COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production

EXPOSE 4000

CMD ["node", "dist/main.js"]
