export interface LivroIntroducao {
  nome: string;
  autor: string;
  data: string;
  tema: string;
  contextoHistorico: string;
  esboco: string[];
  temasTeologicos: string[];
  capitulos: number;
  testamento: string;
  genero: string;
  versiculoChave?: string[];
  cristologia?: string;
}

export const LIVROS_INTRODUCOES: Record<string, LivroIntroducao> = {
  "Gênesis": {
    nome: "Gênesis",
    autor: "Moisés",
    data: "c. 1445-1405 a.C.",
    tema: "Os princípios: criação, queda, redenção",
    contextoHistorico: "Moisés escreveu para Israel recém-liberto do Egito, estabelecendo a origem do universo, do pecado, da aliança e da promessa messiânica. Os primeiros 11 capítulos cobrem milhares de anos.",
    esboco: ["1. Criação (1-2)","2. Queda (3-5)","3. Dilúvio (6-9)","4. Babel (10-11)","5. Abraão (12-25)","6. Isaque e Jacó (26-36)","7. José (37-50)"],
    temasTeologicos: ["Criação ex nihilo","Queda e pecado original","Aliança abraâmica","Soberania de Deus","Promessa messiânica (3:15)"],
    capitulos: 50, testamento: "AT", genero: "Lei",
    versiculoChave: ["Gênesis 1:1","Gênesis 3:15","Gênesis 12:3","Gênesis 50:20"],
    cristologia: "Semente da mulher (3:15). O cordeiro provido por Deus (22:8). O descendente de Abraão que abençoará todas as nações (12:3)."
  },
  "Êxodo": {
    nome: "Êxodo",
    autor: "Moisés",
    data: "c. 1445-1405 a.C.",
    tema: "Redenção do Egito e estabelecimento da aliança",
    contextoHistorico: "Israel, escravizado no Egito por 400 anos, é liberto por Deus através de Moisés com sinais, pragas e a Páscoa. A Lei é entregue no Sinai. O tabernáculo é construído.",
    esboco: ["1. Escravidão e Moisés (1-4)","2. Pragas e Páscoa (5-12)","3. Êxodo e Mar Vermelho (13-15)","4. Jornada ao Sinai (16-18)","5. Lei e Mandamentos (19-24)","6. Tabernáculo (25-40)"],
    temasTeologicos: ["Redenção","Aliança mosaica","Santidade de Deus","Presença divina","Adoração"],
    capitulos: 40, testamento: "AT", genero: "Lei",
    versiculoChave: ["Êxodo 3:14","Êxodo 12:13","Êxodo 20:3-17"],
    cristologia: "O cordeiro pascal cujo sangue livra da morte (12). O libertador maior que Moisés. O tabernáculo prefigurando a encarnação (25:8)."
  },
  "Levítico": {
    nome: "Levítico",
    autor: "Moisés",
    data: "c. 1445-1405 a.C.",
    tema: "Santidade e adoração do povo de Deus",
    contextoHistorico: "Israel no Sinai recebe as leis cerimoniais, sacerdotais e morais. O livro revela como um Deus santo habita com um povo pecador por meio de sacrifícios expiatórios.",
    esboco: ["1. Sacrifícios (1-7)","2. Sacerdotes (8-10)","3. Pureza (11-15)","4. Expiação (16)","5. Santidade prática (17-27)"],
    temasTeologicos: ["Santidade de Deus","Sacrifício expiatório","Pureza ritual","Sacerdócio","Lei moral"],
    capitulos: 27, testamento: "AT", genero: "Lei",
    versiculoChave: ["Levítico 11:44","Levítico 19:2","Levítico 20:7-8"],
    cristologia: "O sacrifício perfeito. O Sumo Sacerdote definitivo segundo a ordem de Melquisedeque."
  },
  "Números": {
    nome: "Números",
    autor: "Moisés",
    data: "c. 1445-1405 a.C.",
    tema: "Jornada e disciplina de Israel no deserto",
    contextoHistorico: "A recusa de Israel em entrar em Canaã resulta em 40 anos de peregrinação. A infidelidade do povo contrasta com a fidelidade de Deus.",
    esboco: ["1. Censo e organização (1-10)","2. Rebelião no deserto (11-20)","3. Balaão e Balac (21-25)","4. Nova geração (26-36)"],
    temasTeologicos: ["Fidelidade de Deus","Julgamento","Liderança","Herança","Incredulidade"],
    capitulos: 36, testamento: "AT", genero: "Lei",
    versiculoChave: ["Números 6:24-26","Números 14:18"],
    cristologia: "A rocha ferida que dá água viva (20:8-11). A estrela de Jacó (24:17)."
  },
  "Deuteronômio": {
    nome: "Deuteronômio",
    autor: "Moisés",
    data: "c. 1405 a.C.",
    tema: "Renovação da aliança e preparação para a Terra Prometida",
    contextoHistorico: "Moisés, prestes a morrer, recapitula a Lei e exorta a nova geração à fidelidade antes de entrar em Canaã. O livro mais citado por Jesus.",
    esboco: ["1. Recordação histórica (1-4)","2. Segunda Lei (5-28)","3. Renovação da aliança (29-30)","4. Despedida de Moisés (31-34)"],
    temasTeologicos: ["Aliança","Obediência","Bênção e maldição","Amor a Deus","Eleição divina"],
    capitulos: 34, testamento: "AT", genero: "Lei",
    versiculoChave: ["Deuteronômio 6:4-5","Deuteronômio 30:19-20"],
    cristologia: "O profeta maior que Moisés que Deus levantaria (18:15-18)."
  },
  "Josué": {
    nome: "Josué",
    autor: "Josué (com Samuel?)",
    data: "c. 1390 a.C.",
    tema: "Conquista e distribuição da Terra Prometida",
    contextoHistorico: "Josué lidera Israel na conquista de Canaã sob o comando divino, cumprindo a promessa feita a Abraão há 700 anos. A terra é distribuída entre as doze tribos.",
    esboco: ["1. Entrada em Canaã (1-5)","2. Conquista do centro (6-9)","3. Conquista do sul e norte (10-12)","4. Distribuição tribal (13-22)","5. Aliança final de Josué (23-24)"],
    temasTeologicos: ["Fidelidade de Deus","Conquista pela fé","Herança prometida","Liderança fiel","Obediência"],
    capitulos: 24, testamento: "AT", genero: "História",
    versiculoChave: ["Josué 1:8-9","Josué 24:15"],
    cristologia: "O comandante do exército do Senhor (5:13-15). O Josué maior que conduz à verdadeira terra prometida."
  },
  "Juízes": {
    nome: "Juízes",
    autor: "Samuel",
    data: "c. 1050 a.C.",
    tema: "Ciclo de apostasia, opressão, arrependimento e livramento",
    contextoHistorico: "Sem liderança central, Israel cai repetidamente em idolatria. Deus levanta juízes para libertá-los. Um dos períodos mais sombrios de Israel.",
    esboco: ["1. Decadência inicial (1-3)","2. Débora e Baraque (4-5)","3. Gideão e Abimeleque (6-9)","4. Jefté (10-12)","5. Sansão (13-16)","6. Anarquia final (17-21)"],
    temasTeologicos: ["Idolatria e apostasia","Arrependimento","Graça libertadora","Consequências do pecado","Necessidade de um rei"],
    capitulos: 21, testamento: "AT", genero: "História",
    versiculoChave: ["Juízes 2:16","Juízes 21:25"],
    cristologia: "O Juiz perfeito e libertador que quebra o ciclo de pecado."
  },
  "Rute": {
    nome: "Rute",
    autor: "Samuel",
    data: "c. 1000 a.C.",
    tema: "O amor redentor e a providência divina",
    contextoHistorico: "No tempo dos juízes, uma família de Belém emigra para Moabe. A tragédia é revertida pela lealdade de Rute e a redenção de Boaz.",
    esboco: ["1. Tragédia e lealdade (1)","2. Colheita e encontro com Boaz (2)","3. Pedido de redenção (3)","4. Casamento e linhagem (4)"],
    temasTeologicos: ["Redenção (goel)","Providência divina","Lealdade (chesed)","Inclusão de gentios","Linhagem messiânica"],
    capitulos: 4, testamento: "AT", genero: "História",
    versiculoChave: ["Rute 1:16-17","Rute 4:14"],
    cristologia: "Boaz como o parente-redentor (goel) que prefigura Cristo. Rute na genealogia de Jesus."
  },
  "1 Samuel": {
    nome: "1 Samuel",
    autor: "Samuel, Gade e Natã",
    data: "c. 930 a.C.",
    tema: "A transição de Israel para a monarquia",
    contextoHistorico: "Israel passa de um período de juízes para a monarquia. Samuel, o último juiz, unge Saul e depois Davi como reis.",
    esboco: ["1. Nascimento e chamado de Samuel (1-3)","2. A arca capturada (4-7)","3. Saul ungido rei (8-12)","4. Queda de Saul (13-15)","5. Ascensão de Davi (16-31)"],
    temasTeologicos: ["Liderança segundo Deus","Obediência vs ritual","Coração vs aparência","Soberania divina","Unção"],
    capitulos: 31, testamento: "AT", genero: "História",
    versiculoChave: ["1 Samuel 15:22","1 Samuel 16:7"],
    cristologia: "Davi como o rei ungido que prefigura Cristo, o Filho de Davi."
  },
  "2 Samuel": {
    nome: "2 Samuel",
    autor: "Gade e Natã",
    data: "c. 930 a.C.",
    tema: "O reinado de Davi: triunfos, pecados e aliança",
    contextoHistorico: "Davi estabelece Jerusalém como capital. Deus faz a aliança davídica prometendo um reino eterno. O pecado com Bate-Seba traz graves consequências.",
    esboco: ["1. Triunfo e unificação (1-6)","2. Aliança davídica (7)","3. Expansão do reino (8-10)","4. Pecado e arrependimento (11-12)","5. Rebelião de Absalão (13-20)","6. Últimos atos (21-24)"],
    temasTeologicos: ["Aliança davídica","Pecado e arrependimento","Consequências do pecado","Misericórdia divina"],
    capitulos: 24, testamento: "AT", genero: "História",
    versiculoChave: ["2 Samuel 7:16","2 Samuel 12:13"],
    cristologia: "O Filho de Davi cujo reino é eterno (7:13-16)."
  },
  "1 Reis": {
    nome: "1 Reis",
    autor: "Jeremias",
    data: "c. 560 a.C.",
    tema: "O reino dividido e o declínio de Israel",
    contextoHistorico: "Salomão constrói o Templo mas cai na idolatria. O reino se divide após sua morte. Elias confronta Acabe e Jezabel no norte.",
    esboco: ["1. Reinado de Salomão (1-11)","2. Divisão do reino (12)","3. Reinos divididos - primeiros reis (13-16)","4. Elias e a crise em Israel (17-22)"],
    temasTeologicos: ["Sabedoria e idolatria","Templo","Profecia","Fidelidade a Deus","Julgamento"],
    capitulos: 22, testamento: "AT", genero: "História",
    versiculoChave: ["1 Reis 3:9","1 Reis 18:21"],
    cristologia: "O maior que Salomão (Mt 12:42). O templo verdadeiro."
  },
  "2 Reis": {
    nome: "2 Reis",
    autor: "Jeremias",
    data: "c. 560 a.C.",
    tema: "O exílio como juízo divino pela infidelidade",
    contextoHistorico: "Eliseu sucede Elias. Israel (norte) cai para a Assíria em 722 a.C. Judá (sul) é levado cativo para a Babilônia em 586 a.C. após repetidas advertências proféticas.",
    esboco: ["1. Eliseu continua Elias (1-8)","2. Dinastia de Jeú (9-10)","3. Queda de Israel - Assíria (11-17)","4. Ezequias e reforma (18-20)","5. Queda de Judá - Babilônia (21-25)"],
    temasTeologicos: ["Juízo divino","Arrependimento","Fidelidade profética","Esperança na restauração"],
    capitulos: 25, testamento: "AT", genero: "História",
    versiculoChave: ["2 Reis 17:7","2 Reis 25:21"],
    cristologia: "O Rei fiel que nunca abandonará seu povo."
  },
  "1 Crônicas": {
    nome: "1 Crônicas",
    autor: "Esdras",
    data: "c. 430 a.C.",
    tema: "A história de Israel vista do trono de Deus - Davi como centro",
    contextoHistorico: "Escrito para os exilados retornados, recontando a história de Israel com foco no templo, no sacerdócio e na aliança davídica para restaurar a esperança messiânica.",
    esboco: ["1. Genealogias de Adão a Davi (1-9)","2. Reinado de Davi (10-21)","3. Preparação para o Templo (22-29)"],
    temasTeologicos: ["Aliança davídica","Templo e adoração","Esperança messiânica","Fidelidade de Deus"],
    capitulos: 29, testamento: "AT", genero: "História",
    versiculoChave: ["1 Crônicas 16:29","1 Crônicas 29:11"],
    cristologia: "O Filho de Davi que construirá o templo eterno."
  },
  "2 Crônicas": {
    nome: "2 Crônicas",
    autor: "Esdras",
    data: "c. 430 a.C.",
    tema: "O templo, o culto e o reavivamento em Judá",
    contextoHistorico: "Foco no reino de Judá (sul). Destaque nos reis que buscaram reavivamento. O templo como centro da adoração e identidade nacional.",
    esboco: ["1. Salomão e o Templo (1-9)","2. Reis de Judá - altos e baixos (10-28)","3. Ezequias e reavivamento (29-32)","4. Queda e exílio (33-36)"],
    temasTeologicos: ["Reavivamento","Arrependimento","Templo","Bênção pela obediência"],
    capitulos: 36, testamento: "AT", genero: "História",
    versiculoChave: ["2 Crônicas 7:14","2 Crônicas 36:23"],
    cristologia: "A glória de Deus que enche o templo."
  },
  "Esdras": {
    nome: "Esdras",
    autor: "Esdras",
    data: "c. 450 a.C.",
    tema: "Restauração do templo e da lei em Jerusalém",
    contextoHistorico: "Após 70 anos de exílio, os judeus retornam à terra sob Zorobabel para reconstruir o templo. Esdras lidera um reavivamento baseado na Palavra de Deus.",
    esboco: ["1. Retorno e reconstrução do templo (1-6)","2. Esdras e a restauração espiritual (7-10)"],
    temasTeologicos: ["Restauração","Primazia da Palavra","Reavivamento","Fidelidade de Deus"],
    capitulos: 10, testamento: "AT", genero: "História",
    versiculoChave: ["Esdras 7:10","Esdras 9:6"],
    cristologia: "O verdadeiro restaurador do templo e da adoração."
  },
  "Neemias": {
    nome: "Neemias",
    autor: "Neemias",
    data: "c. 430 a.C.",
    tema: "Reconstrução dos muros e reforma do povo",
    contextoHistorico: "Neemias, copeiro do rei persa, lidera a reconstrução dos muros de Jerusalém em 52 dias. Segue-se um grande reavivamento sob a liderança de Esdras.",
    esboco: ["1. Reconstrução dos muros (1-7)","2. Reavivamento pela Palavra (8-10)","3. Reformas de Neemias (11-13)"],
    temasTeologicos: ["Liderança serva","Oração","Oposição","Reavivamento","Reforma"],
    capitulos: 13, testamento: "AT", genero: "História",
    versiculoChave: ["Neemias 1:4","Neemias 8:10"],
    cristologia: "O edificador da Jerusalém celestial."
  },
  "Ester": {
    nome: "Ester",
    autor: "Mardoqueu",
    data: "c. 460 a.C.",
    tema: "A providência divina preservando o povo da aliança",
    contextoHistorico: "Ester, uma judia, torna-se rainha da Pérsia. O plano de Hamã para exterminar os judeus é frustrado pela coragem de Ester e pela providência de Deus, que nunca é mencionado mas age soberanamente.",
    esboco: ["1. Ester torna-se rainha (1-2)","2. Conspiração de Hamã (3-4)","3. Coragem de Ester (5-7)","4. Triunfo dos judeus - Purim (8-10)"],
    temasTeologicos: ["Providência divina","Coragem","Identidade do povo de Deus","Jejum e oração"],
    capitulos: 10, testamento: "AT", genero: "História",
    versiculoChave: ["Ester 4:14","Ester 8:17"],
    cristologia: "O intercessor que arrisca a vida para salvar seu povo."
  },
  "Jó": {
    nome: "Jó",
    autor: "Desconhecido (Jó?)",
    data: "c. 2000-1500 a.C.",
    tema: "O problema do sofrimento do justo e a soberania de Deus",
    contextoHistorico: "Jó, um homem justo e próspero, perde tudo. O livro explora profundamente o problema do sofrimento, a inadequação da teologia retributiva simplista e a majestade de Deus.",
    esboco: ["1. Prólogo - a prova de Jó (1-2)","2. Diálogos - Jó e seus amigos (3-31)","3. Discursos de Eliú (32-37)","4. Deus responde do redemoinho (38-41)","5. Restauração de Jó (42)"],
    temasTeologicos: ["Sofrimento","Soberania divina","Sabedoria","Esperança na ressurreição","Teodiceia"],
    capitulos: 42, testamento: "AT", genero: "Poesia",
    versiculoChave: ["Jó 1:21","Jó 19:25-27","Jó 42:5"],
    cristologia: "O Redentor vivo (19:25). O mediador entre Deus e os homens."
  },
  "Salmos": {
    nome: "Salmos",
    autor: "Davi, Asafe, Corá, Salomão, Moisés",
    data: "1410-430 a.C.",
    tema: "O livro de oração e louvor do povo de Deus",
    contextoHistorico: "O hinário de Israel. 150 salmos que cobrem toda a gama de emoções humanas: louvor, gratidão, lamento, confissão, sabedoria e esperança messiânica.",
    esboco: ["1. Livro I - Salmos 1-41 (Davi)","2. Livro II - Salmos 42-72 (Davi/Corá)","3. Livro III - Salmos 73-89 (Asafe)","4. Livro IV - Salmos 90-106 (Moisés e outros)","5. Livro V - Salmos 107-150 (Davi e peregrinos)"],
    temasTeologicos: ["Louvor e adoração","Lamento e confiança","Realeza divina","Messiânico","Sabedoria e Torá"],
    capitulos: 150, testamento: "AT", genero: "Poesia",
    versiculoChave: ["Salmo 1:1-3","Salmo 23:1","Salmo 119:105","Salmo 150:6"],
    cristologia: "O Rei messiânico (2; 110). O Bom Pastor (23). O Servo sofredor (22). O Filho exaltado (110)."
  },
  "Provérbios": {
    nome: "Provérbios",
    autor: "Salomão, Agur, Lemuel",
    data: "c. 950-700 a.C.",
    tema: "Sabedoria prática para viver no temor do Senhor",
    contextoHistorico: "Salomão, o homem mais sábio de sua época, compilou ditados de sabedoria para ensinar os jovens. A sabedoria bíblica começa com o temor do Senhor.",
    esboco: ["1. Propósito e valor da sabedoria (1-9)","2. Provérbios de Salomão (10-24)","3. Provérbios de Salomão compilados por Ezequias (25-29)","4. Palavras de Agur (30)","5. Palavras de Lemuel - Mulher Virtuosa (31)"],
    temasTeologicos: ["Temor do Senhor","Sabedoria prática","Disciplina","Língua","Justiça e integridade"],
    capitulos: 31, testamento: "AT", genero: "Poesia",
    versiculoChave: ["Provérbios 1:7","Provérbios 3:5-6","Provérbios 9:10","Provérbios 22:6"],
    cristologia: "A Sabedoria personificada (8:22-31). O maior que Salomão."
  },
  "Eclesiastes": {
    nome: "Eclesiastes",
    autor: "Salomão",
    data: "c. 935 a.C.",
    tema: "O sentido da vida debaixo do sol sem Deus",
    contextoHistorico: "Salomão, no fim da vida, reflete filosoficamente sobre a vaidade de buscar sentido em prazeres, riquezas e sabedoria humana. O temor de Deus é a conclusão.",
    esboco: ["1. Tudo é vaidade (1-2)","2. Tempo e eternidade (3)","3. Observações sobre a vida (4-8)","4. Aproveitar a vida com sabedoria (9-11)","5. Conclusão: Teme a Deus (12)"],
    temasTeologicos: ["Vaidade das coisas terrenas","Temor de Deus","Eternidade no coração","Contentamento","Juízo final"],
    capitulos: 12, testamento: "AT", genero: "Poesia",
    versiculoChave: ["Eclesiastes 1:2","Eclesiastes 3:11","Eclesiastes 12:13-14"],
    cristologia: "O sentido da vida que transcende debaixo do sol."
  },
  "Cânticos": {
    nome: "Cânticos",
    autor: "Salomão",
    data: "c. 960 a.C.",
    tema: "O amor conjugal como reflexo do amor divino",
    contextoHistorico: "Um poema de amor entre Salomão e a Sulamita. Celebra a beleza do amor físico no casamento e prefigura o amor de Cristo pela igreja.",
    esboco: ["1. Cortejo e desejo (1-2)","2. Busca e encontro (3-4)","3. Consumação e conflito (5-6)","4. Maturidade do amor (7-8)"],
    temasTeologicos: ["Amor conjugal","Intimidade","Fidelidade","Beleza do amor","Alegria"],
    capitulos: 8, testamento: "AT", genero: "Poesia",
    versiculoChave: ["Cânticos 2:4","Cânticos 8:6-7"],
    cristologia: "O Noivo celestial e sua noiva, a Igreja."
  },
  "Isaías": {
    nome: "Isaías",
    autor: "Isaías",
    data: "c. 740-680 a.C.",
    tema: "O Santo de Israel como Salvador e Redentor",
    contextoHistorico: "Isaías profetizou durante os reinados de Uzias, Jotão, Acaz e Ezequias. Advertiu Judá e as nações do juízo vindouro e proclamou a esperança messiânica.",
    esboco: ["1. Juízo e esperança (1-12)","2. Oráculos contra as nações (13-23)","3. Apocalipse de Isaías (24-27)","4. Livro da confiança (28-39)","5. Livro da consolação (40-66)"],
    temasTeologicos: ["Santidade de Deus","Messiânico (Servo Sofredor)","Juízo e restauração","Consolação","Novos céus e nova terra"],
    capitulos: 66, testamento: "AT", genero: "Profecia Maior",
    versiculoChave: ["Isaías 6:3","Isaías 7:14","Isaías 9:6","Isaías 53:5-6","Isaías 55:11"],
    cristologia: "O Emanuel (7:14). O Menino que nos nasceu (9:6). O Servo Sofredor (52:13-53:12). O Ungido que proclama boas novas (61:1-2)."
  },
  "Jeremias": {
    nome: "Jeremias",
    autor: "Jeremias",
    data: "c. 626-586 a.C.",
    tema: "Juízo iminente, arrependimento urgente e nova aliança",
    contextoHistorico: "Jeremias, o profeta chorão, advertiu Judá por 40 anos sobre a destruição vindoura pela Babilônia. Presenciou a queda de Jerusalém em 586 a.C.",
    esboco: ["1. Chamado e advertências (1-20)","2. Profecias e perseguições (21-29)","3. Nova aliança e esperança (30-33)","4. Queda de Jerusalém (34-45)","5. Oráculos às nações (46-52)"],
    temasTeologicos: ["Juízo divino","Arrependimento","Nova aliança","Sofrimento do profeta","Soberania sobre nações"],
    capitulos: 52, testamento: "AT", genero: "Profecia Maior",
    versiculoChave: ["Jeremias 1:5","Jeremias 29:11","Jeremias 31:31-34"],
    cristologia: "O Renovo justo de Davi (23:5-6). O mediador da nova aliança (31:31-34)."
  },
  "Lamentações": {
    nome: "Lamentações",
    autor: "Jeremias",
    data: "586 a.C.",
    tema: "O lamento por Jerusalém destruída e a esperança em Deus",
    contextoHistorico: "Cinco poemas acrósticos de luto pela destruição de Jerusalém em 586 a.C. Apesar da devastação, há esperança nas misericórdias do Senhor.",
    esboco: ["1. A cidade desolada (1)","2. A ira de Deus (2)","3. Esperança na misericórdia (3)","4. O cerco e sofrimento (4)","5. Oração por restauração (5)"],
    temasTeologicos: ["Lamento","Juízo divino","Misericórdia","Esperança","Sofrimento coletivo"],
    capitulos: 5, testamento: "AT", genero: "Profecia Maior",
    versiculoChave: ["Lamentações 3:22-23","Lamentações 3:25"],
    cristologia: "O homem de dores que lamenta sobre Jerusalém (Mt 23:37)."
  },
  "Ezequiel": {
    nome: "Ezequiel",
    autor: "Ezequiel",
    data: "c. 593-570 a.C.",
    tema: "A glória de Deus que parte e retorna - visões de restauração",
    contextoHistorico: "Ezequiel profetizou entre os exilados na Babilônia. Suas visões da glória de Deus e do templo futuro são as mais elaboradas do AT.",
    esboco: ["1. Chamado e glória de Deus (1-3)","2. Juízo sobre Jerusalém (4-24)","3. Juízo sobre as nações (25-32)","4. Restauração de Israel (33-39)","5. Visão do templo futuro (40-48)"],
    temasTeologicos: ["Glória de Deus","Responsabilidade individual","Novo coração","Espírito Santo","Templo"],
    capitulos: 48, testamento: "AT", genero: "Profecia Maior",
    versiculoChave: ["Ezequiel 11:19-20","Ezequiel 36:26-27","Ezequiel 37:27"],
    cristologia: "O Bom Pastor (34). O renovo que Deus planta (17:22-24). O rio de vida do templo (47)."
  },
  "Daniel": {
    nome: "Daniel",
    autor: "Daniel",
    data: "c. 605-536 a.C.",
    tema: "A soberania de Deus sobre as nações e a história",
    contextoHistorico: "Daniel, exilado na Babilônia ainda jovem, serve como conselheiro em três impérios. Suas visões apocalípticas revelam o plano de Deus para as eras.",
    esboco: ["1. Fidelidade na Babilônia (1-6)","2. Visões proféticas (7-12)"],
    temasTeologicos: ["Soberania de Deus","Fidelidade","Profecia apocalíptica","Reino eterno","Anjos"],
    capitulos: 12, testamento: "AT", genero: "Profecia Maior",
    versiculoChave: ["Daniel 2:21","Daniel 7:13-14","Daniel 9:24-27"],
    cristologia: "O Filho do Homem que recebe o reino eterno (7:13-14). O Ungido que virá (9:25-26)."
  },
  "Oséias": {
    nome: "Oséias",
    autor: "Oséias",
    data: "c. 755-715 a.C.",
    tema: "O amor fiel de Deus pelo seu povo infiel",
    contextoHistorico: "Oséias recebe a ordem de casar com Gômer, uma prostituta, como símbolo do amor persistente de Deus por Israel, que comete adultério espiritual com ídolos.",
    esboco: ["1. O casamento simbólico (1-3)","2. A infidelidade de Israel (4-10)","3. O amor restaurador de Deus (11-14)"],
    temasTeologicos: ["Amor incondicional (chesed)","Adultério espiritual","Arrependimento","Conhecimento de Deus"],
    capitulos: 14, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Oséias 6:6","Oséias 11:8-9"],
    cristologia: "O esposo fiel que redime sua noiva infiel."
  },
  "Joel": {
    nome: "Joel",
    autor: "Joel",
    data: "c. 835 a.C.",
    tema: "O Dia do Senhor - juízo e derramamento do Espírito",
    contextoHistorico: "Uma praga de gafanhotos devastadora motiva o chamado ao arrependimento. Joel profetiza sobre o Dia do Senhor e o derramamento do Espírito.",
    esboco: ["1. Praga de gafanhotos - chamado ao arrependimento (1)","2. O Dia do Senhor (2)","3. Juízo das nações e bênção de Sião (3)"],
    temasTeologicos: ["Dia do Senhor","Arrependimento","Derramamento do Espírito","Restauração"],
    capitulos: 3, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Joel 2:28-32","Joel 2:12-13"],
    cristologia: "Aquele que derrama o Espírito no Pentecostes (At 2:16-21)."
  },
  "Amós": {
    nome: "Amós",
    autor: "Amós",
    data: "c. 760 a.C.",
    tema: "A justiça social como expressão da verdadeira religião",
    contextoHistorico: "Amós, um pastor de Tecoa, é chamado para profetizar contra Israel durante sua prosperidade. Denuncia a injustiça social e o formalismo religioso.",
    esboco: ["1. Juízo das nações vizinhas (1-2)","2. Mensagens contra Israel (3-6)","3. Cinco visões de juízo (7-9)","4. Promessa de restauração (9:11-15)"],
    temasTeologicos: ["Justiça social","Juízo divino","Hipocrisia religiosa","Dia do Senhor","Restauração"],
    capitulos: 9, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Amós 3:7","Amós 5:24"],
    cristologia: "O restaurador do tabernáculo caído de Davi (9:11-12)."
  },
  "Obadias": {
    nome: "Obadias",
    autor: "Obadias",
    data: "c. 586 a.C.",
    tema: "O juízo de Deus sobre Edom e a restauração de Israel",
    contextoHistorico: "O livro mais curto do AT. Condena Edom por trair Judá durante a invasão babilônica e promete o reino do Senhor.",
    esboco: ["1. Juízo sobre Edom (1-14)","2. O Dia do Senhor sobre as nações (15-21)"],
    temasTeologicos: ["Orgulho e queda","Justiça retributiva","Dia do Senhor","Restauração"],
    capitulos: 1, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Obadias 1:15","Obadias 1:21"],
    cristologia: "O Rei que julga e restaura."
  },
  "Jonas": {
    nome: "Jonas",
    autor: "Jonas",
    data: "c. 760 a.C.",
    tema: "A misericórdia de Deus para com as nações arrependidas",
    contextoHistorico: "Jonas foge da ordem de pregar em Nínive (capital da Assíria). Um grande peixe o engole e ele finalmente obedece. Sua relutância revela o amor universal de Deus.",
    esboco: ["1. Desobediência e o peixe (1-2)","2. Pregação e arrependimento (3)","3. A lição da misericórdia (4)"],
    temasTeologicos: ["Misericórdia universal","Arrependimento","Eleição para missão","Compaixão vs nacionalismo"],
    capitulos: 4, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Jonas 2:9","Jonas 4:2"],
    cristologia: "O sinal de Jonas - três dias no ventre da terra (Mt 12:40)."
  },
  "Miqueias": {
    nome: "Miqueias",
    autor: "Miqueias",
    data: "c. 735-700 a.C.",
    tema: "O julgamento dos opressores e a esperança do Messias",
    contextoHistorico: "Miqueias profetizou no mesmo período de Isaías. Denunciou a corrupção em Judá e anunciou Belém como o local do nascimento do Messias.",
    esboco: ["1. Juízo sobre Samaria e Judá (1-3)","2. Reinado messiânico (4)","3. Nascimento do Messias e restauração (5)","4. Controvérsia e esperança (6-7)"],
    temasTeologicos: ["Justiça","Misericórdia e humildade","Messias de Belém","Esperança"],
    capitulos: 7, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Miqueias 5:2","Miqueias 6:8"],
    cristologia: "Nascerá em Belém, suas origens são eternas (5:2)."
  },
  "Naum": {
    nome: "Naum",
    autor: "Naum",
    data: "c. 663-612 a.C.",
    tema: "A queda de Nínive e a justiça do Senhor",
    contextoHistorico: "Nínive, que se arrependeu com Jonas, voltou à crueldade. Naum profetiza sua destruição, ocorrida em 612 a.C. pelos medos e babilônios.",
    esboco: ["1. A majestade de Deus como juiz (1)","2. A queda de Nínive (2)","3. A causa do juízo (3)"],
    temasTeologicos: ["Justiça divina","Juízo histórico","Bondade e severidade de Deus"],
    capitulos: 3, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Naum 1:7","Naum 1:3"],
    cristologia: "O refúgio seguro no dia da angústia."
  },
  "Habacuque": {
    nome: "Habacuque",
    autor: "Habacuque",
    data: "c. 609-598 a.C.",
    tema: "O justo viverá pela fé - confiança na justiça divina",
    contextoHistorico: "Habacuque questiona por que Deus usa os babilônios (piores que Judá) para julgar. Deus revela que o justo vive pela fé e que a justiça final virá.",
    esboco: ["1. O profeta questiona Deus (1)","2. Deus responde (2)","3. O salmo de confiança (3)"],
    temasTeologicos: ["Teodiceia","Justificação pela fé","Soberania de Deus","Alegria na adversidade"],
    capitulos: 3, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Habacuque 2:4","Habacuque 3:17-19"],
    cristologia: "Aquele em quem o justo vive pela fé."
  },
  "Sofonias": {
    nome: "Sofonias",
    autor: "Sofonias",
    data: "c. 630 a.C.",
    tema: "O Dia do Senhor e a esperança do remanescente",
    contextoHistorico: "Sofonias, descendente de Ezequias, profetizou durante a reforma de Josias. Anunciou o juízo universal próximo e a futura alegria de Sião.",
    esboco: ["1. Juízo sobre Judá (1)","2. Juízo das nações (2)","3. Restauração e alegria (3)"],
    temasTeologicos: ["Dia do Senhor","Remanescente fiel","Alegria de Deus","Restauração"],
    capitulos: 3, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Sofonias 3:17","Sofonias 1:14"],
    cristologia: "O Rei de Israel que se alegra com seu povo."
  },
  "Ageu": {
    nome: "Ageu",
    autor: "Ageu",
    data: "520 a.C.",
    tema: "Prioridade da reconstrução do templo sobre interesses pessoais",
    contextoHistorico: "Após o retorno do exílio, a reconstrução do templo parou por 16 anos. Ageu exorta o povo a reassumir a obra e promete bênçãos.",
    esboco: ["1. Chamado à reconstrução (1)","2. A glória do novo templo (2)"],
    temasTeologicos: ["Prioridades espirituais","Obediência","Bênção","Esperança escatológica"],
    capitulos: 2, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Ageu 1:7-8","Ageu 2:9"],
    cristologia: "O Desejado de todas as nações que encherá o templo de glória (2:7)."
  },
  "Zacarias": {
    nome: "Zacarias",
    autor: "Zacarias",
    data: "c. 520-480 a.C.",
    tema: "Visões messiânicas - o Renovo, o Pastor e o Rei que vem",
    contextoHistorico: "Contemporâneo de Ageu, Zacarias recebe oito visões noturnas encorajando a reconstrução. Profecias messiânicas notáveis sobre a entrada triunfal e o pastor ferido.",
    esboco: ["1. Oito visões noturnas (1-6)","2. Jejum e justiça (7-8)","3. O Rei que vem (9-14)"],
    temasTeologicos: ["Messiânico","Jerusalém restaurada","Rei humilde","Dia do Senhor"],
    capitulos: 14, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Zacarias 4:6","Zacarias 9:9","Zacarias 12:10"],
    cristologia: "O Rei humilde entrando em Jerusalém sobre um jumento (9:9). O pastor ferido (13:7). As 30 moedas de prata (11:12-13)."
  },
  "Malaquias": {
    nome: "Malaquias",
    autor: "Malaquias",
    data: "c. 430 a.C.",
    tema: "Último apelo antes do silêncio profético - o mensageiro virá",
    contextoHistorico: "O último livro do AT. Israel caiu em apatia espiritual. Malaquias confronta o formalismo e anuncia que o mensageiro (João Batista) preparará o caminho para o Senhor.",
    esboco: ["1. Amor eletivo de Deus (1)","2. Sacerdócio corrupto (2)","3. Dízimos e fidelidade (3)","4. O Dia do Senhor (4)"],
    temasTeologicos: ["Eleição","Fidelidade nos dízimos","Juízo e purificação","Mensageiro da aliança"],
    capitulos: 4, testamento: "AT", genero: "Profecia Menor",
    versiculoChave: ["Malaquias 3:6","Malaquias 3:10","Malaquias 4:2"],
    cristologia: "O Sol da Justiça que traz cura em suas asas (4:2)."
  },
  // NOVO TESTAMENTO
  "Mateus": {
    nome: "Mateus",
    autor: "Mateus (Levi)",
    data: "c. 55-65 d.C.",
    tema: "Jesus, o Messias prometido e Rei de Israel",
    contextoHistorico: "Escrito para judeus, demonstra que Jesus cumpre as profecias messiânicas do AT. Mateus cita o AT mais de 60 vezes. Apresenta o Reino dos Céus e a igreja.",
    esboco: ["1. Nascimento e preparação (1-4)","2. Sermão do Monte (5-7)","3. Milagres e ensino (8-12)","4. Parábolas do Reino (13)","5. Igreja e discipulado (14-20)","6. Semana da Paixão (21-27)","7. Ressurreição e Grande Comissão (28)"],
    temasTeologicos: ["Reino dos Céus","Cumprimento profético","Justiça do Reino","Igreja","Discipulado"],
    capitulos: 28, testamento: "NT", genero: "Evangelho",
    versiculoChave: ["Mateus 5:17","Mateus 16:18","Mateus 28:19-20"],
    cristologia: "O Messias prometido, Filho de Davi, Emanuel. O Rei que ensina com autoridade e entrega sua vida em resgate."
  },
  "Marcos": {
    nome: "Marcos",
    autor: "João Marcos",
    data: "c. 50-60 d.C.",
    tema: "Jesus, o Servo de Deus em ação",
    contextoHistorico: "O evangelho mais curto e dinâmico, escrito para romanos. Marcos foca nas ações de Jesus: milagres, expulsões de demônios e o sacrifício do Servo.",
    esboco: ["1. Preparação do Servo (1)","2. Ministério na Galileia (2-8)","3. Caminho para Jerusalém (9-10)","4. Paixão e ressurreição (11-16)"],
    temasTeologicos: ["Serviço e sacrifício","Poder sobre demônios","Discipulado","Reino de Deus","Segredo messiânico"],
    capitulos: 16, testamento: "NT", genero: "Evangelho",
    versiculoChave: ["Marcos 10:45","Marcos 16:15"],
    cristologia: "O Servo Sofredor que não veio para ser servido mas para servir e dar sua vida em resgate."
  },
  "Lucas": {
    nome: "Lucas",
    autor: "Lucas, o médico",
    data: "c. 58-63 d.C.",
    tema: "Jesus, o Salvador perfeito de toda a humanidade",
    contextoHistorico: "Escrito para Teófilo (e gregos), enfatiza a compaixão de Jesus pelos marginalizados: mulheres, samaritanos, pobres e pecadores. É o evangelho mais histórico e literário.",
    esboco: ["1. Nascimento e infância (1-2)","2. Início do ministério (3-4)","3. Ministério na Galileia (5-9)","4. Grande seção central (9-19)","5. Paixão e ressurreição (20-24)"],
    temasTeologicos: ["Salvação universal","Oração","Espírito Santo","Compaixão pelos marginalizados","Alegria"],
    capitulos: 24, testamento: "NT", genero: "Evangelho",
    versiculoChave: ["Lucas 1:1-4","Lucas 19:10"],
    cristologia: "O Filho do Homem que veio buscar e salvar o perdido. O Salvador compassivo de todos."
  },
  "João": {
    nome: "João",
    autor: "João, o apóstolo",
    data: "c. 85-95 d.C.",
    tema: "Jesus, o Verbo encarnado, Filho de Deus",
    contextoHistorico: "O evangelho teológico escrito pelo apóstolo do amor. João seleciona 7 sinais e 7 discursos 'EU SOU' para provar que Jesus é o Cristo, Filho de Deus, para que crendo tenham vida.",
    esboco: ["1. Prólogo: O Verbo (1:1-18)","2. Livro dos Sinais (1:19-12:50)","3. Livro da Glória (13-20)","4. Epílogo: Pedro e João (21)"],
    temasTeologicos: ["Divindade de Cristo (EU SOU)","Fé salvadora","Vida eterna","Amor (ágape)","Espírito Santo Paráclito"],
    capitulos: 21, testamento: "NT", genero: "Evangelho",
    versiculoChave: ["João 1:1","João 3:16","João 20:31"],
    cristologia: "O Verbo eterno que se fez carne. O EU SOU (8:58). O Cordeiro de Deus que tira o pecado do mundo. O caminho, a verdade e a vida."
  },
  "Atos": {
    nome: "Atos",
    autor: "Lucas",
    data: "c. 62 d.C.",
    tema: "A expansão do evangelho pelo poder do Espírito Santo",
    contextoHistorico: "Continuação do Evangelho de Lucas. Narra o nascimento e expansão da igreja primitiva de Jerusalém a Roma através do poder do Espírito Santo.",
    esboco: ["1. Pentecostes e Jerusalém (1-7)","2. Judeia e Samaria (8-12)","3. Primeira viagem missionária (13-14)","4. Concílio de Jerusalém (15)","5. Segunda viagem (16-18)","6. Terceira viagem e prisão de Paulo (19-28)"],
    temasTeologicos: ["Espírito Santo","Evangelização mundial","Perseguição e martírio","Igreja primitiva","Conversões"],
    capitulos: 28, testamento: "NT", genero: "História",
    versiculoChave: ["Atos 1:8","Atos 2:42","Atos 4:12"],
    cristologia: "O Senhor exaltado que edifica sua igreja. O nome que salva."
  },
  "Romanos": {
    nome: "Romanos",
    autor: "Paulo",
    data: "c. 57 d.C.",
    tema: "O evangelho da justiça de Deus pela fé",
    contextoHistorico: "A epístola mais teológica de Paulo. Apresenta sistematicamente o evangelho: condenação do pecado, justificação pela fé, santificação pelo Espírito e eleição soberana de Deus.",
    esboco: ["1. Condenação: necessidade do evangelho (1:18-3:20)","2. Justificação: provisão pela fé (3:21-5:21)","3. Santificação: poder sobre o pecado (6-8)","4. Israel: passado, presente e futuro (9-11)","5. Aplicação prática (12-16)"],
    temasTeologicos: ["Justificação pela fé","Graça","Pecado e lei","Eleição","Vida no Espírito"],
    capitulos: 16, testamento: "NT", genero: "Epístola",
    versiculoChave: ["Romanos 1:16-17","Romanos 3:23","Romanos 6:23","Romanos 8:28","Romanos 12:1-2"],
    cristologia: "O justificador que declara o ímpio justo. O novo Adão. O fim da lei para justiça."
  },
  "1 Coríntios": {
    nome: "1 Coríntios",
    autor: "Paulo",
    data: "c. 55 d.C.",
    tema: "Problemas na igreja carnal e o evangelho da cruz",
    contextoHistorico: "Paulo corrige divisões, imoralidade, idolatria e abusos espirituais na igreja de Corinto, uma cidade portuária cosmopolita e pagã. Tudo é resolvido pelo evangelho da cruz.",
    esboco: ["1. Divisões na igreja (1-4)","2. Imoralidade e litígios (5-6)","3. Casamento e liberdade cristã (7)","4. Carnes sacrificadas a ídolos (8-10)","5. Ordem no culto (11-14)","6. Ressurreição (15)","7. Coleta para os santos (16)"],
    temasTeologicos: ["Unidade na igreja","Santidade prática","Dons espirituais","Amor (ágape)","Ressurreição corporal"],
    capitulos: 16, testamento: "NT", genero: "Epístola",
    versiculoChave: ["1 Coríntios 1:18","1 Coríntios 10:13","1 Coríntios 13:13","1 Coríntios 15:58"],
    cristologia: "A sabedoria e o poder de Deus. O Cordeiro pascal. O último Adão."
  },
  "2 Coríntios": {
    nome: "2 Coríntios",
    autor: "Paulo",
    data: "c. 56 d.C.",
    tema: "O ministério apostólico na fraqueza humana",
    contextoHistorico: "A epístola mais pessoal de Paulo. Defende seu apostolado contra falsos mestres, revela seu coração pastoral e expõe sua teologia do sofrimento e da graça.",
    esboco: ["1. Conforto na tribulação (1-7)","2. Graça na oferta (8-9)","3. Defesa da autoridade apostólica (10-13)"],
    temasTeologicos: ["Sofrimento e consolação","Nova aliança","Fraqueza e poder","Generosidade","Autoridade apostólica"],
    capitulos: 13, testamento: "NT", genero: "Epístola",
    versiculoChave: ["2 Coríntios 5:17","2 Coríntios 12:9","2 Coríntios 13:14"],
    cristologia: "Aquele que, sendo rico, se fez pobre por nós. O poder de Deus aperfeiçoado na fraqueza."
  },
  "Gálatas": {
    nome: "Gálatas",
    autor: "Paulo",
    data: "c. 48-50 d.C.",
    tema: "A liberdade do evangelho contra o legalismo",
    contextoHistorico: "Paulo combate os judaizantes que exigiam a circuncisão dos gentios. Defende vigorosamente a justificação somente pela fé em Cristo, não pelas obras da lei.",
    esboco: ["1. Defesa do apostolado (1-2)","2. Doutrina da justificação pela fé (3-4)","3. Liberdade cristã e fruto do Espírito (5-6)"],
    temasTeologicos: ["Justificação pela fé","Graça vs Lei","Liberdade cristã","Fruto do Espírito","Filhos de Abraão pela fé"],
    capitulos: 6, testamento: "NT", genero: "Epístola",
    versiculoChave: ["Gálatas 2:20","Gálatas 3:27-28","Gálatas 5:1","Gálatas 5:22-23"],
    cristologia: "O libertador que nos liberta da escravidão da lei. Crucificado com Ele, vivo pela fé."
  },
  "Efésios": {
    nome: "Efésios",
    autor: "Paulo",
    data: "c. 60-62 d.C.",
    tema: "A igreja, corpo de Cristo, e a vida cristã",
    contextoHistorico: "Escrita da prisão, revela o plano eterno de Deus para a igreja: a união de judeus e gentios em um só corpo. A metade final trata da vida cristã e da batalha espiritual.",
    esboco: ["1. Riquezas espirituais em Cristo (1-3)","2. Andar em unidade e santidade (4-5)","3. Batalha espiritual e armadura de Deus (6)"],
    temasTeologicos: ["Igreja como corpo de Cristo","Graça","Unidade","Eleição","Batalha espiritual"],
    capitulos: 6, testamento: "NT", genero: "Epístola",
    versiculoChave: ["Efésios 2:8-9","Efésios 4:5","Efésios 6:12"],
    cristologia: "A cabeça da igreja. O centro da unidade. A pedra angular do templo espiritual."
  },
  "Filipenses": {
    nome: "Filipenses",
    autor: "Paulo",
    data: "c. 60-62 d.C.",
    tema: "A alegria cristã em meio ao sofrimento",
    contextoHistorico: "Carta de gratidão e encorajamento à igreja filipense, a primeira que Paulo fundou na Europa. Contém o sublime hino cristológico (2:5-11).",
    esboco: ["1. Alegria na adversidade (1)","2. Humilhação e exaltação de Cristo (2)","3. O supremo alvo: conhecer Cristo (3)","4. Contentamento em toda situação (4)"],
    temasTeologicos: ["Alegria no sofrimento","Humildade e serviço","Supremacia de conhecer Cristo","Contentamento","Unidade"],
    capitulos: 4, testamento: "NT", genero: "Epístola",
    versiculoChave: ["Filipenses 1:6","Filipenses 2:5-11","Filipenses 3:13-14","Filipenses 4:13"],
    cristologia: "O Deus que se fez servo, humilhou-se até a morte e foi exaltado acima de todo nome."
  },
  "Colossenses": {
    nome: "Colossenses",
    autor: "Paulo",
    data: "c. 60-62 d.C.",
    tema: "A suprema suficiência de Cristo",
    contextoHistorico: "Paulo combate heresias gnósticas que ameaçavam Colossos. Afirma a plena divindade e a absoluta preeminência de Cristo sobre toda a criação e poderes espirituais.",
    esboco: ["1. Supremacia de Cristo (1-2)","2. Vida em Cristo - revestidos do novo homem (3-4)"],
    temasTeologicos: ["Preeminência de Cristo","Plenitude da divindade","Nova vida em Cristo","Relações transformadas"],
    capitulos: 4, testamento: "NT", genero: "Epístola",
    versiculoChave: ["Colossenses 1:15-17","Colossenses 2:9-10","Colossenses 3:1-2"],
    cristologia: "A imagem do Deus invisível. Nele habita corporalmente toda a plenitude da divindade. Tudo foi criado por Ele e para Ele."
  },
  "1 Tessalonicenses": {
    nome: "1 Tessalonicenses",
    autor: "Paulo",
    data: "c. 50-51 d.C.",
    tema: "Esperança na segunda vinda de Cristo",
    contextoHistorico: "A primeira epístola de Paulo. Consola os tessalonicenses sobre o destino dos cristãos que morreram antes do retorno de Cristo e os exorta à santidade.",
    esboco: ["1. Fidelidade sob perseguição (1-3)","2. Santidade e amor fraternal (4)","3. O Dia do Senhor e a esperança (5)"],
    temasTeologicos: ["Segunda vinda de Cristo","Arrebatamento","Santificação","Vigilância","Esperança"],
    capitulos: 5, testamento: "NT", genero: "Epístola",
    versiculoChave: ["1 Tessalonicenses 4:16-17","1 Tessalonicenses 5:16-18","1 Tessalonicenses 5:23"],
    cristologia: "O Senhor que descerá do céu e arrebatará sua igreja para estar para sempre com Ele."
  },
  "2 Tessalonicenses": {
    nome: "2 Tessalonicenses",
    autor: "Paulo",
    data: "c. 51 d.C.",
    tema: "Esclarecimentos sobre o Dia do Senhor",
    contextoHistorico: "Falsos ensinos de que o Dia do Senhor já havia chegado perturbavam a igreja. Paulo esclarece os eventos que precederão a volta de Cristo.",
    esboco: ["1. Perseverança e juízo final (1)","2. O homem da iniquidade (2)","3. Disciplina e trabalho (3)"],
    temasTeologicos: ["Dia do Senhor","Anticristo","Trabalho digno","Perseverança","Juízo"],
    capitulos: 3, testamento: "NT", genero: "Epístola",
    versiculoChave: ["2 Tessalonicenses 2:3","2 Tessalonicenses 3:3","2 Tessalonicenses 3:10"],
    cristologia: "O Senhor que destruirá o iníquo com o sopro de sua boca."
  },
  "1 Timóteo": {
    nome: "1 Timóteo",
    autor: "Paulo",
    data: "c. 63-65 d.C.",
    tema: "Manual pastoral para a igreja de Deus",
    contextoHistorico: "Paulo instrui o jovem pastor Timóteo sobre a administração da igreja em Éfeso, combate às heresias e a qualificação de líderes.",
    esboco: ["1. Perigo das falsas doutrinas (1)","2. Oração e liderança na igreja (2-3)","3. Apostasia e bom ministério (4)","4. Deveres pastorais (5-6)"],
    temasTeologicos: ["Liderança eclesiástica","Sã doutrina","Oração","Contentamento","Perigo das riquezas"],
    capitulos: 6, testamento: "NT", genero: "Epístola",
    versiculoChave: ["1 Timóteo 2:5","1 Timóteo 3:16","1 Timóteo 6:10"],
    cristologia: "O único mediador entre Deus e os homens. O grande mistério da piedade: Deus manifestado em carne."
  },
  "2 Timóteo": {
    nome: "2 Timóteo",
    autor: "Paulo",
    data: "c. 67 d.C.",
    tema: "O legado fiel do apóstolo que parte",
    contextoHistorico: "A última carta de Paulo, escrita da prisão romana antes do martírio. Um testamento pessoal de fé, coragem e perseverança no ministério.",
    esboco: ["1. Não te envergonhes do evangelho (1)","2. Soldado, atleta e lavrador (2)","3. Últimos dias e a Palavra (3)","4. Combati o bom combate (4)"],
    temasTeologicos: ["Perseverança","Inspiração das Escrituras","Pregação da Palavra","Coroa da justiça"],
    capitulos: 4, testamento: "NT", genero: "Epístola",
    versiculoChave: ["2 Timóteo 1:7","2 Timóteo 3:16-17","2 Timóteo 4:7-8"],
    cristologia: "O justo Juiz que dará a coroa da justiça a todos que amam sua vinda."
  },
  "Tito": {
    nome: "Tito",
    autor: "Paulo",
    data: "c. 63-65 d.C.",
    tema: "Ordem na igreja e boas obras",
    contextoHistorico: "Paulo orienta Tito sobre a organização das igrejas em Creta e sobre o caráter cristão prático que decorre da sã doutrina.",
    esboco: ["1. Qualificações dos presbíteros (1)","2. Ensino para cada grupo (2)","3. Regeneração e boas obras (3)"],
    temasTeologicos: ["Liderança","Sã doutrina","Boas obras","Regeneração","Graça"],
    capitulos: 3, testamento: "NT", genero: "Epístola",
    versiculoChave: ["Tito 2:11-12","Tito 3:5"],
    cristologia: "A graça de Deus se manifestou salvadora. O lavar regenerador e renovador do Espírito Santo."
  },
  "Filemom": {
    nome: "Filemom",
    autor: "Paulo",
    data: "c. 60-62 d.C.",
    tema: "O poder transformador do evangelho nas relações sociais",
    contextoHistorico: "A carta mais pessoal de Paulo. Intercede por Onésimo, um escravo fugitivo convertido, pedindo que Filemom o receba como irmão em Cristo.",
    esboco: ["1. Saudação e ação de graças (1-7)","2. Intercessão por Onésimo (8-21)","3. Conclusão (22-25)"],
    temasTeologicos: ["Perdão","Reconciliação","Amor fraternal","Transformação social"],
    capitulos: 1, testamento: "NT", genero: "Epístola",
    versiculoChave: ["Filemom 1:6","Filemom 1:16"],
    cristologia: "O reconciliador que transforma senhor e escravo em irmãos amados."
  },
  "Hebreus": {
    nome: "Hebreus",
    autor: "Desconhecido",
    data: "c. 65-69 d.C.",
    tema: "A superioridade absoluta de Cristo sobre a antiga aliança",
    contextoHistorico: "Exorta judeus cristãos tentados a voltar ao judaísmo, demonstrando que Cristo é superior a anjos, Moisés, Arão e ao sacerdócio levítico. Contém o grande capítulo da fé (11).",
    esboco: ["1. Cristo superior aos profetas e anjos (1-2)","2. Superior a Moisés e Josué (3-4)","3. Sumo Sacerdote superior (5-7)","4. Nova aliança superior (8-10)","5. Fé e perseverança (11-12)","6. Exortações finais (13)"],
    temasTeologicos: ["Superioridade de Cristo","Fé (cap. 11)","Nova aliança","Sacerdócio","Perseverança"],
    capitulos: 13, testamento: "NT", genero: "Epístola",
    versiculoChave: ["Hebreus 1:1-3","Hebreus 4:12","Hebreus 11:1","Hebreus 12:1-2"],
    cristologia: "O resplendor da glória de Deus. O Sumo Sacerdote para sempre. O autor e consumador da fé."
  },
  "Tiago": {
    nome: "Tiago",
    autor: "Tiago, irmão de Jesus",
    data: "c. 45-50 d.C.",
    tema: "A fé verdadeira se manifesta em obras",
    contextoHistorico: "A epístola mais prática do NT. Tiago ensina que a fé genuína se demonstra por obras, domínio da língua e sabedoria celestial. Possivelmente o primeiro livro do NT.",
    esboco: ["1. Provações, sabedoria e tentação (1)","2. Fé e obras (2)","3. Domínio da língua (3)","4. Sabedoria celestial e mundanismo (4)","5. Paciência, oração e restauração (5)"],
    temasTeologicos: ["Fé demonstrada por obras","Sabedoria prática","Língua","Paciência","Oração e cura"],
    capitulos: 5, testamento: "NT", genero: "Epístola",
    versiculoChave: ["Tiago 1:2-4","Tiago 1:22","Tiago 2:17","Tiago 5:16"],
    cristologia: "O Senhor da glória. O Juiz que está à porta."
  },
  "1 Pedro": {
    nome: "1 Pedro",
    autor: "Pedro",
    data: "c. 62-64 d.C.",
    tema: "Esperança e santidade no sofrimento",
    contextoHistorico: "Pedro encoraja cristãos dispersos e perseguidos na Ásia Menor. O sofrimento como cristão é um tema dominante, com Cristo como exemplo supremo.",
    esboco: ["1. Salvação viva e santidade (1)","2. Identidade do povo de Deus (2)","3. Sofrimento e testemunho (3-4)","4. Exortações pastorais (5)"],
    temasTeologicos: ["Sofrimento cristão","Santidade","Esperança viva","Sacerdócio real","Submissão"],
    capitulos: 5, testamento: "NT", genero: "Epístola",
    versiculoChave: ["1 Pedro 1:3-4","1 Pedro 2:9","1 Pedro 3:15","1 Pedro 5:7"],
    cristologia: "O Cordeiro sem defeito. O pastor e bispo das almas. O exemplo do sofrimento injusto."
  },
  "2 Pedro": {
    nome: "2 Pedro",
    autor: "Pedro",
    data: "c. 66-67 d.C.",
    tema: "Crescimento na graça e alerta contra falsos mestres",
    contextoHistorico: "O testamento de Pedro antes da morte. Adverte contra falsos mestres, defende a inspiração das Escrituras e confirma a certeza da segunda vinda de Cristo.",
    esboco: ["1. Crescimento na vida cristã (1)","2. Perigo dos falsos mestres (2)","3. A promessa da vinda de Cristo (3)"],
    temasTeologicos: ["Inspiração das Escrituras","Falsos mestres","Segunda vinda","Juízo","Crescimento na graça"],
    capitulos: 3, testamento: "NT", genero: "Epístola",
    versiculoChave: ["2 Pedro 1:20-21","2 Pedro 3:9","2 Pedro 3:18"],
    cristologia: "O Senhor que não retarda sua promessa. A estrela da manhã que surgirá."
  },
  "1 João": {
    nome: "1 João",
    autor: "João",
    data: "c. 85-95 d.C.",
    tema: "Comunhão com Deus e certeza da salvação",
    contextoHistorico: "João combate o gnosticismo nascente e afirma as marcas do verdadeiro cristão: crença em Cristo encarnado, obediência aos mandamentos e amor aos irmãos.",
    esboco: ["1. Deus é luz (1)","2. Cristo, o propiciatório e o mandamento do amor (2-3)","3. Deus é amor e fé vencedora (4-5)"],
    temasTeologicos: ["Luz e trevas","Amor (ágape)","Verdade","Certeza da salvação","Encarnação"],
    capitulos: 5, testamento: "NT", genero: "Epístola",
    versiculoChave: ["1 João 1:9","1 João 4:8","1 João 5:13"],
    cristologia: "O Verbo da vida manifesto em carne. O propiciatório pelos nossos pecados."
  },
  "2 João": {
    nome: "2 João",
    autor: "João",
    data: "c. 90 d.C.",
    tema: "A verdade e o amor como defesas contra o erro",
    contextoHistorico: "Breve carta a uma igreja local, exortando a permanecer na verdade e a não receber falsos mestres que negam a encarnação de Cristo.",
    esboco: ["1. Caminhar na verdade e no amor (1-6)","2. Rejeitar falsos mestres (7-11)","3. Conclusão (12-13)"],
    temasTeologicos: ["Verdade","Amor","Falsos mestres","Encarnação"],
    capitulos: 1, testamento: "NT", genero: "Epístola",
    versiculoChave: ["2 João 1:6","2 João 1:9"],
    cristologia: "A verdade encarnada que veio em carne."
  },
  "3 João": {
    nome: "3 João",
    autor: "João",
    data: "c. 90 d.C.",
    tema: "Hospitalidade cristã e a ameaça do orgulho na igreja",
    contextoHistorico: "João elogia Gaio pela hospitalidade com os missionários e repreende Diótrefes, que buscava proeminência e rejeitava a autoridade apostólica.",
    esboco: ["1. Elogio a Gaio (1-8)","2. Repreensão a Diótrefes (9-11)","3. Recomendação de Demétrio (12-14)"],
    temasTeologicos: ["Hospitalidade","Humildade","Serviço","Autoridade na igreja"],
    capitulos: 1, testamento: "NT", genero: "Epístola",
    versiculoChave: ["3 João 1:2","3 João 1:11"],
    cristologia: "O exemplo supremo de serviço humilde."
  },
  "Judas": {
    nome: "Judas",
    autor: "Judas, irmão de Jesus",
    data: "c. 65 d.C.",
    tema: "Batalha pela fé contra a apostasia",
    contextoHistorico: "Judas escreve com urgência para alertar contra falsos mestres infiltrados na igreja. Usa exemplos do AT para ilustrar o juízo sobre os apóstatas e exorta à perseverança.",
    esboco: ["1. Chamado à batalha pela fé (1-4)","2. Exemplos de juízo sobre apóstatas (5-16)","3. Como perseverar - edificação, oração, misericórdia (17-25)"],
    temasTeologicos: ["Apostasia","Falsos mestres","Juízo divino","Perseverança dos santos","Doxologia"],
    capitulos: 1, testamento: "NT", genero: "Epístola",
    versiculoChave: ["Judas 1:3","Judas 1:20-21","Judas 1:24-25"],
    cristologia: "O único Deus e Salvador. Aquele que pode guardar-nos de tropeçar."
  },
  "Apocalipse": {
    nome: "Apocalipse",
    autor: "João",
    data: "c. 95 d.C.",
    tema: "A revelação de Jesus Cristo e sua vitória final sobre todo mal",
    contextoHistorico: "João, exilado na ilha de Patmos sob Domiciano, recebe a revelação do Cristo glorificado sobre o fim dos tempos, o juízo final e a nova criação.",
    esboco: ["1. Cartas às 7 igrejas da Ásia (1-3)","2. Visão do trono e cordeiro (4-5)","3. Selos, trombetas e taças (6-16)","4. Queda de Babilônia (17-18)","5. Volta de Cristo e milênio (19-20)","6. Novos céus e nova terra (21-22)"],
    temasTeologicos: ["Soberania de Cristo","Julgamento final","Vitória do Cordeiro","Nova criação","Esperança escatológica"],
    capitulos: 22, testamento: "NT", genero: "Apocalíptico",
    versiculoChave: ["Apocalipse 1:8","Apocalipse 5:12","Apocalipse 21:1","Apocalipse 22:20"],
    cristologia: "O Alfa e o Ômega. O Cordeiro que foi morto e vive. O Rei dos reis e Senhor dos senhores. A brilhante Estrela da Manhã."
  }
};

export function getLivroIntroducao(nome: string): LivroIntroducao | undefined {
  return LIVROS_INTRODUCOES[nome];
}
