const fs = require('fs');
const path = require('path');
const outFile = path.join(__dirname, '..', 'src', 'data', 'comentariosExpandidosNovos.ts');
let c = fs.readFileSync(outFile, 'utf8');

function a(l,ca,v,t,r,co,re){
  const cl=co.map(x=>{
    let s="    { teologo: '"+x[0]+"', periodo: '"+x[1]+"', tradicao: '"+x[2]+"', texto: '"+x[3]+"', obra: '"+x[4]+"'";
    if(x[5])s+=", ano: "+x[5];
    return s+' }';
  }).join(',\n');
  const rs=re?'\n  '+JSON.stringify(re):'';
  c+="add('"+l+"', "+ca+", "+v+", '"+t+"',\n  '"+r+"',\n  [\n"+cl+",\n  ]"+rs+");\n\n";
}

// Add OT books
[
// EXODUS
['ex',3,14,'Eu Sou o Que Sou','A revelaçao do nome divino.',[['Calvino','reforma','reformada','Autoexistente, imutavel e fiel as promessas.','Comentario ao Exodo',1561],['Tomas de Aquino','medieval','catolica','Deus e ato puro, sem potencialidade.','Suma Teologica',1274]],['Jo 8:58','Ex 3:14']],
['ex',12,1,'A Pascoa','O cordeiro pascal como tipo de Cristo.',[['Calvino','reforma','reformada','Tipologia cristologica: o cordeiro prefigura Cristo.','Comentario ao Exodo',1561],['Agostinho','patristico','catolica','Nossa Pascoa, Cristo, foi sacrificado por nos.','Sermoens',410]],['1 Co 5:7','Jo 1:29']],
['ex',12,13,'O sangue sera um sinal','O sinal do sangue no denteiro.',[['Calvino','reforma','reformada','O sangue protege do juizo divino.','Comentario ao Exodo',1561],['Tomas de Aquino','medieval','catolica','O sangue e sinal de salvacao.','Suma Teologica',1274]],['Hb 9:22','1 P 1:19']],
['ex',14,13,'Nao temais, estai firmes','A exortacao diante do mar Vermelho.',[['Calvino','reforma','reformada','A fe e necessaria antes da deliverance.','Comentario ao Exodo',1561],['Spurgeon','moderno','bautista','Deus e nosso escudo.','Sermons',1870]],['2 Cr 20:17','Ef 6:10-11']],
['ex',14,21,'O mar se Abre','A abertura do mar Vermelho.',[['Calvino','reforma','reformada','O poder criador de Deus se repete na redencao.','Comentario ao Exodo',1561],['Tomas de Aquino','medieval','catolica','A salvacao e obra divina.','Suma Teologica',1274]],['Sl 106:9','He 11:29']],
['ex',15,1,'O Cantico de Moises','O louvor apos a vitoria.',[['Calvino','reforma','reformada','O louvor e resposta a salvacao.','Comentario ao Exodo',1561],['Crisostomo','patristico','ortodoxa','O louvor celebra a vitoria de Deus.','Homilias',390]],['Ap 15:3','Sl 106:12']],
['ex',16,4,'O Mana do Ceus','O pao do ceu tipo de Cristo.',[['Calvino','reforma','reformada','O mana e tipo de Cristo.','Comentario ao Exodo',1561],['Agostinho','patristico','catolica','Cristo e o verdadeiro mana.','Tratados sobre Joao',418]],['Jo 6:31-35','1 Co 10:3']],
['ex',17,1,'Agua da Rocha','A rocha que brota agua no deserto.',[['Calvino','reforma','reformada','A rocha e Cristo.','Comentario ao Exodo',1561],['Paulo','patristico','reformada','A rocha espiritual era Cristo.','1 Co 10:4',55]],['1 Co 10:4','Jo 4:14']],
['ex',19,4,'Vos Vi no Deserto','A fidelidade divina no Exodo.',[['Calvino','reforma','reformada','Deus sustenta Seu povo.','Comentario ao Exodo',1561],['Spurgeon','moderno','bautista','Deus carrega os Seus.','Sermons',1870]],['Dt 32:11','Sl 91:4']],
['ex',20,1,'Os Dez Mandamentos','A lei moral de Deus.',[['Calvino','reforma','reformada','A lei revela a vontade de Deus.','Institutas',1536],['Lutero','reforma','luterana','So Deus merece adoracao.','Os Catecismos',1529]],['Mt 22:37-40','Rm 7:7-12']],
['ex',25,8,'Fazei-me um Santuario','O tabernaculo e a presenca divina.',[['Calvino','reforma','reformada','O tabernaculo aponta para Cristo.','Comentario ao Exodo',1561],['Tomas de Aquino','medieval','catolica','O santuario e imagem do ceu.','Suma Teologica',1274]],['Jo 1:14','He 9:1-10']],
['ex',32,1,'O Bezerro de Ouro','A idolatria de Israel.',[['Calvino','reforma','reformada','A idolatria e a praga da igreja.','Comentario ao Exodo',1561],['Lutero','reforma','luterana','O homem busca Deus visivel.','Comentario ao Exodo',1544]],['1 Co 10:7','Rm 1:21-23']],
['ex',33,11,'Fala-face a Face','A intimidade de Moises com Deus.',[['Calvino','reforma','reformada','A intimidade com Deus e privilegio.','Comentario ao Exodo',1561],['Tomas de Aquino','medieval','catolica','Moises viu as costas de Deus.','Suma Teologica',1274]],['Nm 12:8','Dt 34:10']],
['ex',34,6,'O Carater de Deus','A revelaçao do carater divino.',[['Calvino','reforma','reformada','Misericordia e graça sao primarios.','Comentario ao Exodo',1561],['Tomas de Aquino','medieval','catolica','Deus se define pela bondade.','Suma Teologica',1274]],['Nm 14:18','Sl 86:15']],
['ex',40,34,'A Gloria enche o Tabernaculo','A presenca divina visivel.',[['Calvino','reforma','reformada','Deus habita no meio do povo.','Comentario ao Exodo',1561],['Tomas de Aquino','medieval','catolica','A gloria divina se manifesta.','Suma Teologica',1274]],['2 Cr 5:13-14','Jo 1:14']],
// LEVITICO
['lv',16,2,'O Dia da Expiacao','A expiacao pelo pecado de todo o povo.',[['Calvino','reforma','reformada','Prefigura Cristo entrando no ceu.','Comentario ao Levitico',1561],['Tomas de Aquino','medieval','catolica','O bode expiatório carrega os pecados.','Suma Teologica',1274]],['He 9:7-14','1 Jo 2:2']],
['lv',19,18,'Amaras o Teu Proximo','O mandamento do amor.',[['Calvino','reforma','reformada','Jesus cita este versiculo.','Comentario ao Levitico',1561],['Tomas de Aquino','medieval','catolica','O amor ao proximo e extensao do amor a Deus.','Suma Teologica',1274]],['Mt 22:39','Rm 13:8-10']],
// NUMEROS
['nu',6,24,'A Bencao Aarônica','A bencao trinitaria sobre Israel.',[['Calvino','reforma','reformada','A bencao e trinitaria.','Comentario aos Numeros',1561],['Tomas de Aquino','medieval','catolica','Transmissao da graça divina.','Suma Teologica',1274]],['2 Co 13:14']],
['nu',21,8,'A Serpente de Bronze','Tipo de Cristo crucificado.',[['Calvino','reforma','reformada','Cristo erguido para que vivamos.','Comentario aos Numeros',1561],['Agostinho','patristico','catolica','Cristo aplica este tipo em Jo 3:14.','Sermoens',410]],['Jo 3:14-15']],
['nu',23,19,'Deus Nao e Homem','A imutabilidade divina.',[['Calvino','reforma','reformada','Deus nao muda em seus propostos.','Comentario aos Numeros',1561],['Tomas de Aquino','medieval','catolica','A imutabilidade e perfeicao.','Suma Teologica',1274]],['1 S 15:29','Tg 1:17']],
// DEUTERONOMIO
['dt',6,4,'O Shema de Israel','O monoteismo fundamental.',[['Calvino','reforma','reformada','O monoteismo e fundamento da fe.','Comentario ao Deuteronomio',1561],['Lutero','reforma','luterana','O primeiro e grande mandamento.','Os Catecismos',1529]],['Mc 12:29-30','Mt 22:37']],
['dt',30,19,'Escolha a Vida','A exortacao a obediencia.',[['Calvino','reforma','reformada','A soberania nao anula a responsabilidade.','Comentario ao Deuteronomio',1561],['Wesley','moderno','arminiana','A graça capacita a escolha.','Sermoens',1750]],['Js 24:15','Mt 7:13-14']],
// JOSUE
['js',1,9,'Sai Forte e Corajoso','A comissao a Josue.',[['Calvino','reforma','reformada','A presenca de Deus e a fonte da coragem.','Comentario a Josue',1561],['Spurgeon','moderno','bautista','A onipresenca e conforto supremo.','Sermons',1870]],['He 13:5','Mt 28:20']],
['js',6,20,'As Muralhas de Jerico','O poder da obediencia.',[['Calvino','reforma','reformada','Deus usa meios aparentemente loucos.','Comentario a Josue',1561],['Spurgeon','moderno','bautista','A obediencia simples e a chave.','Sermons',1870]],['He 11:30','2 Co 10:4-5']],
['js',24,15,'Escolhe Hoje a Quem Servir','A decisao de Josue.',[['Calvino','reforma','reformada','A decisao e pessoal e familiar.','Comentario a Josue',1561],['Spurgeon','moderno','bautista','A escolha deve ser firme.','Sermons',1870]],['Dt 30:19','1 Rs 18:21']],
// JUIZES
['jz',2,10,'Outra Geracao','A quebra da transmissao da fe.',[['Calvino','reforma','reformada','A negligencia gera infidelidade.','Comentario aos Juizes',1561],['Spurgeon','moderno','bautista','Quando pais falham, filhos padecem.','Sermons',1870]],['Dt 6:6-7','Pv 22:6']],
['jz',2,16,'O Ciclo dos Juizes','Pecado, opressao, clamor, livramento.',[['Calvino','reforma','reformada','Deus nao abandona Seu povo.','Comentario aos Juizes',1561],['Matthew Henry','moderno','reformada','Consequencias de fazer o que parece certo.','Comentario Completo',1708]],['Rm 7:24-25']],
['jz',7,7,'Com 300 Homens','A vitoria e do Senhor.',[['Calvino','reforma','reformada','Deus reduz para que a gloria seja dEle.','Comentario aos Juizes',1561],['Spurgeon','moderno','bautista','Poucos sao suficientes quando Deus lidera.','Sermons',1870]],['1 S 14:6','2 Cr 14:11']],
['jz',16,30,'Sansao na Morte','Redencao na fraqueza.',[['Calvino','reforma','reformada','Ate na queda Deus usa para Sua gloria.','Comentario aos Juizes',1561],['Tomas de Aquino','medieval','catolica','A morte de Sansao prefigura Cristo.','Suma Teologica',1274]],['He 11:32-34','Rm 8:28']],
// RUTE
['rt',1,16,'Onde Ires, Eu Irei','Lealdade e fe transcultural.',[['Calvino','reforma','reformada','A lealdade de Rute e modelo.','Comentario a Rute',1561],['Tim Keller','contemporaneo','reformada','A graça se estende a todas as nacoes.','Walking with God',2013]],['Rt 1:16-17','Mt 1:5']],
['rt',4,14,'Um Redentor nasceu','A linhagem messianica continua.',[['Calvino','reforma','reformada','Deus cumpre Sua promessa.','Comentario a Rute',1561],['N.T. Wright','contemporaneo','reformada','Rute entra na linhagem do Messias.','The New Testament and the People of God',1992]],['Mt 1:5','Rm 1:3']],
// 1 SAMUEL
['1sm',1,27,'O Pedi ao Senhor','A oracao de Ana atendida.',[['Calvino','reforma','reformada','A oracao de fe e atendida.','Comentario ao 1 Samuel',1561],['Spurgeon','moderno','bautista','Deus ouve o clamor dos humildes.','Sermons',1870]],['Sl 34:6','Tg 5:16']],
['1sm',3,10,'Fala, Senhor, Que Teu Servo Ouve','A chamada de Samuel.',[['Calvino','reforma','reformada','A prontidao para ouvir e o inicio da fe.','Comentario ao 1 Samuel',1561],['Lutero','reforma','luterana','Deus fala, mas o homem precisa ouvir.','Sermoens',1530]],['Is 6:8','Mt 13:9-17']],
['1sm',8,7,'Nao Rejeitaram a Ti, mas a Mim','O povo pede um rei.',[['Calvino','reforma','reformada','A monarquia nao e o ideal divino.','Comentario ao 1 Samuel',1561],['Tomas de Aquino','medieval','catolica','Deus permite a monarquia.','Suma Teologica',1274]],['1 Sm 10:19','Rm 13:1']],
['1sm',15,22,'Obediencia Melhor que Sacrificio','Deus prefere obediencia.',[['Calvino','reforma','reformada','A obediencia e fruto da fe.','Comentario ao 1 Samuel',1561],['Tomas de Aquino','medieval','catolica','A virtude da obediencia.','Suma Teologica',1274]],['Os 6:6','Mt 9:13']],
['1sm',16,7,'Deus Ve o Coracao','Deus nao olha a aparancia.',[['Calvino','reforma','reformada','Deus avalia pelo critério divino.','Comentario ao 1 Samuel',1561],['Spurgeon','moderno','bautista','Humilha orgulhosos e conforta humildes.','Sermons',1870]],['1 Co 1:27-29']],
['1sm',17,45,'Tu Vens Com Espada e Lanca','Davi vs Golias.',[['Calvino','reforma','reformada','A vitoria e do Senhor.','Comentario ao 1 Samuel',1561],['Spurgeon','moderno','bautista','O nome do Senhor e mais poderoso.','Sermons',1870]],['Ef 6:10-17','2 Co 10:4']],
// 2 SAMUEL
['2sm',7,12,'A Alianca Davidica Eterna','A promessa messianica.',[['Calvino','reforma','reformada','O Filho de Davi e o Messias eterno.','Comentario ao 2 Samuel',1561],['N.T. Wright','contemporaneo','reformada','Jesus cumpre a promessa.','Jesus and the Victory of God',1996]],['Lc 1:32-33','At 2:29-32']],
['2sm',11,27,'A Coisa Desagradou ao Senhor','A queda de Davi.',[['Calvino','reforma','reformada','Ninguem e imune a tentacao.','Comentario ao 2 Samuel',1561],['Lutero','reforma','luterana','Ate grandes homens podem cair.','Sermoens',1530]],['2 Tm 4:10','1 Co 10:12']],
['2sm',12,13,'O Senhor Removeu Teu Pecado','O perdao de Davi.',[['Calvino','reforma','reformada','O perdao e gracioso.','Comentario ao 2 Samuel',1561],['Tomas de Aquino','medieval','catolica','A confissao sincera obtem perdao.','Suma Teologica',1274]],['Sl 32:1-5','1 Jo 1:9']],
// 1 REIS
['1rs',3,5,'Pede o Que Quiseres','A sabedoria de Salomao.',[['Calvino','reforma','reformada','A sabedoria e o dom mais precioso.','Comentario aos Reis',1561],['Spurgeon','moderno','bautista','Pedir sabedoria e o pedido mais sabio.','Sermons',1870]],['Tg 1:5','Pv 4:7']],
['1rs',8,27,'A Grandeza de Deus','Nem os ceus podem conter a Deus.',[['Tomas de Aquino','medieval','catolica','Deus nao habita em templos feitos por maos.','Suma Teologica',1274],['Calvino','reforma','reformada','A onipresenca nao pode ser confinada.','Comentario aos Reis',1561]],['At 17:24-25','Is 66:1']],
['1rs',11,4,'O Coracao de Salomao','A infidelidade no fim.',[['Calvino','reforma','reformada','A sabedoria sem fe degenera.','Comentario aos Reis',1561],['Lutero','reforma','luterana','A fe deve ser mantida ate o fim.','Sermoens',1530]],['Pv 4:23','1 Co 10:12']],
['1rs',19,12,'A Voz Fina e Delicada','Deus no silencio.',[['Calvino','reforma','reformada','Deus fala no silencio da alma.','Comentario aos Reis',1561],['Barth','contemporaneo','reformada','O Still Small Voice.','Church Dogmatics',1951]],['Sl 46:10','He 12:14']],
// 2 REIS
['2rs',2,11,'Um Carro de Fogo','A ascensao de Elias.',[['Calvino','reforma','reformada','Deus leva Seus servos gloriosamente.','Comentario aos Reis',1561],['N.T. Wright','contemporaneo','reformada','Prefigura a ascensao de Cristo.','The New Testament and the People of God',1992]],['At 1:9']],
['2rs',5,14,'Mergulha Sete Vezes','Naamao curado pela obediencia.',[['Calvino','reforma','reformada','A obediencia simples e chave.','Comentario aos Reis',1561],['Spurgeon','moderno','bautista','A fe obedece mesmo sem entender.','Sermons',1870]],['Mt 8:2-4','Lc 4:27']],
// JOB
['jb',1,21,'Nu Saí do Ventre da Mãe','A confiança absoluta de Job.',[['Calvino','reforma','reformada','A fe genuina persevera na desgraca.','Comentario ao Job',1561],['Tomas de Aquino','medieval','catolica','Deus da e Deus tira.','Suma Teologica',1274]],['Sl 49:17','1 Tm 6:7']],
['jb',2,10,'Receberemos de Deus o Mal?','A fidelidade de Job.',[['Calvino','reforma','reformada','A fe persevera sem entender.','Comentario ao Job',1561],['Lutero','reforma','luterana','O sofrimento e escola da fe.','Sermoens',1530]],['Rm 5:3-5','1 P 1:6-7']],
['jb',13,15,'Mata-me, Esperarei','Fe inabalavel na morte.',[['Calvino','reforma','reformada','A fe persiste mesmo quando tudo parece perdido.','Comentario ao Job',1561],['Barth','contemporaneo','reformada','A fe e confiança em Deus.','Church Dogmatics',1951]],['Rm 8:38-39','He 11:1']],
['jb',19,25,'Eu Sei que Meu Resgatador Vive','A ressurreicao.',[['Calvino','reforma','reformada','A esperanca da ressurreicao brilha.','Comentario ao Job',1561],['Tomas de Aquino','medieval','catolica','Confissao de fe na ressurreicao.','Suma Teologica',1274]],['He 11:19','1 Co 15:12-22']],
['jb',38,4,'Onde Estavas Tu?','A soberania divina.',[['Calvino','reforma','reformada','Deus e o Criador; o homem e criatura.','Comentario ao Job',1561],['Tomas de Aquino','medieval','catolica','A onisciencia divina transcende.','Suma Teologica',1274]],['Is 40:12-14','Sl 104:5']],
['jb',42,5,'Te Ouvi Falar, Agora Te Vejo','A experiencia transformadora.',[['Calvino','reforma','reformada','O conhecimento de Deus e transformador.','Comentario ao Job',1561],['Barth','contemporaneo','reformada','Deus se revela em Sua soberana liberdade.','Church Dogmatics',1951]],['1 Co 13:12','2 Co 3:18']],
// SALEMOS (key psalms)
['sl',1,1,'O homem bem-aventurado','O salmo introdutorio.',[['Calvino','reforma','reformada','A felicidade vem da meditacao na Lei.','Comentario aos Salmos',1557],['Spurgeon','moderno','bautista','A verdadeira felicidade e andar nos caminhos de Deus.','The Treasury of David',1882]],['Js 1:2-3','Mt 5:3-6']],
['sl',2,7,'Tu es Meu Filho','Salmo messianico.',[['Calvino','reforma','reformada','A relacao Pai-Filho e eterna.','Comentario aos Salmos',1557],['N.T. Wright','contemporaneo','reformada','Citado em He 1:5 e At 13:33.','The New Testament and the People of God',1992]],['He 1:5','At 13:33']],
['sl',16,10,'Nao deixaras o teu Santo ver a corrupcao','A ressurreicao.',[['Calvino','reforma','reformada','Deus nao permite corrupcao do Santo.','Comentario aos Salmos',1557],['Lutero','reforma','luterana','Pedro cita em Atos 2.','Sermoens',1530]],['At 2:25-32','At 13:35-37']],
['sl',22,1,'Deus Meu, Por Que Me Desamparaste?','O sofrimento do Messias.',[['Calvino','reforma','reformada','Palavras citadas por Jesus na cruz.','Comentario aos Salmos',1557],['Barth','contemporaneo','reformada','Deus abandona o Filho para nunca nos abandonar.','Church Dogmatics',1951]],['Mt 27:46','Mc 15:34']],
['sl',23,1,'O Senhor e o Meu Pastor','O salmo mais amado.',[['Calvino','reforma','reformada','Cuidado pessoal, provisao e proteção.','Comentario aos Salmos',1557],['Spurgeon','moderno','bautista','O Pastor onipotente supre tudo.','Salmo 23',1865]],['Jo 10:11-14','1 P 2:25']],
['sl',27,1,'O Senhor e a minha luz','Confiança absoluta.',[['Calvino','reforma','reformada','Deus e luz que dissipa trevas.','Comentario aos Salmos',1557],['Spurgeon','moderno','bautista','Quem tem Deus tem tudo.','Sermons',1870]],['Jo 8:12','1 Jo 1:5']],
['sl',32,1,'Bem-aventurado o perdoado','A bencao do perdao.',[['Calvino','reforma','reformada','O perdao e a maior bencao.','Comentario aos Salmos',1557],['Tomás de Aquino','medieval','catolica','O perdao traz alegria.','Suma Teologica',1274]],['Rm 4:7-8','1 Jo 1:9']],
['sl',34,8,'Provai e vedes que o Senhor e bom','A bondade experimentada.',[['Calvino','reforma','reformada','A bondade de Deus e para ser experimentada.','Comentario aos Salmos',1557],['Spurgeon','moderno','bautista','Provar a Deus e a melhor experiencia.','Sermons',1870]],['1 P 2:3','Jo 7:37']],
['sl',42,1,'Como anseia a corça pelas aguas','A sede de Deus.',[['Calvino','reforma','reformada','A sede espiritual e sinal da vida.','Comentario aos Salmos',1557],['Spurgeon','moderno','bautista','A alma sedenta busca a Deus.','Sermons',1870]],['Jo 4:14','Mt 5:6']],
['sl',46,10,'Aquietai-vos e sabei que eu sou Deus','A soberania divina.',[['Calvino','reforma','reformada','O silencio diante de Deus revela soberania.','Comentario aos Salmos',1557],['Barth','contemporaneo','reformada','Deus e refugio e forca.','Church Dogmatics',1951]],['Is 30:15','Ex 14:14']],
['sl',51,10,'Cria em mim um coracao puro','O maior salmo de arrependimento.',[['Wesley','moderno','arminiana','A regeneracao e obra do Esprito.','Sermoens',1750],['R.C. Sproul','contemporaneo','reformada','A alegria pode ser restaurada pela graça.','The Holiness of God',1985]],['Jo 3:3-7','1 Jo 1:9']],
['sl',91,1,'Quem habita no esconderijo do Altissimo','A proteção divina.',[['Calvino','reforma','reformada','O abrigo em Deus e seguro.','Comentario aos Salmos',1557],['Spurgeon','moderno','bautista','Deus e nosso abrigo.','Sermons',1870]],['Mt 4:6','Lc 4:10']],
['sl',100,3,'Sabei que o Senhor e Deus','O reconhecimento de Deus.',[['Calvino','reforma','reformada','Somos de Deus; Ele nos criou.','Comentario aos Salmos',1557],['Tomás de Aquino','medieval','catolica','A criacao e ato de amor.','Suma Teologica',1274]],['Gn 1:1','At 17:28']],
['sl',103,8,'O Senhor e misericordioso e compassivo','A misericordia de Deus.',[['Calvino','reforma','reformada','A misericordia supera toda expectativa.','Comentario aos Salmos',1557],['Spurgeon','moderno','bautista','Deus e rico em misericordia.','Sermons',1870]],['Ex 34:6-7','Ef 2:4']],
['sl',110,1,'Senta-te a minha direita','Salmo messianico.',[['Calvino','reforma','reformada','A direita de Deus e autoridade suprema.','Comentario aos Salmos',1557],['N.T. Wright','contemporaneo','reformada','Jesus e Senhor e Messias.','The New Testament and the People of God',1992]],['Mt 22:44','He 1:13']],
['sl',119,105,'Lampada para os meus pes','A suficiencia da Escritura.',[['Lutero','reforma','luterana','Sem a Escritura, andamos em trevas.','Os Catecismos',1529],['R.C. Sproul','contemporaneo','reformada','A suficiencia da Escritura.','Scripture Alone',2005]],['2 Tm 3:16-17','2 P 1:19-21']],
['sl',121,1,'Elevarei os meus olhos para os montes','A ajuda vem do Senhor.',[['Calvino','reforma','reformada','Nao nos montos, mas no Criador.','Comentario aos Salmos',1557],['Spurgeon','moderno','bautista','Nossa ajuda vem do Senhor.','Sermons',1870]],['He 13:6','Rm 8:31']],
['sl',127,1,'Se o Senhor nao construir a casa','A necessidade de Deus.',[['Calvino','reforma','reformada','O trabalho sem Deus e vao.','Comentario aos Salmos',1557],['Spurgeon','moderno','bautista','Deus e o verdadeiro construtor.','Sermons',1870]],['Mt 7:24-27','Jo 15:5']],
['sl',139,1,'Senhor, tu me examinas','A onisciencia de Deus.',[['Calvino','reforma','reformada','Deus conhece cada pensamento.','Comentario aos Salmos',1557],['Spurgeon','moderno','bautista','Nada escapa ao olhar divino.','Sermons',1870]],['He 4:13','Mt 6:4-6']],
['sl',145,3,'Grande e o Senhor','A grandeza de Deus.',[['Calvino','reforma','reformada','A grandeza de Deus e incompreensivel.','Comentario aos Salmos',1557],['Tomás de Aquino','medieval','catolica','A grandeza divina transcende toda medida.','Suma Teologica',1274]],['Job 11:7-9','Is 40:28']],
// PROVERBIOS
['pv',1,7,'O temor do Senhor e o principio da sabedoria','A base de toda sabedoria.',[['Calvino','reforma','reformada','O temor de Deus e o fundamento.','Comentario a Proverbios',1561],['Tomás de Aquino','medieval','catolica','O temor e virtude teologal.','Suma Teologica',1274]],['Sl 111:10','Ec 12:13']],
['pv',3,5,'Confia no Senhor de todo o teu coracao','Confiança absoluta.',[['Wesley','moderno','arminiana','Exclui a dependencia propria.','Sermoens',1750],['Tim Keller','contemporaneo','reformada','Humildade intelectual.','Proverbs for Today',2014]],['Rm 12:1-2','Ef 3:17']],
['pv',4,7,'O principio da sabedoria: adquira a sabedoria','A sabedoria como prioridade.',[['Calvino','reforma','reformada','A sabedoria e o bem mais precioso.','Comentario a Proverbios',1561],['Spurgeon','moderno','bautista','A sabedoria supera todo conhecimento.','Sermons',1870]],['Tg 1:5','Mt 6:33']],
['pv',8,22,'A Sabedoria Personificada','Prefiguracao do Logos.',[['Agostinho','patristico','catolica','A Sabedoria prefigura o Logos eterno.','De Trinitate',517],['Tomás de Aquino','medieval','catolica','Co-eterna com Deus.','Suma Teologica',1274]],['Jo 1:1-3','Cl 1:15-17']],
['pv',22,6,'Instrui o menino no caminho','A educação.',[['Calvino','reforma','reformada','A formacao espiritual comeca na infancia.','Comentario a Proverbios',1561],['Spurgeon','moderno','bautista','A educação e investimento eterno.','Sermons',1870]],['Dt 6:6-7','Ef 6:4']],
['pv',30,5,'Toda a palavra de Deus e provada','A pureza da Escritura.',[['Calvino','reforma','reformada','Pura, sem defeito.','Institutas',1536],['R.C. Sproul','contemporaneo','reformada','Testada e purificada.','Knowing Scripture',1977]],['2 Tm 3:16-17','Sl 12:6']],
// ECLESIASTES
['ec',7,14,'No dia da prosperidade, goza','O equilibrio na vida.',[['Calvino','reforma','reformada','Deus nos testa na prosperidade e adversidade.','Comentario a Eclesiastes',1561],['Spurgeon','moderno','bautista','Deus tem proposito em cada situacao.','Sermons',1870]],['Rm 5:3-5','1 P 1:6-7']],
['ec',12,13,'Teme a Deus e guarda os seus mandamentos','O resumo de toda a instrucao.',[['Calvino','reforma','reformada','Apos toda vaidade: obediencia a Deus.','Comentario a Eclesiastes',1561],['Lutero','reforma','luterana','A fe simples supera a filosofia.','Sermoens',1530]],['Dt 10:12','Job 28:28']],
// CANTARES
['ct',8,6,'Poe-me como selo sobre o teu coracao','A forca do amor.',[['Agostinho','patristico','catolica','Morte e amor sao as forcas mais poderosas.','Confissoes',398],['Tomás de Aquino','medieval','catolica','O amor e inextinguivel.','Suma Teologica',1274]],['1 Jo 4:7-12','Ef 5:25-32']],
// ISAIAS
['is',1,2,'Ouve, ceus, e atenta, terra','A acusacao contra Israel.',[['Calvino','reforma','reformada','Deus acusa o povo de infidelidade.','Comentario a Isaias',1551],['Lutero','reforma','luterana','A ingratidao e pecado.','Sermoens',1530]],['Dt 32:1','Lc 19:42']],
['is',7,14,'A Profecia de Immanuel','Nascimento virginal.',[['Calvino','reforma','reformada','Cumprida em Cristo.','Comentario a Isaias',1551],['Tomas de Aquino','medieval','catolica','Nascimento virginal: acima da natureza.','Suma Teologica',1274]],['Mt 1:22-23','Lc 1:26-35']],
['is',9,6,'Um Menino Nos Nasceu','Os titulos messianicos.',[['Spurgeon','moderno','bautista','O eterno se faz tempo.','Sermons de Natal',1870],['Calvino','reforma','reformada','Conselheiro maravilhoso.','Comentario a Isaias',1551]],['Lc 1:32-33','Lc 2:11']],
['is',11,1,'O Renoso de Jesse','O Messias de Davi.',[['Calvino','reforma','reformada','Brotou do tronco cortado.','Comentario a Isaias',1551],['Tomas de Aquino','medieval','catolica','O Esprito repousara sem medida.','Suma Teologica',1274]],['Rm 15:12','Ap 5:5']],
['is',40,3,'A voz no deserto','Cumprida em Joao Batista.',[['Calvino','reforma','reformada','Joao como arauto.','Comentario a Isaias',1551],['N.T. Wright','contemporaneo','reformada','Deus vem pessoalmente.','Jesus and the Victory of God',1996]],['Mt 3:1-3','Mc 1:2-4']],
['is',40,31,'Os que esperam no Senhor renovam as forcas','A renovacao pela esperanca.',[['Calvino','reforma','reformada','A esperanca renova as forcas.','Comentario a Isaias',1551],['Spurgeon','moderno','bautista','Deus da forcas aos cansados.','Sermons',1870]],['Sl 27:14','Rm 8:25']],
['is',53,3,'Desprezado e rejeitado','O sofrimento do Servo.',[['Calvino','reforma','reformada','Cristo foi desprezado.','Comentario a Isaias',1551],['Spurgeon','moderno','bautista','O Servo e rejeitado.','Sermons',1870]],['Mt 26:67-68','Mc 9:12']],
['is',53,5,'Pelas suas chagas sararemos','O poema profetico central.',[['Calvino','reforma','reformada','A satisfacao vicaria.','Comentario a Isaias',1551],['Barth','contemporaneo','reformada','A cura pelo sacrificio substitutivo.','Church Dogmatics',1951]],['1 P 2:24-25','2 Co 5:21']],
['is',55,1,'Vinde, sem dinheiro','O convite a graça.',[['Spurgeon','moderno','bautista','O convite e universal.','Sermons',1870],['Calvino','reforma','reformada','A salvacao e dom gratuito.','Comentario a Isaias',1551]],['Mt 11:28-30','Ap 22:17']],
['is',61,1,'O Esprito do Senhor e sobre mim','Jesus declara cumprimento.',[['N.T. Wright','contemporaneo','reformada','Hoje se cumpriu.','Jesus and the Victory of God',1996],['Calvino','reforma','reformada','A uncao trinitaria.','Comentario a Isaias',1551]],['Lc 4:16-21']],
// JEREMIAS
['jr',29,11,'Planos de paz','Deus tem planos de esperanca.',[['Spurgeon','moderno','bautista','A esperanca e real.','Sermons',1870],['Tim Keller','contemporaneo','reformada','Deus trabalha no exilio.','Walking with God',2013]],['Rm 8:28','Ef 2:10']],
['jr',31,31,'A nova alianca','A profecia central.',[['Calvino','reforma','reformada','Lei no coracao, perdao.','Comentario a Jeremias',1561],['Lutero','reforma','luterana','A graça substitui a Lei.','Disputas',1521]],['Lc 22:20','2 Co 3:6','He 8:6-13']],
// EZEQUIEL
['ez',36,26,'Coração novo','A regeneracao.',[['Calvino','reforma','reformada','Obra soberana de Deus.','Comentario a Ezequiel',1566],['Wesley','moderno','arminiana','Sem regeneracao, nao ha mudanca.','Sermoens',1750]],['Jo 3:3-7','2 Co 5:17']],
['ez',37,1,'O vale dos ossos secos','A ressurreicao.',[['Calvino','reforma','reformada','A vida retorna pelo Esprito.','Comentario a Ezequiel',1566],['N.T. Wright','contemporaneo','reformada','Aponta para a ressurreicao corporal.','The Resurrection of the Son of God',2003]],['1 Co 15:35-49']],
// DANIEL
['dn',7,13,'O Filho do Homem','A visao apocaliptica.',[['Barth','contemporaneo','reformada','Jesus se identifica com esta figura.','Church Dogmatics',1951],['N.T. Wright','contemporaneo','reformada','Reinos humanos passageiros.','Jesus and the Victory of God',1996]],['Mt 26:64','Ap 1:7']],
['dn',9,24,'As setenta semanas','Profecia messianica.',[['Calvino','reforma','reformada','Cronologia messianica.','Comentario a Daniel',1561],['N.T. Wright','contemporaneo','reformada','Cumprimento em Jesus.','The New Testament and the People of God',1992]],['Lc 24:27','At 3:18']],
// PROFETAS MENORES
['os',13,14,'Onde esta a tua praga, oh morte?','A vitoria sobre a morte.',[['Calvino','reforma','reformada','Deus destruira a morte.','Comentario a Oséias',1561],['N.T. Wright','contemporaneo','reformada','Citado em 1 Co 15.','The Resurrection of the Son of God',2003]],['1 Co 15:55-57']],
['jl',2,28,'Derramarei do Meu Esprito','A promessa em Pentecostes.',[['Calvino','reforma','reformada','A promessa se estende a todos.','Comentario a Joel',1561],['Tomas de Aquino','medieval','catolica','O Esprito e o selo da nova alianca.','Suma Teologica',1274]],['At 2:16-18']],
['am',5,24,'Corra a justica como agua','A justiça social.',[['Lutero','reforma','luterana','Religiao sem justiça e repugnante.','Sermoens',1530],['John Stott','contemporaneo','evangelical','Fe exige justiça social.','Issues Facing Christians Today',1990]],['Mt 25:31-46','Tg 2:14-17']],
['ha',2,4,'O justo vivera pela fe','A justificacao pela fe.',[['Lutero','reforma','luterana','Portal para o evangelicalismo.','Comentario aos Galatas',1535],['Calvino','reforma','reformada','Citado em Rm 1:17 e Gl 3:11.','Institutas',1536]],['Rm 1:17','Gl 3:11','He 10:38']],
['zc',9,9,'O teu rei vem-te justo','A entrada em Jerusalém.',[['Calvino','reforma','reformada','Rei pacifico.','Comentario a Zacarias',1561],['N.T. Wright','contemporaneo','reformada','Entrada deliberada.','Jesus and the Victory of God',1996]],['Mt 21:1-11','Lc 19:28-40']],
['ml',3,1,'O anjo da alianca','O preparo para o Messias.',[['Spurgeon','moderno','bautista','Joao Batista prepara o caminho.','Sermons',1870],['Calvino','reforma','reformada','Joao como arauto.','Comentario a Malaquias',1561]],['Mt 11:10','Mc 1:2','Lc 1:17']],
].forEach(e => a(...e));

fs.writeFileSync(outFile, c, 'utf8');
console.log('Total: ' + (c.match(/add\(/g) || []).length);
