const fs = require('fs');
const path = require('path');
const outFile = path.join(__dirname, '..', 'src', 'data', 'comentariosExpandidosNovos.ts');
let content = fs.readFileSync(outFile, 'utf8');
// Remove everything after Genesis
const genesisEnd = content.indexOf('// EXODO');
if (genesisEnd > 0) content = content.substring(0, genesisEnd);
function addE(l, c, v, t, r, co, re) {
  const cl = co.map(x => { let s = "    { teologo: '"+x[0]+"', periodo: '"+x[1]+"', tradicao: '"+x[2]+"', texto: '"+x[3]+"', obra: '"+x[4]+"'"; if(x[5]) s += ", ano: "+x[5]; return s+' }'; }).join(',\n');
  const rs = re ? '\n  '+JSON.stringify(re) : '';
  content += `add('${l}', ${c}, ${v}, '${t}',\n  '${r}',\n  [\n${cl},\n  ]${rs});\n\n`;
}
// Isaiah
content += '// ====================================================================\n// ISAIAS\n// ====================================================================\n\n';
[
['is',1,2,'Ouve, ceus, e atenta, terra','A acusacao contra Israel rebelde.',[['Calvino','reforma','reformada','Deus acusa o povo de infidelidade.','Comentario a Isaias',1551],['Lutero','reforma','luterana','A ingratidao e pecado contra a graça.','Sermoens',1530]],['Dt 32:1','Lc 19:42']],
['is',7,14,'A Profecia de Immanuel','Nascimento virginal predito.',[['Calvino','reforma','reformada','Cumprida em Cristo. Mateus 1:23 cita.','Comentario a Isaias',1551],['Tomas de Aquino','medieval','catolica','Nascimento virginal: acima da natureza.','Suma Teologica',1274],['Atanasio','patristico','catolica','A encarnacao e obra da Trindade.','Contra Arios',318]],['Mt 1:22-23','Lc 1:26-35']],
['is',9,6,'Um Menino Nos Nasceu','Os titulos do rei messianico.',[['Spurgeon','moderno','bautista','O eterno se faz tempo, o infinito se faz finito.','Sermons de Natal',1870],['Calvino','reforma','reformada','Conselheiro maravilhoso: sabedoria de Deus.','Comentario a Isaias',1551],['Tomas de Aquino','medieval','catolica','Deus forte, Pai eterno, Principe da Paz.','Suma Teologica',1274],['N.T. Wright','contemporaneo','reformada','O governo sem fim.','Jesus and the Victory of God',1996]],['Lc 1:32-33','Lc 2:11']],
['is',11,1,'O Renoso de Jesse','O Messias da linhagem de Davi.',[['Calvino','reforma','reformada','Brotou do tronco aparentemente cortado.','Comentario a Isaias',1551],['Tomas de Aquino','medieval','catolica','O Esprito repousara sem medida.','Suma Teologica',1274]],['Rm 15:12','Ap 5:5','Mt 1:1']],
['is',40,3,'A voz que clama no deserto','Cumprida em Joao Batista.',[['Calvino','reforma','reformada','Joao como arauto do Messias.','Comentario a Isaias',1551],['N.T. Wright','contemporaneo','reformada','Deus vem pessoalmente atraves do deserto.','Jesus and the Victory of God',1996]],['Mt 3:1-3','Mc 1:2-4']],
['is',40,31,'Os que esperam no Senhor renovam as forcas','A renovacao pela esperanca.',[['Calvino','reforma','reformada','A esperanca divina renova as forcas.','Comentario a Isaias',1551],['Spurgeon','moderno','bautista','Deus da forcas aos cansados.','Sermons',1870]],['Sl 27:14','Rm 8:25']],
['is',53,5,'Pelas suas chagas sararemos','O mais importante poema profetico do AT.',[['Calvino','reforma','reformada','A satisfacao vicaria: Cristo paga nosso pecado.','Comentario a Isaias',1551],['Barth','contemporaneo','reformada','A cura vem pelo sacrificio substitutivo.','Church Dogmatics',1951],['Tomas de Aquino','medieval','catolica','Ele paga o que deviamos.','Suma Teologica',1274],['Spurgeon','moderno','bautista','A submissao voluntaria: nao abre a boca.','Sermons',1870]],['1 P 2:24-25','2 Co 5:21','Rm 4:25']],
['is',55,1,'Vinde, sem dinheiro','O convite a graça gratuita.',[['Spurgeon','moderno','bautista','O convite e universal e gratuito.','Sermons',1870],['Calvino','reforma','reformada','A salvacao e dom gratuito.','Comentario a Isaias',1551]],['Mt 11:28-30','Ap 22:17']],
['is',61,1,'O Esprito do Senhor e sobre mim','Jesus declara cumprimento na sinagoga.',[['N.T. Wright','contemporaneo','reformada','Hoje se cumpriu este texto.','Jesus and the Victory of God',1996],['Calvino','reforma','reformada','A uncao trinitaria para a missao.','Comentario a Isaias',1551]],['Lc 4:16-21']],
].forEach(e => addE(...e));
// Jeremiah
content += '// ====================================================================\n// JEREMIAS\n// ====================================================================\n\n';
[
['jr',29,11,'Planos de paz','Deus tem planos de esperanca.',[['Spurgeon','moderno','bautista','A esperanca e real.','Sermons',1870],['Tim Keller','contemporaneo','reformada','Deus trabalha no exilio.','Walking with God',2013]],['Rm 8:28','Ef 2:10']],
['jr',31,31,'A nova alianca','A profecia central da nova alianca.',[['Calvino','reforma','reformada','Lei no coracao, perdao, conhecimento direto.','Comentario a Jeremias',1561],['Barth','contemporaneo','reformada','A transformacao interior pelo Esprito.','Church Dogmatics',1951],['Lutero','reforma','luterana','A graça substitui a Lei.','Disputas',1521]],['Lc 22:20','2 Co 3:6','He 8:6-13']],
].forEach(e => addE(...e));
// Ezekiel
content += '// ====================================================================\n// EZEQUIEL\n// ====================================================================\n\n';
[
['ez',36,26,'Coração novo','A promessa de regeneracao.',[['Calvino','reforma','reformada','A regeneracao e obra soberana de Deus.','Comentario a Ezequiel',1566],['Wesley','moderno','arminiana','Sem regeneracao, nao ha mudanca.','Sermoens',1750],['Barth','contemporaneo','reformada','O novo coracao e dadiva do Esprito.','Church Dogmatics',1951]],['Jo 3:3-7','2 Co 5:17']],
['ez',37,1,'O vale dos ossos secos','A visao da ressurreicao.',[['Calvino','reforma','reformada','A vida retorna pelo Esprito.','Comentario a Ezequiel',1566],['N.T. Wright','contemporaneo','reformada','Aponta para a ressurreicao corporal.','The Resurrection of the Son of God',2003]],['1 Co 15:35-49']],
].forEach(e => addE(...e));
// Daniel
content += '// ====================================================================\n// DANIEL\n// ====================================================================\n\n';
[
['dn',7,13,'O Filho do Homem recebe dominio','A visao apocaliptica.',[['Barth','contemporaneo','reformada','Jesus se identifica com esta figura.','Church Dogmatics',1951],['N.T. Wright','contemporaneo','reformada','Reinos humanos passageiros, reino de Deus eterno.','Jesus and the Victory of God',1996],['Calvino','reforma','reformada','Cristo reina para sempre.','Comentario a Daniel',1561]],['Mt 26:64','Ap 1:7']],
['dn',9,24,'As setenta semanas','Profecia messianica cronologica.',[['Calvino','reforma','reformada','Cronologia messianica precisa.','Comentario a Daniel',1561],['N.T. Wright','contemporaneo','reformada','Cumprimento em Jesus.','The New Testament and the People of God',1992]],['Lc 24:27','At 3:18']],
].forEach(e => addE(...e));
// Minor Prophets
content += '// ====================================================================\n// PROFETAS MENORES\n// ====================================================================\n\n';
[
['os',13,14,'Onde esta a tua praga, oh morte?','A vitoria sobre a morte.',[['Calvino','reforma','reformada','Deus destruira a morte.','Comentario a Oséias',1561],['N.T. Wright','contemporaneo','reformada','Citado por Paulo em 1 Co 15.','The Resurrection of the Son of God',2003]],['1 Co 15:55-57']],
['jl',2,28,'Derramarei do Meu Esprito','A promessa cumprida em Pentecostes.',[['Calvino','reforma','reformada','A promessa se estende a todos.','Comentario a Joel',1561],['Tomas de Aquino','medieval','catolica','O Esprito e o selo da nova alianca.','Suma Teologica',1274]],['At 2:16-18']],
['am',5,24,'Corra a justica como agua','A demanda por justiça social.',[['Lutero','reforma','luterana','Religiao sem justiça e repugnante.','Sermoens',1530],['John Stott','contemporaneo','evangelical','Fe cristã exige justiça social.','Issues Facing Christians Today',1990]],['Mt 25:31-46','Tg 2:14-17']],
['ha',2,4,'O justo vivera pela fe','Versiculo fundamental da justificação.',[['Lutero','reforma','luterana','Portal para o evangelicalismo.','Comentario aos Galatas',1535],['Calvino','reforma','reformada','Citado em Rm 1:17 e Gl 3:11.','Institutas',1536]],['Rm 1:17','Gl 3:11','He 10:38']],
['zc',9,9,'O teu rei vem-te justo','A entrada em Jerusalém.',[['Calvino','reforma','reformada','Rei pacifico, nao militar.','Comentario a Zacarias',1561],['N.T. Wright','contemporaneo','reformada','Entrada deliberada como rei humilde.','Jesus and the Victory of God',1996]],['Mt 21:1-11','Lc 19:28-40']],
['ml',3,1,'O anjo da alianca','O preparo para o Messias.',[['Spurgeon','moderno','bautista','Joao Batista prepara o caminho.','Sermons',1870],['Calvino','reforma','reformada','Joao como arauto.','Comentario a Malaquias',1561]],['Mt 11:10','Mc 1:2','Lc 1:17']],
].forEach(e => addE(...e));
// MATTHEUS
content += '// ====================================================================\n// MATEUS\n// ====================================================================\n\n';
[
['mt',1,21,'Ele salvara o seu povo dos seus pecados','O nome Jesus: salvacao.',[['Calvino','reforma','reformada','Jesus significa Salvador.','Comentario a Mateus',1555],['Tomas de Aquino','medieval','catolica','O nome revela a missao do Messias.','Suma Teologica',1274]],['Lc 2:21','At 4:12']],
['mt',3,2,'Arrependei-vos, porque o reino dos ceus esta proximo','A pregação joanina.',[['Calvino','reforma','reformada','O reino de Deus se aproxima em Cristo.','Comentario a Mateus',1555],['N.T. Wright','contemporaneo','reformada','A proclamação do reino e urgente.','The New Testament and the People of God',1992]],['Mc 1:15','Lc 3:8']],
['mt',4,4,'Nem so de pao vivera o homem','A tentação no deserto.',[['Calvino','reforma','reformada','A Palavra de Deus e suficiente.','Comentario a Mateus',1555],['Lutero','reforma','luterana','A Escritura resiste a toda tentação.','Sermoens',1530]],['Dt 8:3','Lc 4:4']],
['mt',5,3,'Bem-aventurados os pobres de espirito','A primeira bem-aventurança.',[['Calvino','reforma','reformada','A pobreza espiritual e reconhecimento da necessidade de Deus.','Comentario a Mateus',1555],['Spurgeon','moderno','bautista','A humildade abre as portas do ceu.','Sermons',1870]],['Is 66:2','Tg 4:6']],
['mt',5,14,'Vos sois a luz do mundo','A missao da igreja.',[['Calvino','reforma','reformada','A luz nao pode ser escondida.','Comentario a Mateus',1555],['Spurgeon','moderno','bautista','As boas obras glorificam a Deus.','Sermons',1870]],['Jo 8:12','Fp 2:15']],
['mt',5,17,'Nvim vim derrogar a lei','Cumprimento, nao abrogacao.',[['Calvino','reforma','reformada','A lei encontra cumprimento em Cristo.','Comentario a Mateus',1555],['N.T. Wright','contemporaneo','reformada','De forma inesperada.','Jesus and the Victory of God',1996]],['Rm 8:3-4']],
['mt',6,33,'Buscai primeiro o reino de Deus','A prioridade do reino.',[['Calvino','reforma','reformada','Deus primeiro em tudo.','Comentario a Mateus',1555],['Spurgeon','moderno','bautista','Deus supre todas as necessidades.','Sermons',1870]],['Fp 4:19','Sl 37:4']],
['mt',7,7,'Pede e vos sera dado','A promessa da oração.',[['Calvino','reforma','reformada','A oracao e meio de graça.','Comentario a Mateus',1555],['Spurgeon','moderno','bautista','Deus ouve a oracao dos Seus.','Sermons',1870]],['Lc 11:9-10','Jo 14:13-14']],
['mt',9,12,'Nao sao os saos que precisam de medico','A missao de Cristo aos pecadores.',[['Calvino','reforma','reformada','Cristo veio para os doentes espirituais.','Comentario a Mateus',1555],['Spurgeon','moderno','bautista','O evangelho e para pecadores.','Sermons',1870]],['Mc 2:17','Lc 5:31-32']],
['mt',11,28,'Vinde a mim, todos os cansados','O convite mais doce.',[['Spurgeon','moderno','bautista','Descanso para oprimidos.','Sermons',1870],['Tim Keller','contemporaneo','reformada','Liberdade do trabalho servil.','King Cross',2011]],['Is 55:1','Mt 11:29-30']],
['mt',16,16,'Tu es o Cristo','A confissão messiânica de Pedro.',[['Calvino','reforma','reformada','Revelação divina, nao descoberta humana.','Comentario a Mateus',1555],['N.T. Wright','contemporaneo','reformada','Climax da revelação.','Jesus and the Victory of God',1996]],['Mc 8:29','Jo 6:68-69']],
['mt',16,18,'Edificare-se a minha igreja','A promessa da igreja indestrutivel.',[['Calvino','reforma','reformada','A igreja e construida sobre Cristo.','Comentario a Mateus',1555],['Tomas de Aquino','medieval','catolica','As portas do inferno nao prevalecerao.','Suma Teologica',1274]],['Ef 2:20','1 P 2:4-6']],
['mt',22,37,'O grande mandamento','Amor total a Deus e ao proximo.',[['Tomas de Aquino','medieval','catolica','O fim ultimo do homem.','Suma Teologica',1274],['Calvino','reforma','reformada','Dois mandamentos, uma lei.','Institutas',1536]],['Mc 12:29-30','Lc 10:25-28']],
['mt',24,14,'Este evangelho do reino sera pregado','A missao universal.',[['Calvino','reforma','reformada','O evangelho sera pregado a todas as nacoes.','Comentario a Mateus',1555],['John Piper','contemporaneo','reformada','A missao e o proposito de Deus.','Let the Nations Be Glad',1993]],['Mc 13:10','Rm 10:18']],
['mt',24,30,'A vinda do Filho do Homem','A segunda vinda.',[['Calvino','reforma','reformada','Visivel e gloriosa.','Comentario a Mateus',1555],['N.T. Wright','contemporaneo','reformada','A vindicacao de Deus.','Jesus and the Victory of God',1996]],['Mc 13:24-27','1 Ts 4:16-17','Ap 1:7']],
['mt',26,41,'Vigiai e orai','A alerta espiritual.',[['Calvino','reforma','reformada','A vigilancia e a oracao sao armas contra a tentação.','Comentario a Mateus',1555],['Spurgeon','moderno','bautista','A oracao e o antidoto contra a tentação.','Sermons',1870]],['Mc 14:38','1 P 5:8']],
['mt',27,46,'Deus meu, por que me desamparaste?','A setima palavra da cruz.',[['Calvino','reforma','reformada','Deus abandonou o Filho para nos aceitar.','Comentario a Mateus',1555],['Barth','contemporaneo','reformada','O abandono e vicario, nao pessoal.','Church Dogmatics',1951]],['Sl 22:1','Mc 15:34']],
['mt',28,18,'Toda autoridade me foi dada','A Grande Comissao.',[['John Piper','contemporaneo','reformada','Autoridade cosmica para missao.','Let the Nations Be Glad',1993],['Calvino','reforma','reformada','Discipulos: ensino, batismo, obediencia.','Comentario a Mateus',1555],['N.T. Wright','contemporaneo','reformada','A missao nao e opcional.','The Mission of God',2006]],['Mc 16:15-18','Lc 24:46-49']],
].forEach(e => addE(...e));
// MARCOS
content += '// ====================================================================\n// MARCOS\n// ====================================================================\n\n';
[
['mc',1,1,'Principio do evangelho','Cristo e Filho de Deus e Messias.',[['N.T. Wright','contemporaneo','reformada','Urgencia messianica.','Jesus and the Victory of God',1996],['Calvino','reforma','reformada','Filho de Deus: natureza divina.','Comentario a Marcos',1551]],['Jo 20:31','Rm 1:3-4']],
['mc',2,5,'Filho, os teus pecados sao perdoados','A autoridade de Jesus para perdoar.',[['Calvino','reforma','reformada','So Deus pode perdoar pecados.','Comentario a Marcos',1551],['Tomas de Aquino','medieval','catolica','A autoridade divina em Jesus e evidente.','Suma Teologica',1274]],['Lc 5:20-26','Jo 5:14']],
['mc',4,39,'Enfreça! Calma-te!','O poder de Jesus sobre a natureza.',[['Calvino','reforma','reformada','O poder divino se manifesta na criacao.','Comentario a Marcos',1551],['Tomas de Aquino','medieval','catolica','Cristo e Senhor da natureza.','Suma Teologica',1274]],['Lc 8:24','Mt 8:27']],
['mc',5,36,'Nao temas, cre apenas','A fe diante do impossivel.',[['Calvino','reforma','reformada','A fe supera o medo.','Comentario a Marcos',1551],['Spurgeon','moderno','bautista','A fe e o antidoto contra o medo.','Sermons',1870]],['Lc 8:50','Jo 11:25']],
['mc',8,36,'De que adianta ao homem ganhar o mundo inteiro','A perda da alma.',[['Calvino','reforma','reformada','A alma e mais preciosa que o mundo.','Comentario a Marcos',1551],['Spurgeon','moderno','bautista','Nada vale mais que a alma.','Sermons',1870]],['Mt 16:26','Lc 9:25']],
['mc',10,14,'Deixai vir a mim as criancinhas','A recepção das crianças.',[['Calvino','reforma','reformada','As criancas sao modelo de humildade.','Comentario a Marcos',1551],['Spurgeon','moderno','bautista','Cristo ama as criancas.','Sermons',1870]],['Mt 19:13-15','Lc 18:15-17']],
['mc',10,45,'Dar a sua vida em resgate por muitos','O proposito da missao de Jesus.',[['Calvino','reforma','reformada','Substitutiva e redentora.','Comentario a Marcos',1551],['Wesley','moderno','arminiana','Lideranca e servico.','Sermoens',1750],['Tomas de Aquino','medieval','catolica','O maior preco possivel.','Suma Teologica',1274]],['Mt 20:28','1 Tm 2:6']],
['mc',15,33,'Escuridao sobre toda a terra','Trevas cosmicas na crucificação.',[['Calvino','reforma','reformada','A criacao geme na morte do Criador.','Comentario a Marcos',1551],['Tomas de Aquino','medieval','catolica','O veu rasgado: acesso aberto.','Suma Teologica',1274]],['Mt 27:45-46','Lc 23:44-45']],
['mc',16,6,'Ele ressuscitou!','O fato central da fe.',[['Spurgeon','moderno','bautista','Sem ressurreicao, fe va.','Sermons',1870],['N.T. Wright','contemporaneo','reformada','O tumulo vazio e fato historico.','The Resurrection of the Son of God',2003]],['1 Co 15:3-4','Rm 1:4']],
].forEach(e => addE(...e));
// LUCAS
content += '// ====================================================================\n// LUCAS\n// ====================================================================\n\n';
[
['lc',1,26,'A Anunciacao','O anuncio a Maria.',[['Tomas de Aquino','medieval','catolica','Obra da Trindade.','Suma Teologica',1274],['Calvino','reforma','reformada','Maria como modelo de submissao.','Comentario a Lucas',1551]],['Mt 1:18-25']],
['lc',1,38,'Eis aqui a serva do Senhor','A submissao de Maria.',[['Calvino','reforma','reformada','Maria e modelo de obediencia.','Comentario a Lucas',1551],['Tomas de Aquino','medieval','catolica','A submissao de Maria e ato de fe.','Suma Teologica',1274]],['Lc 1:45','Fp 2:8']],
['lc',2,10,'Anuncio-vos uma grande alegria','O nascimento de Cristo.',[['Calvino','reforma','reformada','A alegria do nascimento do Salvador.','Comentario a Lucas',1551],['Spurgeon','moderno','bautista','A maior noticia de todos os tempos.','Sermons',1870]],['Is 9:6','Mt 1:21']],
['lc',4,18,'O Esprito do Senhor e sobre mim','Jesus declara o cumprimento.',[['N.T. Wright','contemporaneo','reformada','Se identifica como Servo Sofredor.','Jesus and the Victory of God',1996],['Calvino','reforma','reformada','Missao: libertar, curar, proclamar.','Comentario a Lucas',1551]],['Is 61:1-2']],
['lc',7,13,'Moço, eu te digo, levanta-te','A ressurreicao do filho da viuva.',[['Calvino','reforma','reformada','O poder de Jesus sobre a morte.','Comentario a Lucas',1551],['Tomas de Aquino','medieval','catolica','Cristo e a ressurreicao e a vida.','Suma Teologica',1274]],['Jo 11:25','Mt 5:28-29']],
['lc',9,23,'Se alguem quer vir apos mim','O custo do discipulado.',[['Calvino','reforma','reformada','O discipulado exige negacao diaria.','Comentario a Lucas',1551],['Tim Keller','contemporaneo','reformada','Seguir Jesus custa tudo.','King Cross',2011]],['Mt 16:24','Mc 8:34']],
['lc',10,27,'Amaras o Senhor... e o teu proximo','O mandamento duplo do amor.',[['Tomas de Aquino','medieval','catolica','O amor a Deus e ao proximo sao inseparaveis.','Suma Teologica',1274],['Calvino','reforma','reformada','A Lei se resume em amor.','Comentario a Lucas',1551]],['Mt 22:37-40','Rm 13:8-10']],
['lc',10,30,'A parabola do bom samaritano','A misericordia em acao.',[['Calvino','reforma','reformada','O amor ao proximo nao tem limites.','Comentario a Lucas',1551],['Tim Keller','contemporaneo','reformada','O evangelho nos faz samaritanos.','Generous Justice',2010]],['Mt 25:31-46','Tg 2:14-17']],
['lc',12,32,'Nao temas, pequeno rebanho','A providencia do Pai.',[['Calvino','reforma','reformada','Deus cuida do Seu rebanho.','Comentario a Lucas',1551],['Spurgeon','moderno','bautista','Deus nunca abandona os Seus.','Sermons',1870]],['Mt 6:26-30','1 P 5:7']],
['lc',15,11,'A parabola do filho prodiro','A graça que restaura.',[['Lutero','reforma','luterana','Restauracao completa.','Sermoens',1530],['Tim Keller','contemporaneo','reformada','A graça precede o arrependimento.','The Prodigal God',2008],['Barth','contemporaneo','reformada','Dois tipos de perda.','Church Dogmatics',1951],['Agostinho','patristico','catolica','Graça generosa.','Sermoens',410]],['Jo 3:16-17','Ef 2:1-10']],
['lc',19,10,'Procurar e salvar o que estava perdido','A missao de Jesus.',[['Calvino','reforma','reformada','Cristo veio para salvar os perdidos.','Comentario a Lucas',1551],['Spurgeon','moderno','bautista','A missao de Jesus e resgate.','Sermons',1870]],['Lc 5:31-32','1 Tm 1:15']],
['lc',22,19,'Isto e o meu corpo','A instituicao da Ceia.',[['Calvino','reforma','reformada','A Ceia e memorial e presenca espiritual.','Comentario a Lucas',1551],['Tomas de Aquino','medieval','catolica','A transubstanciacao e o misterio da fe.','Suma Teologica',1274]],['1 Co 11:23-26','Mt 26:26-28']],
['lc',23,34,'Pai, perdoa-les','Primeira palavra da cruz.',[['Calvino','reforma','reformada','Intercessao pelos inimigos.','Comentario a Lucas',1551],['Barth','contemporaneo','reformada','Perdao incondicional.','Church Dogmatics',1951]],['Mt 27:38-39','At 7:60']],
['lc',23,46,'Pai, nas tuas maos entrego o meu espirito','A morte de Cristo em fe.',[['Calvino','reforma','reformada','Cristo morre confiando no Pai.','Comentario a Lucas',1551],['Tomas de Aquino','medieval','catolica','A submissao perfeita ao Pai.','Suma Teologica',1274]],['Sl 31:5','Mt 27:50']],
['lc',24,27,'E comecando por Moises e todos os profetas','Jesus explica as Escrituras.',[['Calvino','reforma','reformada','Todo o AT aponta para Cristo.','Comentario a Lucas',1551],['N.T. Wright','contemporaneo','reformada','O AT tem sentido em Cristo.','The Resurrection of the Son of God',2003]],['Lc 24:44-47','At 3:18']],
['lc',24,46,'Era necessario que o Cristo sofresse','Cristo ressurreto explica o AT.',[['N.T. Wright','contemporaneo','reformada','O AT aponta para a cruz.','The Resurrection of the Son of God',2003],['Calvino','reforma','reformada','Missao universal.','Comentario a Lucas',1551]],['1 Co 15:3-4','At 17:2-3']],
].forEach(e => addE(...e));
// JOAO
content += '// ====================================================================\n// JOAO\n// ====================================================================\n\n';
[
['jo',1,1,'No principio era o Verbo','A preexistencia do Verbo.',[['Atanasio','patristico','catolica','Eterno e igual ao Pai.','Contra Arios',318],['Calvino','reforma','reformada','Distincao trinitaria.','Comentario a Joao',1553],['Tomas de Aquino','medieval','catolica','Consubstancial ao Pai.','Suma Teologica',1274]],['Cl 1:15-17','He 1:1-3','1 Jo 1:1-2']],
['jo',1,14,'O Verbo se fez carne','A encarnacao.',[['Agostinho','patristico','catolica','O eterno no tempo, o infinito no finito.','Tratados sobre Joao',418],['Lutero','reforma','luterana','Deus habita conosco.','Sermoens',1530],['Crisostomo','patristico','ortodoxa','Vimos a sua gloria.','Homilias',390]],['Mt 1:23','Fp 2:6-8','1 Tm 3:16']],
['jo',3,16,'Porque Deus amou o mundo','O versiculo mais famoso.',[['Lutero','reforma','luterana','O amor e a causa da salvacao.','Comentario a Joao',1523],['Calvino','reforma','reformada','A fe como instrumento.','Comentario a Joao',1553],['Spurgeon','moderno','bautista','Amor sem limites.','Sermons',1870],['John Piper','contemporaneo','reformada','A medida e a ddiva do Filho.','The Pleasures of God',1991]],['Rm 5:8','1 Jo 4:9-10','Ef 2:4-5']],
['jo',4,14,'Agua viva','O que satisfaz a alma.',[['Tim Keller','contemporaneo','reformada','Cristo preenche o vazio.','King Cross',2011],['John Stott','contemporaneo','evangelical','Dom permanente.','The Message of John',1988]],['Is 55:1','Ap 22:17']],
['jo',6,35,'Eu sou o pao da vida','Primeiro Eu Sou joanino.',[['Spurgeon','moderno','bautista','Satisfacao da fome da alma.','Sermons',1870],['Agostinho','patristico','catolica','Eucaristia nutre a alma.','Tratados',418]],['Jo 6:48-51']],
['jo',8,12,'Eu sou a luz do mundo','Segundo Eu Sou.',[['Calvino','reforma','reformada','Ilumina as trevas do pecado.','Comentario a Joao',1553],['N.T. Wright','contemporaneo','reformada','Cumpre a festa dos tabernaculos.','The New Testament and the People of God',1992]],['Is 42:6','Is 49:6']],
['jo',8,32,'Conhecereis a verdade, e a verdade vos libertara','A libertacao pela verdade.',[['Lutero','reforma','luterana','Quebra correntes do pecado.','Comentario a Joao',1523],['Spurgeon','moderno','bautista','Liberdade da culpa.','Sermons',1870]],['Jo 8:36','2 Co 3:17']],
['jo',8,58,'Antes que Abraao existisse, Eu sou','A eternidade de Jesus.',[['Tomas de Aquino','medieval','catolica','Divindade declarada.','Suma Teologica',1274],['Calvino','reforma','reformada','Preexistencia eterna.','Comentario a Joao',1553]],['Ex 3:14','Jo 1:1-3','Fp 2:6']],
['jo',10,10,'Eu vim para que tenham vida','O proposito de Cristo.',[['Wesley','moderno','arminiana','Abundancia, nao apenas existencia.','Sermoens',1750],['John Piper','contemporaneo','reformada','Plenitude de relacao com Deus.','Desiring God',1986]],['Jo 10:11','Jo 15:5']],
['jo',10,11,'Eu sou o bom pastor','Sacrificio voluntario.',[['Spurgeon','moderno','bautista','Da a vida pelas ovelhas.','Sermons',1870],['Crisostomo','patristico','ortodoxa','Ama ate a morte.','Homilias',390]],['Ef 5:25','1 P 2:21-25']],
['jo',11,25,'Eu sou a ressurreicao e a vida','A mais poderosa declaracao.',[['Spurgeon','moderno','bautista','Crer e viver mesmo morrendo.','Sermons',1870],['Calvino','reforma','reformada','Fe e a chave.','Comentario a Joao',1553],['Tomas de Aquino','medieval','catolica','Causa eficiente da ressurreicao.','Suma Teologica',1274]],['Jo 11:43-44','1 Co 15:20-23']],
['jo',14,6,'Eu sou o caminho, a verdade e a vida','A declaracao exclusivista.',[['Calvino','reforma','reformada','Unica via ao Pai.','Comentario a Joao',1553],['Lutero','reforma','luterana','Unico mediador.','Comentario a Joao',1523],['Tomas de Aquino','medieval','catolica','Cristo e caminho, verdade e vida.','Suma Teologica',1274]],['At 4:12','1 Tm 2:5']],
['jo',14,27,'A minha paz vos dou','A paz de Cristo.',[['Calvino','reforma','reformada','A paz de Cristo supera a do mundo.','Comentario a Joao',1553],['Spurgeon','moderno','bautista','Paz que o mundo nao pode dar.','Sermons',1870]],['Fp 4:7','Is 26:3']],
['jo',15,5,'Eu sou a vide, vos as sarcas','Dependencia radical.',[['Wesley','moderno','arminiana','Graça indispensavel.','Sermoens',1750],['Tim Keller','contemporaneo','reformada','Humildade radical.','King Cross',2011]],['Gl 2:20','Fp 4:13']],
['jo',15,13,'Ninguem tem maior amor do que este','O amor sacrificial.',[['Calvino','reforma','reformada','O amor de Cristo e o modelo supremo.','Comentario a Joao',1553],['Tomas de Aquino','medieval','catolica','O amor sacrificial e o mais elevado.','Suma Teologica',1274]],['Rm 5:8','1 Jo 3:16']],
['jo',17,3,'Esta e a vida eterna: que te conhecam','O conhecimento de Deus como vida.',[['Calvino','reforma','reformada','Conhecimento relacional.','Comentario a Joao',1553],['Tomas de Aquino','medieval','catolica','Visao de Deus como fim ultimo.','Suma Teologica',1274]],['1 Jo 5:11-13']],
['jo',19,30,'Esta consumado','A obra da redencao completa.',[['Spurgeon','moderno','bautista','Nada mais a acrescentar.','Sermons',1870],['Calvino','reforma','reformada','Tetelestai: pago integralmente.','Comentario a Joao',1553],['Barth','contemporaneo','reformada','O ponto alto da historia.','Church Dogmatics',1951]],['He 9:12','He 10:10-14']],
].forEach(e => addE(...e));
// ATOS
content += '// ====================================================================\n// ATOS DOS APOSTOLOS\n// ====================================================================\n\n';
[
['at',1,8,'Recebereis poder, quando o Esprito Santo descer','A promessa do Esprito.',[['Calvino','reforma','reformada','O Esprito capacita para testemunho.','Comentario aos Atos',1552],['N.T. Wright','contemporaneo','reformada','De Jerusalem ao mundo: expansao do reino.','The Acts of the Apostles',2008]],['Mt 28:19-20','Mc 16:15']],
['at',2,38,'Arrependei-vos, e cada um de vos seja batizado','A primeira pregação apostolica.',[['Calvino','reforma','reformada','Arrependimento e fe sao instrumentos, nao meritos.','Comentario aos Atos',1552],['Wesley','moderno','arminiana','A promessa e para todos os que se arrependem.','Sermoens',1750],['Tomas de Aquino','medieval','catolica','Batismo como sinal da graça.','Suma Teologica',1274]],['Mc 16:16','Rm 6:3-4']],
['at',4,12,'Em nenhum outro ha salvacao','A exclusividade de Cristo.',[['Calvino','reforma','reformada','Salvacao somente em Cristo.','Comentario aos Atos',1552],['R.C. Sproul','contemporaneo','reformada','Exclusividade cristologica.','The Holiness of God',1985]],['Jo 14:6','1 Tm 2:5']],
['at',5,29,'E necessario obedecer a Deus antes que aos homens','A superioridade da Lei divina.',[['Calvino','reforma','reformada','A obediencia a Deus tem prioridade.','Comentario aos Atos',1552],['Lutero','reforma','luterana','Deus deve ser obedecido acima de tudo.','Sermoens',1530]],['Dt 5:29','Mt 22:37']],
['at',7,55,'Eis que vejo os ceus abertos','A visao estefica da gloria de Cristo.',[['Calvino','reforma','reformada','Cristo esta a direita de Deus.','Comentario aos Atos',1552],['Tomas de Aquino','medieval','catolica','A exaltacao de Cristo e visivel aos fiel.','Suma Teologica',1274]],['Mc 16:19','Rm 8:34']],
['at',9,3,'Saulo, Saulo, por que me persegues?','A conversao de Saulo.',[['Calvino','reforma','reformada','A graça de Deus alcanca os perseguidores.','Comentario aos Atos',1552],['Spurgeon','moderno','bautista','Deus pode converter qualquer um.','Sermons',1870]],['1 Tm 1:15','Gl 1:15-16']],
['at',10,34,'Deus nao faz acepcao de pessoas','A universalidade do evangelho.',[['Calvino','reforma','reformada','O evangelho e para todas as nacoes.','Comentario aos Atos',1552],['Tomas de Aquino','medieval','catolica','A graça de Deus e universal.','Suma Teologica',1274]],['Rm 2:11','Ef 2:11-14']],
['at',15,8,'Deus purificou os seus coracoes pela fe','A pureza pela fe.',[['Calvino','reforma','reformada','A fe purifica o coracao.','Comentario aos Atos',1552],['Tomas de Aquino','medieval','catolica','A fe opera pelo amor.','Suma Teologica',1274]],['Rm 3:22','Ef 2:8-9']],
['at',16,31,'Cre no Senhor Jesus, e seras salvo','A simplificacao do evangelho.',[['Calvino','reforma','reformada','A fe em Cristo e o meio da salvacao.','Comentario aos Atos',1552],['Spurgeon','moderno','bautista','Salvacao pela fe em Cristo.','Sermons',1870]],['Rm 10:9-10','Ef 2:8']],
['at',17,22,'Homens de Atenas','Paulo na Areopago: engajamento cultural.',[['N.T. Wright','contemporaneo','reformada','Modelo de apologia cultural.','The New Testament and the People of God',1992],['John Stott','contemporaneo','evangelical','Ponte entre culturas.','The Message of Acts',1990]],['Is 66:1','Sl 139:7-10']],
['at',20,28,'A igreja de Deus, que Ele comprou com o seu proprio sangue','O preco da igreja.',[['Calvino','reforma','reformada','A igreja foi adquirida com o sangue de Cristo.','Comentario aos Atos',1552],['Tomas de Aquino','medieval','catolica','O sacrificio de Cristo e pela igreja.','Suma Teologica',1274]],['Ef 5:25','1 P 1:18-19']],
['at',22,16,'Levanta-te, e sendo batizado, lava os teus pecados','O batismo e o perdao.',[['Calvino','reforma','reformada','O batismo e sinal do perdao recebido.','Comentario aos Atos',1552],['Tomas de Aquino','medieval','catolica','O batismo aplica o perdao.','Suma Teologica',1274]],['Mc 16:16','Rm 6:3-4']],
['at',26,18,'Abrir os seus olhos, para que se convertam','A missao paulina aos gentios.',[['Calvino','reforma','reformada','A conversao e obra do Esprito.','Comentario aos Atos',1552],['N.T. Wright','contemporaneo','reformada','Paulo e instrumento da missao divina.','The New Testament and the People of God',1992]],['Is 42:6-7','2 Co 4:6']],
['at',28,28,'Saibam, pois, que a salvacao de Deus foi enviada aos gentios','A universalidade do evangelho.',[['Calvino','reforma','reformada','O evangelho e para todas as nacoes.','Comentario aos Atos',1552],['N.T. Wright','contemporaneo','reformada','O missionario cumpre sua chamada.','The New Testament and the People of God',1992]],['Rm 1:16','Mt 28:19']],
].forEach(e => addE(...e));
// ROMANOS
content += '// ====================================================================\n// ROMANOS\n// ====================================================================\n\n';
[
['rm',1,16,'Nao me envergonho do evangelho','O versiculo tematico de Romanos.',[['Lutero','reforma','luterana','A chave de Romanos: o poder de Deus para salvacao.','Comentario aos Romanos',1515],['Calvino','reforma','reformada','O evangelho e poder de Deus para fe.','Comentario aos Romanos',1551],['Tim Keller','contemporaneo','reformada','O evangelho nao e apenas o ABC, mas o A-Z da fe.','Romans 1-7 For You',2014]],['1 Co 1:18','Rm 1:17']],
['rm',3,23,'Nao ha justo, nem um sequer','A universalidade do pecado.',[['Calvino','reforma','reformada','A depravacao total: ninguem busca a Deus.','Comentario aos Romanos',1551],['Tomas de Aquino','medieval','catolica','A razao obscurecida pelo pecado original.','Suma Teologica',1274]],['Sl 14:1-3','Rm 3:23']],
['rm',3,21,'Mas agora se manifestou a justica de Deus','A justificacao pela fe em Cristo.',[['Lutero','reforma','luterana','Justica alienada: a justica de Cristo nos e creditada.','Comentario aos Romanos',1515],['Calvino','reforma','reformada','A justica pela fe, sem obras da Lei.','Comentario aos Romanos',1551],['N.T. Wright','contemporaneo','reformada','Justica de Deus e fidelidade a alianca.','Justification',2009]],['Ef 2:8-9','Fp 3:9']],
['rm',5,8,'Deus prova o seu amor para connosco','A cruz como demonstracao suprema do amor.',[['Calvino','reforma','reformada','Amor independente do merito humano.','Comentario aos Romanos',1551],['Barth','contemporaneo','reformada','A cruz e o evento central da historia.','Church Dogmatics',1951]],['Jo 3:16','1 Jo 4:10']],
['rm',6,23,'O salario do pecado e a morte','Morte versus vida eterna.',[['Spurgeon','moderno','bautista','Salario e o que merecemos. Ddiva e o que Deus da.','Sermons',1870],['Calvino','reforma','reformada','A graça gratuita supera o merito do pecado.','Comentario aos Romanos',1551]],['Jó 20:29','Rm 5:17','Ef 2:5-6']],
['rm',7,24,'Nao faço o bem que quero','A luta contra o pecado.',[['Lutero','reforma','luterana','A lei mostra o pecado, mas nao da poder para vence-lo.','Comentario aos Romanos',1515],['Calvino','reforma','reformada','A luta do crente contra a carne.','Comentario aos Romanos',1551]],['Gl 5:17','Gn 4:7']],
['rm',8,1,'Nao ha, portanto, nenhuma condenacao','A proclamacao da liberdade em Cristo.',[['Lutero','reforma','luterana','A sentenca mais doce da Escritura.','Comentario aos Romanos',1515],['Calvino','reforma','reformada','Libertacao da condenacao e do pecado.','Comentario aos Romanos',1551]],['Jo 5:24','8:36']],
['rm',8,28,'E sabemos que todas as coisas contribuem juntamente para o bem','A soberania de Deus na adversidade.',[['Calvino','reforma','reformada','Deus ordena todas as coisas para o bem dos eleitos.','Comentario aos Romanos',1551],['Spurgeon','moderno','bautista','Tudo, sem excecao, coopera para o bem.','Sermons',1870],['Tim Keller','contemporaneo','reformada','Nao promete conforto, mas proposito no sofrimento.','Walking with God',2013]],['Jó 42:2','Ef 1:11']],
['rm',8,38,'Nada nos separara do amor de Deus','A seguranca eterna do crente.',[['Calvino','reforma','reformada','Invencibilidade do amor divino.','Comentario aos Romanos',1551],['Spurgeon','moderno','bautista','Nem morte, nem vida, nem poder algum.','Sermons',1870],['Agostinho','patristico','catolica','Amor que nenhum inimigo pode romper.','Sermoens',410]],['Ef 3:18-19','1 P 1:3-5']],
['rm',12,1,'Apresentai os vossos corpos em sacrificio vivo','O culto vivo e racional.',[['Calvino','reforma','reformada','Sacrificio agradavel: vida santa.','Comentario aos Romanos',1551],['John Stott','contemporaneo','evangelical','Culto e a totalidade da vida dedicada.','The Message of Romans',1994]],['1 P 2:5','He 13:15-16']],
['rm',12,2,'Nao vos conformai','Transformacao pela renovacao da mente.',[['Calvino','reforma','reformada','A mente renovada discernir a vontade de Deus.','Comentario aos Romanos',1551],['R.C. Sproul','contemporaneo','reformada','Cosmovisao cristã versus cultura secular.','The Holiness of God',1985]],['Ef 4:22-24','Cl 3:10']],
['rm',13,1,'Sujeitai-vos a toda autoridade humana','A obediencia as autoridades.',[['Calvino','reforma','reformada','A autoridade civil e instituida por Deus.','Comentario aos Romanos',1551],['Tomas de Aquino','medieval','catolica','O poder civil e necessario para a ordem social.','Suma Teologica',1274]],['1 P 2:13-17','Tt 3:1']],
['rm',14,17,'O reino de Deus nao e comida nem bebida','A essencia do reino.',[['Calvino','reforma','reformada','O reino e justica, paz e alegria no Esprito Santo.','Comentario aos Romanos',1551],['Wesley','moderno','arminiana','O reino de Deus e interior e espiritual.','Sermoens',1750]],['Gl 5:22-23','1 Co 4:20']],
].forEach(e => addE(...e));
// 1 CORINTHIOS
content += '// ====================================================================\n// 1 CORINTHIOS\n// ====================================================================\n\n';
[
['1co',1,18,'A palavra da cruz e loucura','A cruz como poder de Deus.',[['Lutero','reforma','luterana','O que parece loucura e sabedoria suprema.','Comentario aos Galatas',1535],['Calvino','reforma','reformada','O evangelho transcende a razao humana.','Comentario a 1 Corintios',1551],['Barth','contemporaneo','reformada','O escandalo da cruz desafia toda cultura.','Church Dogmatics',1951]],['Gl 6:14','1 Co 2:14']],
['1co',2,9,'Olho nao viu, ouvido nao ouviu','As coisas preparadas por Deus.',[['Calvino','reforma','reformada','Deus prepara coisas inimaginaveis.','Comentario a 1 Corintios',1551],['Spurgeon','moderno','bautista','O ceu supera toda expectativa.','Sermons',1870]],['Is 64:4','Rm 8:28']],
['1co',3,16,'Vós sois o templo de Deus','A igreja como templo.',[['Calvino','reforma','reformada','Deus habita no meio dos crentes.','Comentario a 1 Corintios',1551],['Tomas de Aquino','medieval','catolica','O templo espiritual e a igreja.','Suma Teologica',1274]],['2 Co 6:16','Ef 2:20-22']],
['1co',6,19,'O vosso corpo e templo do Esprito Santo','A santidade do corpo.',[['Calvino','reforma','reformada','O corpo e morada do Esprito.','Comentario a 1 Corintios',1551],['Tomas de Aquino','medieval','catolica','A pureza corporal e necessidade espiritual.','Suma Teologica',1274]],['Rm 12:1','1 Ts 4:3-4']],
['1co',10,13,'Nenhuma tentacao vos sobreveio','A fidelidade de Deus na provacao.',[['Calvino','reforma','reformada','Deus limita a tentacao e da saida.','Comentario a 1 Corintios',1551],['Wesley','moderno','arminiana','A graça capacita a resistir.','Sermoens',1750],['Spurgeon','moderno','bautista','Deus e fiel: sempre ha escapatória.','Sermons',1870]],['1 Co 10:6-13','Tg 1:2-4']],
['1co',13,4,'O amor e paciente, o amor e bondoso','O hino ao amor.',[['Agostinho','patristico','catolica','O amor e o vinculo das virtudes.','Tratados sobre 1 Joao',420],['Tomas de Aquino','medieval','catolica','A caridade e a rainha das virtudes.','Suma Teologica',1274],['Calvino','reforma','reformada','Sem amor, os dons sao vaos.','Comentario a 1 Corintios',1551],['Tim Keller','contemporaneo','reformada','O amor e sacrificio, nao sentimento.','The Meaning of Marriage',2011]],['1 Jo 4:7-8','Gl 5:22-23']],
['1co',15,3,'Cristo morreu por nossos pecados','O evangelho resumido.',[['Calvino','reforma','reformada','Tradicao apostolica central.','Comentario a 1 Corintios',1551],['R.C. Sproul','contemporaneo','reformada','O kerigma apostolico.','The Heart of the Gospel',2003]],['Rm 4:25','1 Co 15:14-17']],
['1co',15,55,'Onde esta, oh morte, o teu aguilhao?','A vitoria final sobre a morte.',[['Calvino','reforma','reformada','A morte e destruida pela ressurreicao.','Comentario a 1 Corintios',1551],['N.T. Wright','contemporaneo','reformada','A vitoria e de Cristo.','The Resurrection of the Son of God',2003],['Agostinho','patristico','catolica','A morte engolida na vitoria.','Sermoens',410]],['Os 13:14','1 Co 15:54-57']],
].forEach(e => addE(...e));
// 2 CORINTHIOS
content += '// ====================================================================\n// 2 CORINTHIOS\n// ====================================================================\n\n';
[
['2co',4,5,'Nao nos pregamos a nos mesmos, mas a Cristo','A pregação apostolica.',[['Calvino','reforma','reformada','O foco e Cristo, nao o pregador.','Comentario a 2 Corintios',1551],['Spurgeon','moderno','bautista','O evangelho e sobre Cristo, nao sobre nos.','Sermons',1870]],['1 Co 2:2','Gl 6:14']],
['2co',5,17,'Se alguem esta em Cristo, nova criatura e','A regeneracao em Cristo.',[['Calvino','reforma','reformada','O antigo passou, o novo comecou.','Comentario a 2 Corintios',1551],['Lutero','reforma','luterana','De velho homem a nova criatura pela fe.','Comentario a Galatas',1535],['Tim Keller','contemporaneo','reformada','Identidade transformada pelo evangelho.','The Reason for God',2008]],['Ef 2:10','Gl 6:15']],
['2co',5,21,'Aquele que nao conheceu pecado, por nos se fez pecado','A imputacao da justica.',[['Lutero','reforma','luterana','A grande troca: pecado por justica.','Comentario a Galatas',1535],['Calvino','reforma','reformada','Justica alienada: a de Cristo nos e creditada.','Comentario a 2 Corintios',1551],['N.T. Wright','contemporaneo','reformada','A justica de Deus e dada em Cristo.','Justification',2009]],['Is 53:5-6','Fp 3:9']],
['2co',12,9,'Minha graça te basta','A suficiencia da graça na fraqueza.',[['Spurgeon','moderno','bautista','Na fraqueza, a perfeicao de Cristo se manifesta.','Sermons',1870],['Calvino','reforma','reformada','A graça divina supre a insuficiencia humana.','Comentario a 2 Corintios',1551],['Wesley','moderno','arminiana','Dependencia total da graça.','Sermoens',1750]],['Fp 4:13','2 Co 4:7']],
].forEach(e => addE(...e));
// GALATAS
content += '// ====================================================================\n// GALATAS\n// ====================================================================\n\n';
[
['gl',2,16,'Sabemos que o homem nao e justificado','A Reforma em um versiculo.',[['Lutero','reforma','luterana','A pedra angular da Reforma: sola fide.','Comentario a Galatas',1535],['Calvino','reforma','reformada','Fe como instrumento de recebimento.','Comentario a Galatas',1548],['N.T. Wright','contemporaneo','reformada','A fe como confianca leal em Deus.','Justification',2009]],['Rm 3:28','Ef 2:8-9']],
['gl',2,20,'Cristo vive em mim','A vida vivida pela fe.',[['Lutero','reforma','luterana','A vida cristã e Cristo vivendo em nos.','Comentario a Galatas',1535],['Wesley','moderno','arminiana','A graça que transforma a vida.','Sermoens',1750],['Calvino','reforma','reformada','Morta a autoconfianca, Cristo governa.','Comentario a Galatas',1548]],['Jo 15:5','Fp 1:21']],
['gl',5,22,'O fruto do Esprito e','Os frutos do Esprito na vida do crente.',[['Wesley','moderno','arminiana','Santificacao progressiva produz fruto.','Sermoens',1750],['Tomas de Aquino','medieval','catolica','As virtudes teologais e morais.','Suma Teologica',1274],['Calvino','reforma','reformada','O Esprito produz o que a lei nao consegue.','Comentario a Galatas',1548]],['Mt 7:16-20','Ef 5:9']],
].forEach(e => addE(...e));
// EPHESIANS
content += '// ====================================================================\n// EFESIOS\n// ====================================================================\n\n';
[
['ef',2,8,'Por graça sois salvos','A salvacao como dom de Deus.',[['Lutero','reforma','luterana','Graça e desmerecida, graça e suficiente.','Comentario aos Romanos',1515],['Calvino','reforma','reformada','A fe e dom, nao merito.','Comentario a Efesios',1548],['Tim Keller','contemporaneo','reformada','Nao por obras para que ninguem se glorie.','The Reason for God',2008]],['Rm 3:24','Tt 3:5']],
['ef',2,10,'Somos feitura dele, criados em Cristo Jesus','A salvacao prepara para a santificacao.',[['Calvino','reforma','reformada','Deus preparou as obras que devemos andar.','Comentario a Efesios',1548],['Wesley','moderno','arminiana','Salvacao produz santidade.','Sermoens',1750],['N.T. Wright','contemporaneo','reformada','A graça antecipa a obra boa.','After You Believe',2010]],['Tg 2:14-17','Mt 5:16']],
['ef',6,10,'No demais, irmãos meus, fortalecei-vos no Senhor','A armadura de Deus.',[['Calvino','reforma','reformada','A guerra espiritual requer preparacao divina.','Comentario a Efesios',1548],['John Stott','contemporaneo','evangelical','A armadura e Cristo mesmo.','The Message of Ephesians',1979],['Spurgeon','moderno','bautista','O crente nao luta pela vitoria, mas da vitoria.','Sermons',1870]],['2 Co 10:3-5','Rm 13:12']],
].forEach(e => addE(...e));
// COLOSSIANS
content += '// ====================================================================\n// COLOSSIENS\n// ====================================================================\n\n';
[
['cl',1,15,'A imagem do Deus invisivel','A supremacia de Cristo.',[['Atanasio','patristico','catolica','O Filho e imagem perfeita do Pai.','Contra Arios',318],['Tomas de Aquino','medieval','catolica','Primogenito de toda a criacao.','Suma Teologica',1274],['Barth','contemporaneo','reformada','Cristo e o comeco e o centro.','Church Dogmatics',1951]],['Jo 1:1-3','He 1:3']],
['cl',2,9,'Nele habita toda a plenitude da divindade','A plenitude da divindade em Cristo.',[['Atanasio','patristico','catolica','Toda a divindade habita corporalmente.','Contra Arios',318],['Calvino','reforma','reformada','Plenitude divina para a salvacao dos fieis.','Comentario a Colossenses',1548]],['Jo 1:14','Cl 1:19']],
['cl',3,1,'Buscai as coisas la de cima','A vida centrada nas realidades eternas.',[['Calvino','reforma','reformada','Mentes elevadas para as coisas celestiais.','Comentario a Colossenses',1548],['Tomas de Aquino','medieval','catolica','O amor pelas coisas eternas eleva a alma.','Suma Teologica',1274]],['Rm 8:5-6','Ef 2:6']],
].forEach(e => addE(...e));
// 1 THESSALONICENSES
content += '// ====================================================================\n// 1 TESSALONICENSES\n// ====================================================================\n\n';
[
['1ts',4,16,'O Senhor desecera dos ceus','A segunda vinda de Cristo.',[['Calvino','reforma','reformada','Visivel, audivel, glorioso.','Comentario a 1 Tessalonicenses',1551],['N.T. Wright','contemporaneo','reformada','A vindicacao final de Deus.','The New Testament and the People of God',1992]],['Mt 24:30-31','Ap 1:7']],
['1ts',5,16,'Regozijai-vos sempre','A alegria cristã permanente.',[['Calvino','reforma','reformada','Alegria como fruto do Esprito.','Comentario a 1 Tessalonicenses',1551],['Wesley','moderno','arminiana','Alegria nao depende de circunstancias.','Sermoens',1750]],['Fp 4:4','Gl 5:22']],
].forEach(e => addE(...e));
// 1-2 TIMOTEO, TITO
content += '// ====================================================================\n// 1 TIMOTEO, 2 TIMOTEO, TITO\n// ====================================================================\n\n';
[
['1tm',2,5,'Porque ha um so Deus, e tambem um so mediador','A unica mediação de Cristo.',[['Calvino','reforma','reformada','Cristo e o unico mediador.','Comentario a 1 Timoteo',1549],['Tomas de Aquino','medieval','catolica','A mediação de Cristo e unica e suficiente.','Suma Teologica',1274]],['Jo 14:6','He 9:15']],
['2tm',3,16,'Toda Escritura e inspirada por Deus','A doutrina da inspiração biblica.',[['Lutero','reforma','luterana','A Palavra de Deus e a autoridade suprema.','Disputas',1521],['Calvino','reforma','reformada','Autoridade, inerrancia e suficiencia da Escritura.','Institutas',1536],['R.C. Sproul','contemporaneo','reformada','A Escritura e o padrao inerrante.','Scripture Alone',2005],['John Stott','contemporaneo','evangelical','Util para ensinar, corrigir, instruir.','The Message of 2 Timothy',1973]],['2 P 1:20-21','Sl 119:89']],
['tt',2,11,'A graça de Deus se manifestou','A graça salvadora e transformadora.',[['Wesley','moderno','arminiana','A graça que ensina negar a impiedade.','Sermoens',1750],['Calvino','reforma','reformada','Graça instrutiva e salvadora.','Comentario a Tito',1549]],['Ef 2:8-9','Tg 2:14-17']],
].forEach(e => addE(...e));
// HEBREUS
content += '// ====================================================================\n// HEBREUS\n// ====================================================================\n\n';
[
['hb',1,1,'Deus falou, antigamente, por meio dos profetas','A revelacao suprema em Cristo.',[['Calvino','reforma','reformada','O Filho e a Palavra final de Deus.','Comentario aos Hebreus',1551],['Tomas de Aquino','medieval','catolica','A supremacia do Filho sobre os profetas.','Suma Teologica',1274],['Barth','contemporaneo','reformada','Deus se revela plenamente em Cristo.','Church Dogmatics',1951]],['Jo 1:1-3','Cl 1:15-17']],
['hb',4,12,'A palavra de Deus e viva e eficaz','O poder penetrante da Escritura.',[['Lutero','reforma','luterana','A Palavra que corta, cura e converte.','Sermoens',1530],['Calvino','reforma','reformada','Mais afiada que espada de dois gumes.','Comentario aos Hebreus',1551],['R.C. Sproul','contemporaneo','reformada','Eficacia da Escritura na vida humana.','Scripture Alone',2005]],['2 Tm 3:16-17','Sl 119:105']],
['hb',4,14,'Temos um grande sumo sacerdote','A intercessao de Cristo.',[['Tomas de Aquino','medieval','catolica','Cristo e Sumo Sacerdote eterno.','Suma Teologica',1274],['Calvino','reforma','reformada','Intercede por nos no ceu.','Comentario aos Hebreus',1551]],['Hb 7:25','1 Jo 2:1']],
['hb',7,25,'Sempre vive para interceder','A intercessao perene de Cristo.',[['Calvino','reforma','reformada','A intercessao e a garantia da salvacao.','Comentario aos Hebreus',1551],['Tomas de Aquino','medieval','catolica','Sumo Sacerdote que nao morre.','Suma Teologica',1274]],['Rm 8:34','Hb 4:14-16']],
['hb',9,12,'Com o seu proprio sangue','O sacrificio unico e eterno.',[['Calvino','reforma','reformada','Sacrificio uma vez para sempre.','Comentario aos Hebreus',1551],['Lutero','reforma','luterana','Sangue precioso, expiacao eterna.','Sermoens',1530]],['Lv 16:2-34','1 P 1:18-19']],
['hb',11,1,'A fe e o firme fundamento','A definicao classica de fe.',[['Calvino','reforma','reformada','Conviccao das coisas nao vistas.','Comentario aos Hebreus',1551],['Tomas de Aquino','medieval','catolica','O ato da fe como assentimento da razao.','Suma Teologica',1274],['Barth','contemporaneo','reformada','A fe e resposta a revelacao.','Church Dogmatics',1951]],['2 Co 4:18','Rm 8:24-25']],
['hb',12,2,'Olhando para Jesus','Jesus como autor e consumador da fe.',[['Calvino','reforma','reformada','O exemplo supremo de perseveranca.','Comentario aos Hebreus',1551],['Spurgeon','moderno','bautista','Olhando para Jesus, nao para as circunstancias.','Sermons',1870]],['Fp 3:13-14','12:1-2']],
['hb',13,8,'Jesus Cristo e o mesmo ontem, e sempre','A imutabilidade de Cristo.',[['Calvino','reforma','reformada','Cristo nao muda, por isso a fe e segura.','Comentario aos Hebreus',1551],['Tomas de Aquino','medieval','catolica','A imutabilidade divina e garantia da alianca.','Suma Teologica',1274],['Spurgeon','moderno','bautista','O mesmo ontem, hoje e sempre.','Sermons',1870]],['Ml 3:6','Tg 1:17']],
].forEach(e => addE(...e));
// JAMES
content += '// ====================================================================\n// TIAGO\n// ====================================================================\n\n';
[
['tg',1,2,'Tende por grande alegria','A alegria na provacao.',[['Calvino','reforma','reformada','Tribulacoes produzem perseveranca.','Comentario a Tiago',1548],['Tomas de Aquino','medieval','catolica','A provacao aperfeicoa a virtude.','Suma Teologica',1274]],['Rm 5:3-5','1 P 1:6-7']],
['tg',2,14,'Que aproveita, se alguem disser que tem fe','Fé sem obras e morta.',[['Tomas de Aquino','medieval','catolica','A fe que nao e inutil.','Suma Teologica',1274],['Lutero','reforma','luterana','A fe viva produz obras.','Comentario a Tiago',1522],['Calvino','reforma','reformada','A fe genuina se demonstra em acao.','Comentario a Tiago',1548],['John Stott','contemporaneo','evangelical','Fe e obras sao inseparaveis.','The Message of James',1979]],['Gl 2:16','Ef 2:8-10']],
].forEach(e => addE(...e));
// 1 PETER
content += '// ====================================================================\n// 1 PEDRO\n// ====================================================================\n\n';
[
['1p',2,9,'Vós sois geração eleita, sacerdocio real','A identidade do povo de Deus.',[['Calvino','reforma','reformada','Sacerdocio real, nacao santa.','Comentario a 1 Pedro',1551],['Tomas de Aquino','medieval','catolica','Sacerdocio espiritual de todos os fieis.','Suma Teologica',1274],['N.T. Wright','contemporaneo','reformada','Povo peculiar para proclamar virtudes.','The New Testament and the People of God',1992]],['Ex 19:6','Ap 1:6']],
['1p',3,15,'Estai sempre preparados para responder','A defesa da fe com mansidao.',[['Calvino','reforma','reformada','Defesa racional com mansidao e respeito.','Comentario a 1 Pedro',1551],['John Stott','contemporaneo','evangelical','Apologética com humildade.','Issues Facing Christians Today',1990]],['2 Tm 2:24-26','Cl 4:5-6']],
].forEach(e => addE(...e));
// 1 JOHN
content += '// ====================================================================\n// 1 JOAO\n// ====================================================================\n\n';
[
['1jo',1,9,'Se confessarmos os nossos pecados','O perdao mediante a confissao.',[['Agostinho','patristico','catolica','Deus e fiel e justo para perdoar.','Tratados sobre 1 Joao',420],['Calvino','reforma','reformada','Confissao e perdao seguro pela fidelidade divina.','Comentario a 1 Joao',1551],['R.C. Sproul','contemporaneo','reformada','A justica de Deus garante o perdao.','The Holiness of God',1985]],['Sl 32:5','1 Jo 2:1-2']],
['1jo',4,8,'Deus e amor','O amor como essencia divina.',[['Agostinho','patristico','catolica','Deus e amor em Si mesmo.','Tratados sobre 1 Joao',420],['Tomas de Aquino','medieval','catolica','O amor e a causa final da criacao.','Suma Teologica',1274],['Calvino','reforma','reformada','O amor se manifesta na cruz.','Comentario a 1 Joao',1551],['Barth','contemporaneo','reformada','Deus e amor: ponto de partida.','Church Dogmatics',1951]],['Jo 3:16','1 Jo 4:16']],
['1jo',4,19,'Nós o amamos porque ele nos amou primeiro','O amor como resposta ao amor divino.',[['Agostinho','patristico','catolica','Amamos porque fomos amados primeiro.','Tratados sobre 1 Joao',420],['Calvino','reforma','reformada','O amor precede o nosso.','Comentario a 1 Joao',1551],['Wesley','moderno','arminiana','A graça desperta o amor no coracao.','Sermoens',1750]],['Ef 2:4-5','1 Jo 4:9-10']],
].forEach(e => addE(...e));
// REVELATION
content += '// ====================================================================\n// APOCALIPSE\n// ====================================================================\n\n';
[
['ap',1,7,'Eis que vem com as nuvens','A segunda vinda visivel.',[['Calvino','reforma','reformada','Todo o mundo O vera.','Comentario ao Apocalipse',1555],['N.T. Wright','contemporaneo','reformada','Vindicacao final de Deus.','The New Testament and the People of God',1992]],['Mt 24:30','Dn 7:13','Zc 12:10']],
['ap',1,8,'Eu sou o Alfa e o Omega','A eternidade de Deus.',[['Tomas de Aquino','medieval','catolica','Deus e o inicio e o fim.','Suma Teologica',1274],['Calvino','reforma','reformada','A soberania absoluta de Deus.','Comentario ao Apocalipse',1555]],['Is 44:6','Ex 3:14']],
['ap',3,20,'Eis que estou a porta e bato','O convite pessoal de Cristo.',[['Calvino','reforma','reformada','Cristo bate, mas nao entra a forca.','Comentario ao Apocalipse',1555],['Spurgeon','moderno','bautista','A porta so se abre de dentro.','Sermons',1870],['Tim Keller','contemporaneo','reformada','O convite e urgente e pessoal.','King Cross',2011]],['Lc 13:25','Mt 25:1-13']],
['ap',5,9,'Tu foste morto, e com o teu sangue','Digno e o Cordeiro.',[['Tomas de Aquino','medieval','catolica','O Cordeiro sacrificado e adorado.','Suma Teologica',1274],['Calvino','reforma','reformada','So Cristo e digno de adoracao.','Comentario ao Apocalipse',1555]],['Jo 1:29','Fl 2:9-11']],
['ap',7,9,'Uma grande multidao de todas as nacoes','A igreja triunfante.',[['Agostinho','patristico','catolica','A cidade de Deus de todas as nacoes.','A Cidade de Deus',426],['Calvino','reforma','reformada','Multidao inumeravel.','Comentario ao Apocalipse',1555]],['Ap 5:9-10','Mt 28:19']],
['ap',19,16,'Rei dos reis e Senhor dos senhores','A soberania absoluta de Cristo.',[['Calvino','reforma','reformada','Cristo reina sobre todas as nacoes.','Comentario ao Apocalipse',1555],['Tomas de Aquino','medieval','catolica','Toda a autoridade lhe foi dada.','Suma Teologica',1274],['N.T. Wright','contemporaneo','reformada','O rei vitorioso.','The New Testament and the People of God',1992]],['Mt 28:18','Fl 2:9-11']],
['ap',21,1,'Novos ceus e nova terra','A renovacao de toda a criacao.',[['Calvino','reforma','reformada','A criacao renovada, nao destruida.','Comentario ao Apocalipse',1555],['N.T. Wright','contemporaneo','reformada','A restauracao cosmica.','Surprised by Hope',2008],['Tomas de Aquino','medieval','catolica','A gloria da nova criacao.','Suma Teologica',1274]],['Is 65:17','2 P 3:13']],
['ap',21,4,'Enxugara todas as lagrimas','A ausencia final da dor.',[['Agostinho','patristico','catolica','A felicidade perfeita dos santos.','A Cidade de Deus',426],['Spurgeon','moderno','bautista','Sem mais morte, luto, dor.','Sermons',1870],['Tim Keller','contemporaneo','reformada','A esperanca final da criacao.','Walking with God',2013]],['Is 25:8','1 Co 15:54-55']],
['ap',22,20,'Sim, vem, Senhor Jesus','A oracao escatologica da igreja.',[['Calvino','reforma','reformada','A Maranatha: vem, Senhor Jesus.','Comentario ao Apocalipse',1555],['Spurgeon','moderno','bautista','Suspiro final da historia.','Sermons',1870],['N.T. Wright','contemporaneo','reformada','O clamor pela consumacao.','Surprised by Hope',2008]],['1 Co 16:22','Mt 24:42']],
].forEach(e => addE(...e));
content += '\n// ====================================================================\n// EXPORTACAO\n// ====================================================================\n\n';
content += 'export default comentariosNovos;\nexport { comentariosNovos };\n';
fs.writeFileSync(outFile, content, 'utf8');
const count = (content.match(/add\(/g) || []).length;
console.log('Total entries: ' + count);
