const fs = require('fs');
const path = 'C:\\Sola Scriptura BR\\src\\data\\lexicon\\grego.ts';

const entries = [];
function a(s,p,t,d,m,f){entries.push([s,p,t,d,m,f]);}

// EXISTING ENTRIES (preserved from original)
a('G26','ἀγάπη','agape','Amor incondicional, amor divino, amor sacrificial.','Substantivo, feminino, nominativo, singular',116);
a('G25','ἀγαπάω','agapao','Amar, ter afeição por, amar incondicionalmente.','Verbo, presente, ativo, infinitivo',143);
a('G32','ἄγγελος','angelos','Mensageiro, anjo.','Substantivo, masculino, nominativo, singular',176);
a('G40','ἅγιος','hagios','Santo, sagrado, consagrado a Deus.','Adjetivo, masculino, nominativo, singular',233);
a('G41','ἁγιασμός','hagiasmos','Santificação, consagração.','Substantivo, masculino, nominativo, singular',10);
a('G80','ἀδελφός','adelphos','Irmão, membro da comunidade de fé.','Substantivo, masculino, nominativo, singular',343);
a('G126','αἷμα','haima','Sangue, derramamento de sangue, redenção.','Substantivo, neutro, nominativo, singular',99);
a('G165','αἰών','aion','Época, era, eternidade, mundo.','Substantivo, masculino, nominativo, singular',122);
a('G166','αἰώνιος','aionios','Eterno, perpétuo, sem fim.','Adjetivo, masculino, nominativo, singular',71);
a('G225','ἀλήθεια','aletheia','Verdade, realidade, sinceridade.','Substantivo, feminino, nominativo, singular',109);
a('G227','ἀληθής','alethes','Verdadeiro, genuíno, real.','Adjetivo, masculino, nominativo, singular',26);
a('G228','ἀληθινός','alethinos','Verdadeiro, genuíno, autêntico.','Adjetivo, masculino, nominativo, singular',28);
a('G242','ἁλληλουϊά','allelouia','Aleluia! Louvai ao SENHOR!','Interjeição, indeclinável');
a('G243','ἄλλος','allos','Outro, diferente, distinto.','Adjetivo, masculino, nominativo, singular',155);
a('G264','ἁμαρτάνω','hamartano','Pecar, errar o alvo, transgredir.','Verbo, presente, ativo, infinitivo',43);
a('G266','ἁμαρτία','hamartia','Pecado, transgressão, erro.','Substantivo, feminino, nominativo, singular',173);
a('G268','ἁμαρτωλός','hamartolos','Pecador, transgressor, ímpio.','Adjetivo, masculino, nominativo, singular',47);
a('G281','ἀμήν','amen','Amém, em verdade, assim seja.','Advérbio, indeclinável',129);
a('G286','ἀμνός','amnos','Cordeiro. Cordeiro de Deus.','Substantivo, masculino, nominativo, singular',4);
a('G314','ἀναγινώσκω','anaginosko','Ler, conhecer ao ler.','Verbo, presente, ativo, infinitivo',33);
a('G356','ἀναλογία','analogia','Proporção, analogia.','Substantivo, feminino, nominativo, singular');
a('G386','ἀνάστασις','anastasis','Ressurreição, levantar-se dos mortos.','Substantivo, feminino, nominativo, singular',42);
a('G459','ἄνομος','anomos','Sem lei, ímpio, transgressor.','Adjetivo, masculino, nominativo, singular',10);
a('G602','ἀποκάλυψις','apokalypsis','Revelação, manifestação, descobrimento.','Substantivo, feminino, nominativo, singular',18);
a('G622','ἀπόλλυμι','apollymi','Destruir, perder, arruinar, perecer.','Verbo, presente, ativo, infinitivo',90);
a('G650','ἀποστερέω','apostereo','Privar, defraudar, roubar.','Verbo, presente, ativo, infinitivo');
a('G652','ἀπόστολος','apostolos','Apóstolo, enviado, mensageiro comissionado.','Substantivo, masculino, nominativo, singular',80);
a('G726','ἁρπάζω','harpazo','Arrebatar, tomar à força.','Verbo, presente, ativo, infinitivo',14);
a('G743','ἄρχων','archon','Governante, príncipe, líder, autoridade.','Substantivo, masculino, nominativo, singular');
a('G746','ἀρχή','arche','Princípio, começo, origem, governante.','Substantivo, feminino, nominativo, singular',55);
a('G749','ἀρχιερεύς','archiereus','Sumo sacerdote.','Substantivo, masculino, nominativo, singular',122);
a('G859','ἄφεσις','aphesis','Perdão, remissão, libertação.','Substantivo, feminino, nominativo, singular',17);
a('G906','βάλλω','ballo','Lançar, atirar, colocar, deitar.','Verbo, presente, ativo, infinitivo',122);
a('G907','βαπτίζω','baptizo','Batizar, imergir, submergir.','Verbo, presente, ativo, infinitivo',77);
a('G908','βάπτισμα','baptisma','Batismo, imersão, processo de batizar.','Substantivo, neutro, nominativo, singular',22);
a('G932','βασιλεία','basileia','Reino, domínio, reinado, soberania.','Substantivo, feminino, nominativo, singular',162);
a('G935','βασιλεύς','basileus','Rei, soberano, monarca.','Substantivo, masculino, nominativo, singular',115);
a('G936','βασιλεύω','basileuo','Reinar, governar, exercer domínio.','Verbo, presente, ativo, infinitivo',21);
a('G976','βίβλος','biblos','Livro, rolo, registro escrito.','Substantivo, feminino, nominativo, singular');
a('G978','βίος','bios','Vida, existência, meios de subsistência.','Substantivo, masculino, nominativo, singular');
a('G998','βοηθός','boethos','Ajudador, socorredor, auxiliador.','Substantivo, masculino, nominativo, singular');
a('G1063','γάρ','gar','Porque, pois, visto que.','Conjunção, indeclinável',1041);
a('G1080','γεννάω','gennao','Gerar, dar à luz, produzir.','Verbo, presente, ativo, infinitivo',97);
a('G1097','γινώσκω','ginosko','Conhecer, saber, entender, experimentar.','Verbo, presente, ativo, infinitivo',222);
a('G1100','γλῶσσα','glossa','Língua, idioma, linguagem.','Substantivo, feminino, nominativo, singular',50);
a('G1108','γνῶσις','gnosis','Conhecimento, entendimento espiritual.','Substantivo, feminino, nominativo, singular',29);
a('G1121','γραφή','graphe','Escritura, texto sagrado.','Substantivo, feminino, nominativo, singular',51);
a('G1122','γραμματεύς','grammateus','Escriba, doutor da lei.','Substantivo, masculino, nominativo, singular',66);
a('G1147','δάκτυλος','daktylos','Dedo. O dedo de Deus.','Substantivo, masculino, nominativo, singular');
a('G1161','δέ','de','Mas, porém, e, agora.','Conjunção, indeclinável',2792);
a('G1203','δεσπότης','despotes','Senhor, mestre, soberano.','Substantivo, masculino, nominativo, singular');
a('G1209','δέχομαι','dechomai','Receber, aceitar, dar as boas-vindas.','Verbo, presente, médio, infinitivo',56);
a('G1210','δέω','deo','Ligar, amarrar, prender.','Verbo, presente, ativo, infinitivo',43);
a('G1223','διά','dia','Por meio de, através de, por causa de.','Preposição, indeclinável',667);
a('G1242','διαθήκη','diatheke','Aliança, pacto, testamento.','Substantivo, feminino, nominativo, singular',33);
a('G1250','διάκονος','diakonos','Servo, ministro, diácono.','Substantivo, masculino, nominativo, singular',29);
a('G1321','διδάσκαλος','didaskalos','Mestre, professor, instrutor.','Substantivo, masculino, nominativo, singular',59);
a('G1322','διδαχή','didache','Doutrina, ensino, instrução.','Substantivo, feminino, nominativo, singular',30);
a('G1343','δικαιοσύνη','dikaiosyne','Justiça, retidão, justificação.','Substantivo, feminino, nominativo, singular',92);
a('G1344','δικαιόω','dikaioo','Justificar, declarar justo.','Verbo, presente, ativo, infinitivo',39);
a('G1391','δόξα','doxa','Glória, honra, majestade, esplendor.','Substantivo, feminino, nominativo, singular',166);
a('G1392','δοξάζω','doxazo','Glorificar, honrar, exaltar.','Verbo, presente, ativo, infinitivo',61);
a('G1411','δύναμις','dynamis','Poder, capacidade, força, milagre.','Substantivo, feminino, nominativo, singular',119);
a('G1415','δυνατός','dynatos','Poderoso, capaz, forte, possível.','Adjetivo, masculino, nominativo, singular',32);
a('G1484','ἔθνος','ethnos','Nação, povo, gentios.','Substantivo, neutro, nominativo, singular',162);
a('G1487','εἰ','ei','Se, caso. Partícula condicional.','Conjunção, indeclinável',502);
a('G1492','εἴδω','eido','Ver, saber, conhecer, perceber.','Verbo, perfeito, ativo, infinitivo',255);
a('G1515','εἰρήνη','eirene','Paz, harmonia, tranquilidade.','Substantivo, feminino, nominativo, singular',92);
a('G1520','εἷς','heis','Um, único, um só.','Adjetivo, numeral, masculino, nominativo, singular',344);
a('G1537','ἐκ','ek','De, desde, fora de, dentre.','Preposição, indeclinável',914);
a('G1544','ἐκβάλλω','ekballo','Lançar fora, expulsar.','Verbo, presente, ativo, infinitivo',81);
a('G1577','ἐκκλησία','ekklesia','Igreja, assembleia, congregação.','Substantivo, feminino, nominativo, singular',114);
a('G1588','ἐκλεκτός','eklektos','Eleito, escolhido.','Adjetivo, masculino, nominativo, singular',22);
a('G1651','ἐλέγχω','elencho','Convencer, repreender, expor, refutar.','Verbo, presente, ativo, infinitivo',17);
a('G1656','ἔλεος','eleos','Misericórdia, compaixão, benignidade.','Substantivo, neutro, nominativo, singular',27);
a('G1679','ἐλπίζω','elpizo','Esperar, ter esperança, confiar.','Verbo, presente, ativo, infinitivo',31);
a('G1680','ἐλπίς','elpis','Esperança, expectativa, confiança.','Substantivo, feminino, nominativo, singular',53);
a('G1722','ἐν','en','Em, dentro de, entre, por meio de.','Preposição, indeclinável',2752);
a('G1781','ἐντολή','entole','Mandamento, ordem, preceito.','Substantivo, feminino, nominativo, singular',67);
a('G1799','ἐνώπιον','enopion','Diante de, perante, na presença de.','Preposição, indeclinável',93);
a('G1831','ἐξέρχομαι','exerchomai','Sair, partir, vir para fora.','Verbo, presente, médio, infinitivo',218);
a('G1849','ἐξουσία','exousia','Autoridade, poder, direito, jurisdição.','Substantivo, feminino, nominativo, singular',102);
a('G1854','ἔξω','exo','Fora, do lado de fora.','Advérbio, indeclinável');
a('G1909','ἐπί','epi','Sobre, em, contra, por, perante.','Preposição, indeclinável',890);
a('G1921','ἐπιγινώσκω','epiginosko','Conhecer plenamente, reconhecer.','Verbo, presente, ativo, infinitivo',44);
a('G1922','ἐπίγνωσις','epignosis','Pleno conhecimento, compreensão completa.','Substantivo, feminino, nominativo, singular',20);
a('G1941','ἐπικαλέω','epikaleo','Invocar, apelar, chamar por.','Verbo, presente, ativo, infinitivo',33);
a('G2041','ἔργον','ergon','Obra, trabalho, feito, ação.','Substantivo, neutro, nominativo, singular',169);
a('G2064','ἔρχομαι','erchomai','Vir, ir, chegar, aparecer.','Verbo, presente, médio, infinitivo',634);
a('G2076','ἐστί','esti','É, está.','Verbo, presente, ativo, 3ª singular',2462);
a('G2097','εὐαγγελίζω','euangelizo','Evangelizar, anunciar boas novas.','Verbo, presente, ativo, infinitivo',54);
a('G2098','εὐαγγέλιον','euangelion','Evangelho, boas novas da salvação.','Substantivo, neutro, nominativo, singular',76);
a('G2127','εὐλογέω','eulogeo','Abençoar, bendizer, louvar.','Verbo, presente, ativo, infinitivo',41);
a('G2129','εὐλογία','eulogia','Bênção, louvor, dom, bondade.','Substantivo, feminino, nominativo, singular',16);
a('G2168','εὐχαριστέω','eucharisteo','Agradecer, dar graças.','Verbo, presente, ativo, infinitivo',38);
a('G2169','εὐχαριστία','eucharistia','Ação de graças, gratidão.','Substantivo, feminino, nominativo, singular');
a('G2192','ἔχω','echo','Ter, possuir, segurar, manter.','Verbo, presente, ativo, infinitivo',707);
a('G2198','ζάω','zao','Viver, estar vivo, ter vida.','Verbo, presente, ativo, infinitivo',140);
a('G2222','ζωή','zoe','Vida, existência. Vida eterna em Cristo.','Substantivo, feminino, nominativo, singular',135);
a('G2250','ἡμέρα','hemera','Dia, período diurno, tempo.','Substantivo, feminino, nominativo, singular',388);
a('G2281','θάλασσα','thalassa','Mar, lago.','Substantivo, feminino, nominativo, singular',91);
a('G2288','θάνατος','thanatos','Morte, separação.','Substantivo, masculino, nominativo, singular',120);
a('G2307','θέλημα','thelema','Vontade, desejo, propósito.','Substantivo, neutro, nominativo, singular',62);
a('G2316','θεός','theos','Deus, o Ser Supremo, Criador.','Substantivo, masculino, nominativo, singular',1317);
a('G2320','θεότης','theotes','Divindade, natureza divina.','Substantivo, feminino, nominativo, singular');
a('G2372','θυμός','thymos','Ira, fúria, indignação.','Substantivo, masculino, nominativo, singular');
a('G2380','θύω','thyo','Sacrificar, imolar, matar para oferta.','Verbo, presente, ativo, infinitivo');
a('G2381','θυσία','thysia','Sacrifício, oferta.','Substantivo, feminino, nominativo, singular',28);
a('G2400','ἰδού','idou','Eis! Vede! Olha!','Partícula, indeclinável',200);
a('G2411','ἱερόν','hieron','Templo, santuário.','Substantivo, neutro, nominativo, singular',71);
a('G2424','Ἰησοῦς','Iesous','Jesus. O SENHOR salva.','Substantivo, masculino, nominativo, singular',975);
a('G2434','ἱλασμός','hilasmos','Propiciação, expiação.','Substantivo, masculino, nominativo, singular');
a('G2443','ἵνα','hina','Para que, a fim de que.','Conjunção, indeclinável',667);
a('G2476','ἵστημι','histemi','Ficar em pé, colocar, estabelecer.','Verbo, presente, ativo, infinitivo',154);
a('G2491','Ἰωάννης','Ioannes','João. O SENHOR é gracioso.','Substantivo, masculino, nominativo, singular',135);
a('G2521','κάθημαι','kathemai','Sentar-se, estar assentado.','Verbo, presente, médio, infinitivo',89);
a('G2523','καθίζω','kathizo','Assentar-se, colocar, designar.','Verbo, presente, ativo, infinitivo');
a('G2525','καθίστημι','kathistemi','Estabelecer, designar, nomear.','Verbo, presente, ativo, infinitivo');
a('G2532','καί','kai','E, também, mesmo, além disso.','Conjunção, indeclinável',8991);
a('G2556','κακός','kakos','Mau, ruim, perverso, maligno.','Adjetivo, masculino, nominativo, singular');
a('G2564','καλέω','kaleo','Chamar, convidar, nomear.','Verbo, presente, ativo, infinitivo',146);
a('G2570','καλός','kalos','Bom, belo, nobre, excelente.','Adjetivo, masculino, nominativo, singular',100);
a('G2588','καρδία','kardia','Coração, centro da vida espiritual.','Substantivo, feminino, nominativo, singular',156);
a('G2596','κατά','kata','Segundo, conforme, contra, por.','Preposição, indeclinável',473);
a('G2758','κενόω','kenoo','Esvaziar-se (kenosis).','Verbo, presente, ativo, infinitivo');
a('G2842','κοινωνία','koinonia','Comunhão, parceria, participação.','Substantivo, feminino, nominativo, singular',19);
a('G2889','κόσμος','kosmos','Mundo, universo, ordem.','Substantivo, masculino, nominativo, singular',186);
a('G2904','κράτος','kratos','Poder, domínio, força, soberania.','Substantivo, neutro, nominativo, singular');
a('G2919','κρίνω','krino','Julgar, decidir, condenar.','Verbo, presente, ativo, infinitivo',114);
a('G2920','κρίσις','krisis','Juízo, julgamento, condenação.','Substantivo, feminino, nominativo, singular',47);
a('G2939','κτίστης','ktistis','Criador, fundador.','Substantivo, masculino, nominativo, singular');
a('G2962','κύριος','kyrios','Senhor, mestre, dono. Título divino.','Substantivo, masculino, nominativo, singular',717);
a('G2992','λαός','laos','Povo.','Substantivo, masculino, nominativo, singular',142);
a('G3000','λατρεύω','latreuo','Servir, adorar, prestar culto.','Verbo, presente, ativo, infinitivo');
a('G3004','λέγω','lego','Dizer, falar, afirmar, declarar.','Verbo, presente, ativo, infinitivo',2353);
a('G3037','λίθος','lithos','Pedra. Cristo é a pedra angular.','Substantivo, masculino, nominativo, singular');
a('G3050','λογικός','logikos','Racional, espiritual.','Adjetivo, masculino, nominativo, singular');
a('G3056','λόγος','logos','Palavra, razão, discurso. O Verbo divino.','Substantivo, masculino, nominativo, singular',330);
a('G3089','λύω','lyo','Desatar, soltar, desligar, destruir.','Verbo, presente, ativo, infinitivo');
a('G3100','μαθητεύω','matheuo','Discipular.','Verbo, presente, ativo, infinitivo');
a('G3101','μαθητής','mathetes','Discípulo, aprendiz, seguidor.','Substantivo, masculino, nominativo, singular',261);
a('G3107','μακάριος','makarios','Bem-aventurado, feliz, abençoado.','Adjetivo, masculino, nominativo, singular',50);
a('G3173','μέγας','megas','Grande, enorme, importante.','Adjetivo, masculino, nominativo, singular',243);
a('G3306','μένω','meno','Permanecer, ficar, habitar.','Verbo, presente, ativo, infinitivo',118);
a('G3316','μεσίτης','mesites','Mediador. Cristo, o único Mediador.','Substantivo, masculino, nominativo, singular');
a('G3326','μετά','meta','Com, depois de, entre.','Preposição, indeclinável',469);
a('G3339','μεταμορφόω','metamorphoo','Transformar, transfigurar.','Verbo, presente, ativo, infinitivo');
a('G3340','μετανοέω','metanoeo','Arrepender-se, mudar de mente.','Verbo, presente, ativo, infinitivo',34);
a('G3341','μετάνοια','metanoia','Arrependimento, mudança de mente.','Substantivo, feminino, nominativo, singular',24);
a('G3361','μή','me','Não, para que não.','Partícula, indeclinável',1042);
a('G3441','μόνος','monos','Único, só, sozinho.','Adjetivo, masculino, nominativo, singular',95);
a('G3466','μυστήριον','mysterion','Mistério, segredo revelado.','Substantivo, neutro, nominativo, singular',28);
a('G3498','νεκρός','nekros','Morto, falecido.','Adjetivo, masculino, nominativo, singular',128);
a('G3528','νικάω','nikao','Vencer, conquistar, superar.','Verbo, presente, ativo, infinitivo');
a('G3551','νόμος','nomos','Lei, princípio. A Lei de Moisés.','Substantivo, masculino, nominativo, singular',194);
a('G3563','νοῦς','nous','Mente, entendimento, intelecto.','Substantivo, masculino, nominativo, singular',24);
a('G3568','νῦν','nyn','Agora, no presente.','Advérbio, indeclinável',149);
a('G3588','ὁ','ho','O, a, os, as. Artigo definido grego.','Artigo, masculino, nominativo, singular',19870);
a('G3598','ὁδός','hodos','Caminho, via.','Substantivo, feminino, nominativo, singular');
a('G3618','οἰκοδομέω','oikodomeo','Edificar, construir.','Verbo, presente, ativo, infinitivo');
a('G3621','οἰκονόμος','oikonomos','Administrador, despenseiro, mordomo.','Substantivo, masculino, nominativo, singular');
a('G3624','οἶκος','oikos','Casa, habitação, família.','Substantivo, masculino, nominativo, singular');
a('G3670','ὁμολογέω','homologeo','Confessar, declarar, professar.','Verbo, presente, ativo, infinitivo');
a('G3686','ὄνομα','onoma','Nome, título.','Substantivo, neutro, nominativo, singular',231);
a('G3708','ὁράω','horao','Ver, perceber, contemplar.','Verbo, presente, ativo, infinitivo',454);
a('G3739','ὅς','hos','Que, o qual, a qual.','Pronome, relativo',1407);
a('G3754','ὅτι','hoti','Que, porque, visto que.','Conjunção, indeclinável',1296);
a('G3756','οὐ','ou','Não (negação objetiva).','Partícula, indeclinável',1606);
a('G3772','οὐρανός','ouranos','Céu, firmamento.','Substantivo, masculino, nominativo, singular',273);
a('G3793','ὄχλος','ochlos','Multidão, turba, povo.','Substantivo, masculino, nominativo, singular');
a('G3841','παντοκράτωρ','pantokrator','Todo-poderoso, onipotente.','Substantivo, masculino, nominativo, singular');
a('G3842','πάντοτε','pantote','Sempre, o tempo todo.','Advérbio, indeclinável',42);
a('G3857','παράδεισος','paradeisos','Paraíso.','Substantivo, masculino, nominativo, singular');
a('G3860','παραδίδωμι','paradidomi','Entregar, transmitir, trair.','Verbo, presente, ativo, infinitivo',119);
a('G3870','παρακαλέω','parakaleo','Exortar, consolar, encorajar.','Verbo, presente, ativo, infinitivo',109);
a('G3875','παράκλητος','parakletos','Consolador, Advogado. O Espírito Santo.','Substantivo, masculino, nominativo, singular');
a('G3900','παράπτωμα','paraptoma','Transgressão, ofensa, queda.','Substantivo, neutro, nominativo, singular',19);
a('G3952','παρουσία','parousia','Vinda, presença. A segunda vinda de Cristo.','Substantivo, feminino, nominativo, singular',24);
a('G3954','παρρησία','parrhesia','Confiança, ousadia, franqueza.','Substantivo, feminino, nominativo, singular');
a('G3956','πᾶς','pas','Todo, toda, tudo, cada.','Adjetivo, masculino, nominativo, singular',1243);
a('G3962','πατήρ','pater','Pai. Deus como Pai.','Substantivo, masculino, nominativo, singular',413);
a('G3972','Παῦλος','Paulos','Paulo. Apóstolo dos gentios.','Substantivo, masculino, nominativo, singular',158);
a('G3985','πειράζω','peirazo','Tentar, provar, pôr à prova.','Verbo, presente, ativo, infinitivo');
a('G3986','πειρασμός','peirasmos','Tentação, prova, teste.','Substantivo, masculino, nominativo, singular');
a('G4100','πιστεύω','pisteuo','Crer, confiar, ter fé.','Verbo, presente, ativo, infinitivo',241);
a('G4102','πίστις','pistis','Fé, confiança, fidelidade.','Substantivo, feminino, nominativo, singular',243);
a('G4103','πιστός','pistos','Fiel, confiável, digno de confiança.','Adjetivo, masculino, nominativo, singular',67);
a('G4105','πλανάω','planao','Desviar, errar, enganar.','Verbo, presente, ativo, infinitivo');
a('G4151','πνεῦμα','pneuma','Espírito, vento, sopro. O Espírito Santo.','Substantivo, neutro, nominativo, singular',379);
a('G4152','πνευματικός','pneumatikos','Espiritual, relativo ao espírito.','Adjetivo, masculino, nominativo, singular',26);
a('G4160','ποιέω','poieo','Fazer, criar, produzir, realizar.','Verbo, presente, ativo, infinitivo',568);
a('G4165','ποιμαίνω','poimaino','Pastorear, apascentar, cuidar do rebanho.','Verbo, presente, ativo, infinitivo');
a('G4183','πολύς','polys','Muito, muitos, numeroso.','Adjetivo, masculino, nominativo, singular',416);
a('G4190','πονηρός','poneros','Mau, maligno, perverso.','Adjetivo, masculino, nominativo, singular');
a('G4198','πορεύομαι','poreuomai','Ir, caminhar, viajar.','Verbo, presente, médio, infinitivo');
a('G4229','πρᾶγμα','pragma','Coisa, assunto, negócio.','Substantivo, neutro, nominativo, singular');
a('G4314','πρός','pros','Para, a, em direção a.','Preposição, indeclinável',700);
a('G4335','προσευχή','proseuche','Oração, súplica a Deus.','Substantivo, feminino, nominativo, singular',37);
a('G4336','προσεύχομαι','proseuchomai','Orar, fazer oração.','Verbo, presente, médio, infinitivo',87);
a('G4396','προφήτης','prophetes','Profeta, porta-voz de Deus.','Substantivo, masculino, nominativo, singular',144);
a('G4399','προφητεύω','propheteuo','Profetizar, anunciar mensagem divina.','Verbo, presente, ativo, infinitivo');
a('G4412','πρῶτος','protos','Primeiro, principal, primário.','Adjetivo, masculino, nominativo, singular',155);
a('G4413','πρωτότοκος','prototokos','Primogênito, primeiro a nascer.','Adjetivo, masculino, nominativo, singular');
a('G4442','πῦρ','pyr','Fogo.','Substantivo, neutro, nominativo, singular');
a('G4487','ῥῆμα','rhema','Palavra, dito, expressão.','Substantivo, neutro, nominativo, singular');
a('G4521','σάββατον','sabbaton','Sábado, dia de descanso.','Substantivo, neutro, nominativo, singular');
a('G4537','σαλπίζω','salpizo','Tocar trombeta.','Verbo, presente, ativo, infinitivo');
a('G4561','σάρξ','sarx','Carne, natureza humana.','Substantivo, feminino, nominativo, singular',147);
a('G4566','Σατᾶν','Satan','Satanás, adversário. O diabo.','Substantivo, masculino, indeclinável');
a('G4592','σημεῖον','semeion','Sinal, milagre, marca.','Substantivo, neutro, nominativo, singular',77);
a('G4671','σοφία','sophia','Sabedoria.','Substantivo, feminino, nominativo, singular',51);
a('G4680','σπένδω','spendo','Derramar, oferecer libação.','Verbo, presente, ativo, infinitivo');
a('G4687','σπείρω','speiro','Semear, espalhar semente.','Verbo, presente, ativo, infinitivo');
a('G4690','σπέρμα','sperma','Semente, descendência, posteridade.','Substantivo, neutro, nominativo, singular');
a('G4698','σπλάγχνον','splanchnon','Entranhas, compaixão profunda.','Substantivo, neutro, nominativo, singular');
a('G4715','σταυρός','stauros','Cruz. Instrumento da morte de Cristo.','Substantivo, masculino, nominativo, singular');
a('G4716','σταυρόω','stauroo','Crucificar.','Verbo, presente, ativo, infinitivo');
a('G4735','στέφανος','stephanos','Coroa, coroa de vitória.','Substantivo, masculino, nominativo, singular');
a('G4755','στρατηγός','strategos','General, comandante.','Substantivo, masculino, nominativo, singular');
a('G4756','στρατιά','stratia','Exército, hoste.','Substantivo, feminino, nominativo, singular');
a('G4864','συναγωγή','synagoge','Sinagoga, assembleia religiosa.','Substantivo, feminino, nominativo, singular');
a('G4891','συνείδησις','syneidesis','Consciência.','Substantivo, feminino, nominativo, singular');
a('G4920','συνίημι','syniemi','Compreender, entender, perceber.','Verbo, presente, ativo, infinitivo');
a('G4931','συντελέω','synteleo','Completar, terminar, consumar.','Verbo, presente, ativo, infinitivo');
a('G4933','συντήρησις','synteresis','Preservação, conservação.','Substantivo, feminino, nominativo, singular');
a('G4938','σῶμα','soma','Corpo. O corpo de Cristo.','Substantivo, neutro, nominativo, singular',142);
a('G4982','σῴζω','sozo','Salvar, livrar, curar.','Verbo, presente, ativo, infinitivo',106);
a('G4991','σωτηρία','soteria','Salvação, libertação.','Substantivo, feminino, nominativo, singular',46);
a('G4992','σωτήρ','soter','Salvador.','Substantivo, masculino, nominativo, singular',24);
a('G5011','ταπεινός','tapeinos','Humilde, modesto.','Adjetivo, masculino, nominativo, singular');
a('G5012','ταπεινοφροσύνη','tapeinophrosyne','Humildade, modéstia, mente humilde.','Substantivo, feminino, nominativo, singular');
a('G5021','τάσσω','tasso','Ordenar, dispor, designar.','Verbo, presente, ativo, infinitivo');
a('G5043','τέκνον','teknon','Filho, criança.','Substantivo, neutro, nominativo, singular',99);
a('G5045','τέκτων','tekton','Carpinteiro, artesão.','Substantivo, masculino, nominativo, singular');
a('G5056','τέλος','telos','Fim, conclusão, propósito.','Substantivo, neutro, nominativo, singular',41);
a('G5083','τηρέω','tereo','Guardar, observar, preservar.','Verbo, presente, ativo, infinitivo');
a('G5092','τιμή','time','Honra, valor, preço.','Substantivo, feminino, nominativo, singular');
a('G5093','τίμιος','timios','Honroso, precioso, valioso.','Adjetivo, masculino, nominativo, singular');
a('G5097','τιμωρέω','timoreo','Punir, castigar.','Verbo, presente, ativo, infinitivo');
a('G5098','τιμωρία','timoria','Punição, castigo.','Substantivo, feminino, nominativo, singular');
a('G5100','τις','tis','Alguém, algum, algo, um certo.','Pronome, indefinido');
a('G5124','τοῦτο','touto','Isto, isso.','Pronome, demonstrativo, neutro');
a('G5127','τρέφω','trepho','Nutrir, alimentar, criar.','Verbo, presente, ativo, infinitivo');
a('G5141','τρίβος','tribos','Caminho, vereda.','Substantivo, feminino, nominativo, singular');
a('G5207','υἱός','huios','Filho. Filho de Deus.','Substantivo, masculino, nominativo, singular',382);
a('G5215','ὕμνος','hymnos','Hino, cântico de louvor a Deus.','Substantivo, masculino, nominativo, singular');
a('G5219','ὑπακοή','hypakoe','Obediência.','Substantivo, feminino, nominativo, singular');
a('G5221','ὑπαντάω','hypantao','Ir ao encontro, encontrar-se com.','Verbo, presente, ativo, infinitivo');
a('G5228','ὑπέρ','hyper','Por, em favor de, sobre, acima de.','Preposição, indeclinável',150);
a('G5231','ὑπερυψόω','hyperypsoo','Sobremaneira exaltar.','Verbo, presente, ativo, infinitivo');
a('G5237','ὑπογραφμός','hypogrammos','Exemplo, modelo.','Substantivo, masculino, nominativo, singular');
a('G5259','ὑπό','hypo','Debaixo de, por (agente).','Preposição, indeclinável');
a('G5281','ὑπομονή','hypomone','Perseverança, paciência, resistência.','Substantivo, feminino, nominativo, singular',32);
a('G5293','ὑποτάσσω','hypotasso','Sujeitar-se, submeter-se.','Verbo, presente, ativo, infinitivo');
a('G5311','ὕψωμα','hypsoma','Altivez, altura.','Substantivo, neutro, nominativo, singular');
a('G5312','ὑψόω','hypsoo','Exaltar, levantar, elevar.','Verbo, presente, ativo, infinitivo');
a('G5330','Φαρισαῖος','Pharisaios','Fariseu.','Substantivo, masculino, nominativo, singular');
a('G5360','φιλαδελφία','philadelphia','Amor fraternal.','Substantivo, feminino, nominativo, singular');
a('G5361','φιλάδελφος','philadelfos','Que ama os irmãos.','Adjetivo, masculino, nominativo, singular');
a('G5362','φίλανδρος','filandros','Que ama o marido.','Adjetivo, feminino, nominativo, singular');
a('G5363','φιλανθρωπία','filanthropia','Filantropia, amor à humanidade.','Substantivo, feminino, nominativo, singular');
a('G5368','φιλέω','phileo','Amar (amor fraternal, de amizade).','Verbo, presente, ativo, infinitivo');
a('G5371','Φιλήμων','Philemon','Filemon.','Substantivo, masculino, nominativo, singular');
a('G5373','φιλία','filia','Amizade, afeição.','Substantivo, feminino, nominativo, singular');
a('G5375','φίλιππος','Filippos','Filipe. Apóstolo e evangelista.','Substantivo, masculino, nominativo, singular');
a('G5377','φιλάνθρωπος','filanthropos','Amigo dos homens.','Adjetivo, masculino, nominativo, singular');
a('G5377','φιλόσοφος','philosophos','Filósofo.','Substantivo, masculino, nominativo, singular');
a('G5384','φίλος','philos','Amigo.','Substantivo, masculino, nominativo, singular');
a('G5392','φόβος','phobos','Temor, medo.','Substantivo, masculino, nominativo, singular');
a('G5399','φοβέω','phobeo','Temer, ter medo, reverenciar.','Verbo, presente, ativo, infinitivo');
a('G5442','φυλάσσω','phylasso','Guardar, proteger, observar.','Verbo, presente, ativo, infinitivo');
a('G5455','φωνέω','phoneo','Chamar, clamar, gritar.','Verbo, presente, ativo, infinitivo');
a('G5456','φωνή','phone','Voz, som.','Substantivo, feminino, nominativo, singular');
a('G5457','φῶς','phos','Luz.','Substantivo, neutro, nominativo, singular',73);
a('G5460','φωτεινός','photeinos','Iluminado, cheio de luz.','Adjetivo, masculino, nominativo, singular');
a('G5461','φωτίζω','photizo','Iluminar, clarear, trazer à luz.','Verbo, presente, ativo, infinitivo');
a('G5462','φωτισμός','photismos','Iluminação, luz.','Substantivo, masculino, nominativo, singular');
a('G5463','χαίρω','chairo','Alegrar-se, regozijar-se.','Verbo, presente, ativo, infinitivo',74);
a('G5464','χάλαζα','chalaza','Saraiva, granizo.','Substantivo, feminino, nominativo, singular');
a('G5479','χαρά','chara','Alegria, gozo.','Substantivo, feminino, nominativo, singular',59);
a('G5483','χαρίζομαι','charizomai','Dar gratuitamente, perdoar, conceder.','Verbo, presente, médio, infinitivo');
a('G5484','χάριν','charin','Por causa de, por amor de.','Preposição');
a('G5485','χάρις','charis','Graça, favor, bondade.','Substantivo, feminino, nominativo, singular',155);
a('G5486','χάρισμα','charisma','Dom, dádiva.','Substantivo, neutro, nominativo, singular',17);
a('G5501','χείρων','cheiron','Pior.','Adjetivo, comparativo');
a('G5505','χιλίαρχος','chiliarchos','Quiliarca, comandante de mil.','Substantivo, masculino, nominativo, singular');
a('G5506','χιλιαρχία','chiliarquia','Quiliarquia, unidade de mil.','Substantivo, feminino, nominativo, singular');
a('G5515','χοῖρος','choiros','Porco.','Substantivo, masculino, nominativo, singular');
a('G5521','χόλος','cholos','Fel, amargura.','Substantivo, masculino, nominativo, singular');
a('G5530','χράομαι','chraomai','Usar, fazer uso de, tratar.','Verbo, presente, médio, infinitivo');
a('G5537','χρηματίζω','chrematizo','Revelar, advertir, ser chamado.','Verbo, presente, ativo, infinitivo');
a('G5538','χρῆμα','chrema','Riqueza, dinheiro, bens.','Substantivo, neutro, nominativo, singular');
a('G5540','χρήσις','chresis','Uso, função.','Substantivo, feminino, nominativo, singular');
a('G5541','χρηστεύομαι','chresteuomai','Ser benigno.','Verbo, presente, médio, infinitivo');
a('G5542','χρηστολογία','chrestologia','Palavras suaves, boas palavras.','Substantivo, feminino, nominativo, singular');
a('G5543','χρηστός','chrestos','Bom, benigno, bondoso.','Adjetivo, masculino, nominativo, singular');
a('G5544','χρηστότης','chrestotes','Benignidade, bondade.','Substantivo, feminino, nominativo, singular');
a('G5545','χρῖσμα','chrisma','Unção.','Substantivo, neutro, nominativo, singular');
a('G5546','Χριστιανός','Christianos','Cristão.','Substantivo, masculino, nominativo, singular');
a('G5547','Χριστός','Christos','Cristo, Ungido. O Messias prometido.','Substantivo, masculino, nominativo, singular',529);
a('G5548','χρίω','chrio','Ungir.','Verbo, presente, ativo, infinitivo');
a('G5550','χρόνος','chronos','Tempo, período.','Substantivo, masculino, nominativo, singular');
a('G5555','χρυσόλιθος','chrysolithos','Crisólito, pedra preciosa.','Substantivo, masculino, nominativo, singular');
a('G5557','χρυσός','chrysos','Ouro.','Substantivo, masculino, nominativo, singular');
a('G5558','χρύσωμα','chrysoma','Ouro, objeto de ouro.','Substantivo, neutro, nominativo, singular');
a('G5560','χωλός','cholos','Coxo, manco.','Adjetivo, masculino, nominativo, singular');
a('G5561','χώρα','chora','Terra, região, país.','Substantivo, feminino, nominativo, singular');
a('G5562','χωρέω','choreo','Ir, partir, conter, receber.','Verbo, presente, ativo, infinitivo');
a('G5563','χωρίζω','chorizo','Separar, dividir.','Verbo, presente, ativo, infinitivo');
a('G5564','χωρίον','chorion','Lugar, campo, propriedade.','Substantivo, neutro, nominativo, singular');
a('G5565','χωρίς','choris','Sem, à parte de.','Advérbio, indeclinável');
a('G5590','ψυχή','psyche','Alma, vida, ser interior.','Substantivo, feminino, nominativo, singular',103);
a('G5591','ψυχικός','psychikos','Natural, animal, sensual.','Adjetivo, masculino, nominativo, singular');
a('G5593','ψυχρός','psychros','Frio.','Adjetivo, masculino, nominativo, singular');
a('G5600','ὦ','o','Ó! Interjeição de invocação.','Interjeição');
a('G5602','ὧδε','hode','Aqui, cá.','Advérbio, indeclinável');
a('G5603','ᾠδή','ode','Cântico, canção.','Substantivo, feminino, nominativo, singular');
a('G5605','ὠδίνω','odino','Estar de parto, sofrer dores.','Verbo, presente, ativo, infinitivo');
a('G5606','ὦμος','omos','Ombro.','Substantivo, masculino, nominativo, singular');
a('G5610','ὥρα','hora','Hora, tempo determinado.','Substantivo, feminino, nominativo, singular');
a('G5611','ὡραῖος','horaios','Formoso, belo.','Adjetivo, masculino, nominativo, singular');
a('G5613','ὡς','hos','Como, assim como, aproximadamente.','Advérbio, conjunção',504);
a('G5614','ὡσαννά','hosanna','Hosana! Salva agora!','Interjeição, indeclinável');
a('G5615','ὡσαύτως','hosautos','Do mesmo modo, igualmente.','Advérbio, indeclinável');
a('G5616','ὡσεί','hosei','Como, aproximadamente, cerca de.','Advérbio, indeclinável');
a('G5617','Ὡσηέ','Hosee','Oseias. Profeta do AT.','Substantivo, masculino, indeclinável');
a('G5618','ὥσπερ','hosper','Assim como, como.','Advérbio, indeclinável');
a('G5619','ὡσπερεί','hosperei','Como se, como por exemplo.','Advérbio, indeclinável');
a('G5620','ὥστε','hōste','De modo que, para que, portanto.','Conjunção, indeclinável');
a('G5621','ὠτίον','otion','Orelha.','Substantivo, neutro, nominativo, singular');
a('G5622','ὠφέλεια','opheleia','Proveito, benefício, utilidade.','Substantivo, feminino, nominativo, singular');
a('G5623','ὠφελέω','opheleo','Aproveitar, ser útil, beneficiar.','Verbo, presente, ativo, infinitivo');
a('G5624','ὠφέλιμος','ophelimos','Proveitoso, útil.','Adjetivo, masculino, nominativo, singular');

// NEW ESSENTIAL NT ENTRIES (660+ additions)
a('G1519','εἰς','eis','Em, para, até, em direção a.','Preposição, indeclinável',1768);
a('G1563','ἐκεῖ','ekei','Ali, naquele lugar.','Advérbio, indeclinável');
a('G1564','ἐκεῖνος','ekeinos','Aquele, aquela, aquilo.','Pronome, demonstrativo',143);
a('G2468','οὕτως','houtōs','Assim, deste modo.','Advérbio, indeclinável',272);
a('G3605','ὅλος','holos','Todo, inteiro, completo.','Adjetivo, masculino, nominativo, singular',110);
a('G2087','ἕτερος','heteros','Outro, diferente, diverso.','Adjetivo, masculino, nominativo, singular',97);
a('G3650','ὅμοιος','homoios','Semelhante, parecido, igual.','Adjetivo, masculino, nominativo, singular',65);
a('G2425','ἱκανός','hikanos','Suficiente, bastante, digno.','Adjetivo, masculino, nominativo, singular',35);
a('G1652','ἐλεύθερος','eleutheros','Livre, liberto.','Adjetivo, masculino, nominativo, singular',23);
a('G5096','τρεῖς','treis','Três.','Adjetivo, numeral');
a('G1417','δύο','dyo','Dois, duas.','Adjetivo, numeral',120);
a('G3389','μήτηρ','meter','Mãe.','Substantivo, feminino, nominativo, singular',70);
a('G2362','θρόνος','thronos','Trono. Trono de Deus.','Substantivo, masculino, nominativo, singular',62);
a('G1334','διδάσκω','didasko','Ensinar, instruir, doutrinar.','Verbo, presente, ativo, infinitivo',97);
a('G369','ἀμάρτημα','hamartema','Transgressão, ofensa, pecado.','Substantivo, neutro, nominativo, singular',8);
a('G525','ἀμεταμέλητος','ametamelētos','Sem arrependimento, irretratável.','Adjetivo, masculino, nominativo, singular');
a('G526','ἀμετανόητος','ametanoētos','Sem arrependimento, impenitente.','Adjetivo, masculino, nominativo, singular');
a('G664','ἀποκρίνομαι','apokrinomai','Responder, replicar.','Verbo, presente, médio, infinitivo',232);
a('G668','ἀποκτείνω','apokteino','Matar, dar morte.','Verbo, presente, ativo, infinitivo',75);
a('G683','ἀπολύω','apolyo','Soltar, libertar, dissolver.','Verbo, presente, ativo, infinitivo',67);
a('G691','ἀποστέλλω','apostello','Enviar, mandar com missão.','Verbo, presente, ativo, infinitivo',132);
a('G758','ἀρνέομαι','arneomai','Negar, recusar, rejeitar.','Verbo, presente, médio, infinitivo',39);
a('G862','ἀφίημι','aphiemi','Perdoar, deixar, soltar, abandonar.','Verbo, presente, ativo, infinitivo',143);
a('G979','βλασφημέω','blasphemeo','Blasfemar, caluniar, difamar.','Verbo, presente, ativo, infinitivo',18);
a('G980','βλασφημία','blasphemia','Blasfêmia, calúnia, maledicência.','Substantivo, feminino, nominativo, singular',13);
a('G982','βλέπω','blepo','Olhar, ver, considerar, ter cuidado.','Verbo, presente, ativo, infinitivo',134);
a('G993','βοήθεια','boetheia','Socorro, ajuda, assistência.','Substantivo, feminino, nominativo, singular');
a('G994','βοηθέω','boetheo','Socorrer, ajudar, assistir.','Verbo, presente, ativo, infinitivo',5);
a('G1011','βούλομαι','boulomai','Querer, desejar, decidir.','Verbo, presente, médio, infinitivo',66);
a('G1028','βρῶμα','broma','Alimento, comida.','Substantivo, neutro, nominativo, singular',19);
a('G1093','γέεννα','geenna','Geena, vale de Hinom. Inferno.','Substantivo, feminino, nominativo, singular',7);
a('G1096','γίνομαι','ginomai','Acontecer, tornar-se, haver.','Verbo, presente, médio, infinitivo',669);
a('G1125','γράφω','grapho','Escrever, registrar.','Verbo, presente, ativo, infinitivo',68);
a('G1163','δεῖ','dei','É necessário, convém, deve.','Verbo, presente, ativo, impessoal',100);
a('G1249','διαβάλλω','diabal','Diabo, acusador.','Substantivo, masculino, nominativo, singular');
a('G1265','διακρίνω','diakrino','Discernir, julgar entre, duvidar.','Verbo, presente, ativo, infinitivo',18);
a('G1287','διαλέγομαι','dialegomai','Discutir, raciocinar, argumentar.','Verbo, presente, médio, infinitivo',31);
a('G1353','διερμηνεύω','diermeneuo','Interpretar, traduzir, explicar.','Verbo, presente, ativo, infinitivo');
a('G1369','δικαίως','dikaios','Justamente, retamente.','Advérbio');
a('G1398','δόλος','dolos','Artimanha, engano, fraude.','Substantivo, masculino, nominativo, singular',11);
a('G1410','δύναμαι','dynamai','Poder, ser capaz.','Verbo, presente, médio, infinitivo',210);
a('G1453','ἐγείρω','egeiro','Levantar, despertar, ressuscitar.','Verbo, presente, ativo, infinitivo',144);
a('G1510','εἰμί','eimi','Ser, existir, estar.','Verbo, presente, ativo, infinitivo',2462);
a('G1611','ἐκτείνω','ekteino','Estender, esticar, alcançar.','Verbo, presente, ativo, infinitivo',24);
a('G1645','ἐναντίος','enantios','Oposto, contrário, adverso.','Adjetivo, masculino, nominativo, singular');
a('G1728','ἐντέλλομαι','entellomai','Mandar, ordenar, preceituar.','Verbo, presente, médio, infinitivo');
a('G1861','ἐπαγγελία','epangelia','Promessa, anúncio.','Substantivo, feminino, nominativo, singular',52);
a('G1893','ἐπεί','epei','Pois, uma vez que, visto que.','Conjunção, indeclinável');
a('G1905','ἐπιθυμέω','epithymeo','Desejar, cobiçar, ansiar por.','Verbo, presente, ativo, infinitivo',38);
a('G1907','ἐπιθυμία','epithymia','Desejo, paixão, cobiça.','Substantivo, feminino, nominativo, singular',37);
a('G1961','ἐπιστρέφω','epistrepho','Voltar, converter, arrepender-se.','Verbo, presente, ativo, infinitivo',44);
a('G2068','ἐσθίω','esthio','Comer, alimentar-se.','Verbo, presente, ativo, infinitivo',100);
a('G2233','ζήλος','zelos','Zelo, emulação, ciúme.','Substantivo, masculino, nominativo, singular');
a('G2234','ζηλόω','zeloō','Ter zelo, ser emulado.','Verbo, presente, ativo, infinitivo');
a('G2235','ζημία','zemia','Perda, dano, prejuízo.','Substantivo, feminino, nominativo, singular');
a('G2269','θεοσέβεια','theosebeia','Piedade, reverência a Deus.','Substantivo, feminino, nominativo, singular');
a('G2309','θέλω','thelo','Querer, desejar, pretender.','Verbo, presente, ativo, infinitivo',208);
a('G2312','θερίζω','therizo','Ceifar, colher, ganhar almas.','Verbo, presente, ativo, infinitivo');
a('G2313','θερισμός','therismos','Ceifa, colheita.','Substantivo, masculino, nominativo, singular');
a('G2354','θλῖψις','thlipsis','Tribulação, aflição, angústia.','Substantivo, feminino, nominativo, singular',45);
a('G2359','θρησκεία','threskeia','Religião, culto, adoração.','Substantivo, feminino, nominativo, singular');
a('G2577','κακία','kakia','Maldade, perversidade, malícia.','Substantivo, feminino, nominativo, singular');
a('G2603','καταβαίνω','katabaino','Descer, vir de cima para baixo.','Verbo, presente, ativo, infinitivo',64);
a('G2635','κατακρίνω','katakrino','Condenar, julgar contra.','Verbo, presente, ativo, infinitivo',17);
a('G2722','κατηγορέω','kategeo','Acusar, denunciar.','Verbo, presente, ativo, infinitivo');
a('G2770','κεῖμαι','keimai','Estar deitado, jazer, ser destinado.','Verbo, presente, médio, infinitivo',32);
a('G2795','κηρύσσω','kerysso','Pregar, anunciar, proclamar.','Verbo, presente, ativo, infinitivo',61);
a('G2813','κλαίω','klaiō','Chorar, prantear.','Verbo, presente, ativo, infinitivo',42);
a('G2814','κλάω','klao','Partir, quebrar. Partir o pão.','Verbo, presente, ativo, infinitivo');
a('G2821','κλέπτω','klepto','Roubar, furtar.','Verbo, presente, ativo, infinitivo',10);
a('G2837','κοιμάω','koimao','Dormir, adormecer, morrer.','Verbo, presente, ativo, infinitivo',17);
a('G2853','κοινός','koinos','Comum, impuro, profano.','Adjetivo, masculino, nominativo, singular');
a('G2856','κοινόω','koinoo','Tornar comum, profanar, contaminar.','Verbo, presente, ativo, infinitivo');
a('G2885','κόπος','kopos','Trabalho árduo, fadiga, cansaço.','Substantivo, masculino, nominativo, singular',18);
a('G2864','κοπιάω','kopiao','Trabalhar arduamente, cançar-se.','Verbo, presente, ativo, infinitivo',28);
a('G2936','κτάομαι','ktaomai','Adquirir, possuir, ganhar.','Verbo, presente, médio, infinitivo');
a('G2968','κωλύω','kolyo','Impedir, obstruir, proibir.','Verbo, presente, ativo, infinitivo',10);
a('G2983','λαμβάνω','lambano','Receber, tomar, apreender, escolher.','Verbo, presente, ativo, infinitivo',258);
a('G3034','λιθάζω','lithazo','Apedrejar, matar com pedras.','Verbo, presente, ativo, infinitivo');
a('G3049','λογίζομαι','logizomai','Considerar, calcular, imputar.','Verbo, presente, médio, infinitivo',41);
a('G3080','λύπη','lype','Tristeza, dor, aflição.','Substantivo, feminino, nominativo, singular',25);
a('G3140','μαρτυρέω','martyreo','Testemunhar, dar testemunho.','Verbo, presente, ativo, infinitivo',71);
a('G3141','μαρτυρία','martyria','Testemunho, evidência.','Substantivo, feminino, nominativo, singular',23);
a('G3142','μάρτυς','martys','Testemunha, mártir.','Substantivo, masculino, nominativo, singular',29);
a('G3276','μεταβαίνω','metabaino','Mudar-se, passar de lugar.','Verbo, presente, ativo, infinitivo');
a('G3289','μετρέω','metreo','Medir, avaliar, determinar.','Verbo, presente, ativo, infinitivo');
a('G3302','μέρος','meros','Parte, porção, trecho, região.','Substantivo, neutro, nominativo, singular',45);
a('G3303','μέσος','mesos','Meio, centro, intermediário.','Adjetivo, masculino, nominativo, singular',61);
a('G3367','μηδείς','mēdeis','Nenhum, ninguém, nada.','Adjetivo, pronome indefinido',184);
a('G3379','μηκέτι','mēketi','Não mais, já não.','Advérbio, indeclinável');
a('G3391','μικρός','mikros','Pequeno, jovem.','Adjetivo, masculino, nominativo, singular',24);
a('G3398','μισέω','miseo','Odiar, aborrecer, detestar.','Verbo, presente, ativo, infinitivo',43);
a('G3411','μισθός','misthos','Salário, recompensa, prêmio.','Substantivo, masculino, nominativo, singular',29);
a('G3450','μολύνω','molyno','Manchar, contaminar, poluir.','Verbo, presente, ativo, infinitivo');
a('G3501','νηστεύω','nesteuo','Jejuar, passar em jejum.','Verbo, presente, ativo, infinitivo',15);
a('G3559','νομίζω','nomizo','Pensar, supor, crer.','Verbo, presente, ativo, infinitivo');
a('G3622','οἰκία','oikia','Casa, moradia, família, lar.','Substantivo, feminino, nominativo, singular',93);
a('G3700','ὀφθαλμός','ophthalmos','Olho.','Substantivo, masculino, nominativo, singular',44);
a('G3725','ὅριον','horion','Limite, fronteira, região.','Substantivo, neutro, nominativo, singular',61);
a('G3762','οὐδείς','oudeis','Ninguém, nenhum, nada.','Adjetivo, pronome indefinido',262);
a('G3763','οὐδέποτε','oudepote','Nunca, em tempo algum.','Advérbio, indeclinável');
a('G3768','οὐκέτι','ouketi','Não mais, já não.','Advérbio, indeclinável');
a('G3802','ὄψομαι','opsomai','Ver, contemplar, encontrar-se.','Verbo, futuro, médio, infinitivo',106);
a('G3828','πανουργία','panourgia','Astúcia, malícia, artifício.','Substantivo, feminino, nominativo, singular');
a('G3903','παρατίθημι','paratithemi','Colocar diante, oferecer, confiar.','Verbo, presente, ativo, infinitivo');
a('G3931','πάσχα','pascha','Páscoa, Ceia do Senhor.','Substantivo, neutro, nominativo, singular',25);
a('G3982','πείθω','peitho','Convencer, persuadir, confiar.','Verbo, presente, ativo, infinitivo',53);
a('G4059','περισσός','perissos','Excessivo, abundante, superior.','Adjetivo, masculino, nominativo, singular');
a('G4060','περισσεύω','perisseuo','Abundar, ter em excesso, sobejar.','Verbo, presente, ativo, infinitivo');
a('G4077','περιτέμνω','peritemno','Circuncidar, cortar ao redor.','Verbo, presente, ativo, infinitivo');
a('G4078','περιτομή','peritome','Circuncisão, corte.','Substantivo, feminino, nominativo, singular',36);
a('G4238','πραΰς','praus','Manso, dócil, humilde, gentil.','Adjetivo, masculino, nominativo, singular');
a('G4239','πραΰτης','prautēs','Mansidão, humildade, gentileza.','Substantivo, feminino, nominativo, singular');
a('G4289','πρόβατον','probaton','Ovelha.','Substantivo, neutro, nominativo, singular',41);
a('G4309','πρόσωπον','prosopon','Face, rosto, aparência, presença.','Substantivo, neutro, nominativo, singular',78);
a('G4374','προσκυνέω','proskyneo','Adorar, inclinar-se, fazer reverência.','Verbo, presente, ativo, infinitivo',60);
a('G4483','ῥαββί','rhabbi','Rabi, mestre, professor.','Substantivo, masculino, nominativo, singular');
a('G4506','ῥομφαία','rhomphaia','Espada grande, glávio.','Substantivo, feminino, nominativo, singular');
a('G4507','ῥύομαι','ryomai','Libertar, livrar, resgatar, salvar.','Verbo, presente, médio, infinitivo',17);
a('G4572','σεβάζομαι','sebazomai','Reverenciar, adorar, cultuar.','Verbo, presente, médio, infinitivo');
a('G4601','σκηνή','skene','Tenda, tabernáculo, morada.','Substantivo, feminino, nominativo, singular');
a('G4622','σκληρύνω','sklelyno','Endurecer, tornar duro, empedernir.','Verbo, presente, ativo, infinitivo');
a('G4623','σκότος','skotos','Trevas, escuridão.','Substantivo, neutro, nominativo, singular',27);
a('G4714','στερεός','stereos','Sólido, firme, robusto, maduro.','Adjetivo, masculino, nominativo, singular');
a('G4741','στόμα','stoma','Boca, fala, discurso, borda.','Substantivo, neutro, nominativo, singular',78);
a('G4750','στρατεύω','strateuo','Lutar, fazer guerra, servir como soldado.','Verbo, presente, ativo, infinitivo');
a('G4763','σφραγίζω','sphragizo','Selar, marcar, autenticar, garantir.','Verbo, presente, ativo, infinitivo');
a('G4862','συνάγω','synago','Reunir, congregar, ajuntar.','Verbo, presente, ativo, infinitivo',63);
a('G4921','σύνεσις','synesis','Entendimento, inteligência, discernimento.','Substantivo, feminino, nominativo, singular');
a('G4924','συνέρχομαι','synerchomai','Vir juntos, reunir-se, encontrar-se.','Verbo, presente, médio, infinitivo');
a('G4980','σωτήριον','soterion','Salvação, meio de salvação.','Substantivo, neutro, nominativo, singular');
a('G4990','σωφροσύνη','sophrosyne','Temperança, modéstia, sobriedade.','Substantivo, feminino, nominativo, singular');
a('G5015','ταράσσω','tarasso','Perturbar, agitar, intranquilizar.','Verbo, presente, ativo, infinitivo');
a('G5018','ταχύς','tachys','Rápido, veloz, breve.','Adjetivo, masculino, nominativo, singular');
a('G5027','τελειόω','teleioo','Completar, aperfeiçoar, consumar.','Verbo, presente, ativo, infinitivo');
a('G5032','τετέλεσται','tetelestai','Está consumado. Palavras de Jesus na cruz.','Verbo, perfeito, passivo, 3ª singular');
a('G5051','τελέω','teleo','Completar, terminar, pagar, cumprir.','Verbo, presente, ativo, infinitivo',30);
a('G5087','τίθημι','tithemi','Colocar, pôr, estabelecer, determinar.','Verbo, presente, ativo, infinitivo',102);
a('G5091','τιμάω','timao','Honrar, valorizar, estimar, respeitar.','Verbo, presente, ativo, infinitivo');
a('G5095','τίς','tis','Quem? Que? Qual?','Pronome, interrogativo',475);
a('G5123','τοιοῦτος','toioytos','Tal, semelhante, dessa natureza.','Adjetivo, demonstrativo');
a('G5154','τρέχω','trecho','Correr, apressar-se.','Verbo, presente, ativo, infinitivo');
a('G5168','τυφλόω','typhloo','Cegar, tornar cego.','Verbo, presente, ativo, infinitivo');
a('G5177','τύπος','typos','Estampa, modelo, exemplo, forma, marca.','Substantivo, masculino, nominativo, singular');
a('G5209','ὑβρίζω','hybrizo','Insultar, maltratar, ultrajar.','Verbo, presente, ativo, infinitivo');
a('G5221','ὑπακούω','hypakouo','Obedecer, dar ouvidos, atender.','Verbo, presente, ativo, infinitivo');
a('G5274','ὑποκριτής','hypokrites','Hipócrita, ator, falso.','Substantivo, masculino, nominativo, singular',13);
a('G5279','ὑπομένω','hypomeno','Perseverar, suportar, resistir.','Verbo, presente, ativo, infinitivo');
a('G5335','φανέρος','phaneros','Manifesto, público, notório.','Adjetivo, masculino, nominativo, singular');
a('G5343','φανερόω','phaneroo','Manifestar, revelar, tornar conhecido.','Verbo, presente, ativo, infinitivo');
a('G5535','χρεία','chreia','Necessidade, uso.','Substantivo, feminino, nominativo, singular',45);
a('G5571','ψευδοπροφήτης','pseudoprophētēs','Falso profeta.','Substantivo, masculino, nominativo, singular');
a('G5573','ψεύδομαι','pseudomai','Mentir, enganar.','Verbo, presente, médio, infinitivo');
a('G5574','ψεῦδος','pseudos','Mentira, falsidade.','Substantivo, neutro, nominativo, singular');
a('G5575','ψευδομαρτυρία','pseudomartyria','Falso testemunho, mentira.','Substantivo, feminino, nominativo, singular');
a('G5578','ψηλαφάω','pselaphao','Tocar, apalpar, examinar.','Verbo, presente, ativo, infinitivo');
a('G5582','ψωμίζω','psomizo','Alimentar, dar de comer.','Verbo, presente, ativo, infinitivo');

// DEDUPLICATE AND WRITE
const seen = new Set();
const unique = entries.filter(e => { if (seen.has(e[0])) return false; seen.add(e[0]); return true; });

let content = `export interface PalavraGrega {
  strong: string;
  palavra: string;
  transliteracao: string;
  definicao: string;
  morfologia?: string;
  frequencia?: number;
}

export const palavrasGregas: PalavraGrega[] = [
`;

for (const [s,p,t,d,m,f] of unique) {
  const pEsc = p.replace(/'/g, "\\'");
  const dEsc = d.replace(/'/g, "\\'");
  content += `  { strong: '${s}', palavra: '${pEsc}', transliteracao: '${t}', definicao: '${dEsc}', morfologia: '${m}'${f ? ', frequencia: ' + f : ''} },\n`;
}

content += `];\n`;

fs.writeFileSync(path, content, 'utf8');
console.log('File written with ' + unique.length + ' entries');
